### ISSUE TITLE
Multiple bundles

### ISSUE THREAD

**Issue by nickdima** [ampedandwired/html-webpack-plugin#1]
I have a use case where I'm using the `ExtractTextPlugin` for generating a css file. In this case there's an extra bundle generated for the same chunk (one js file and one css file).
Looking at the code I see that you're just taking the first element when the chunk is an array, but with my use case I would need to get access to the second item which is the `css` file.
The ideal option here would be to get the specific item from the array by specifying the index in the template, like this: `{%=o.htmlWebpackPlugin.assets.styles[1]%}` and fallback to the first item when not specifying an index.
With the current codebase this doesn't seem doable, as you just pass the data structure to the template engine.
Any thoughts? For my own use I just changed it so you always need to specify the index when the chunk is an array, but this won't work when switching back and forth between building with and without source maps.

**Comment by jantimon** [comment]
The pull request #14 adds all ExtractTextPlugins to the head element

**Comment by ampedandwired** [comment]
Closing this now that #14 is merged. All generated css is now included in the default index.html, and details of the css files (per chunk and globally) are available in the `htmlWebpackPlugin.files` object.
