### ISSUE TITLE
Allow using a loader

### ISSUE THREAD

**Issue by Couto** [ampedandwired/html-webpack-plugin#10]
I'm not sure if this is a useful idea for other people, but it happens that my index.html file already contains some images. It would be nice to add the images to webpack's dependency graph.

Is it possible to use the [html-loader](https://github.com/webpack/html-loader) in conjunction with this plugin? Or is this idea too farfetched? 

Once again, thanks.

**Comment by ampedandwired** [comment]
This is a pretty interesting idea - I like it. To be honest I'm not too sure if it's possible, but I'll definitely take a look into it.

The webpack stats object actually contains the compiled code for each asset as a string, so conceivably we could take the output of the html-loader and use it as an input template into this plugin.

**Comment by andersekdahl** [comment]
I'd really like this as well. I want to add an `apple-touch-icon` link icon in index.html, and I currently have to require that in JS (even though JS doesn't use it) to force it into the pipeline, and then iterate over all modules in my html template to get the correct path for that file. I'd much rather be able to just do `{% o.require('./myimage.png') %}` in my template.

**Comment by SimenB** [comment]
@andersekdahl Could you post your code? I need a `favicon`, and I'm thinking this is the best way.
Ref #28

**Comment by jantimon** [comment]
So #41 allows to use loaders - could someone please give me some feedback on it?

**Comment by jantimon** [comment]
You can use the beta branch: `npm install html-webpack-plugin@2 --save-dev`
