### ISSUE TITLE
leading "//"  of publicPath became  "/"   

### ISSUE THREAD

**Issue by ftao** [ampedandwired/html-webpack-plugin#103]
when output.PublicPath   is    "//some.somecnd.com"  . ( // is necessary for  auto select http/https url  base on current page's protocol ) 
But in  the generated html , the url became  "/some.somecnd.com/xxx.js"   , should be 
 "//some.somecnd.com/xxx.js" 

I think this  change cause this problem 
https://github.com/ampedandwired/html-webpack-plugin/commit/396cdedf8a554465d00797bb4d279b085e2e05d8

**Comment by jantimon** [comment]
Actually this should have been fixed: 

https://github.com/ampedandwired/html-webpack-plugin/blob/feature/loaders/index.js#L333

**Comment by ftao** [comment]
Ok. Thanks .  I guess I will stick to 1.6.1  before next stable release .
