### ISSUE TITLE
The plugin breaks code with specific symbols

### ISSUE THREAD

**Issue by Kreozot** [ampedandwired/html-webpack-plugin#105]
I use d3.js. It includes this string (from [trigonometry.js](https://github.com/mbostock/d3/blob/master/src/math/trigonometry.js) in source):
```javascript
var ε = 1e-6, ε2 = ε * ε, π = Math.PI, τ = 2 * π, τε = τ - ε, halfπ = π / 2, d3_radians = π / 180, d3_degrees = 180 / π;
```
So if I build my script without html-webpack-plugin everything is ok, but if I do with, it turns into this:
```javascript
var Оµ = 1e-6, Оµ2 = Оµ * Оµ, ПЂ = Math.PI, П„ = 2 * ПЂ, П„Оµ = П„ - Оµ, halfПЂ = ПЂ / 2, d3_radians = ПЂ / 180, d3_degrees = 180 / ПЂ;
```
And this causes "Uncaught SyntaxError: Unexpected token ILLEGAL"

**Comment by jantimon** [comment]
Which version are you using?

**Comment by Kreozot** [comment]
The last. I've installed the plugin today.

**Comment by jantimon** [comment]
Actually we don't change the code webpack delivers..
I have no idea what this might cause
