### ISSUE TITLE
templateContent + webpack-dev-server

### ISSUE THREAD

**Issue by mjackson** [ampedandwired/html-webpack-plugin#106]
First off, just wanted to say thanks for such a great webpack plugin :) You guys have done an excellent job here.

I'm doing something a little unorthodox, but I was wondering if you guys might be interested in supporting webpack-dev-server inside `templateContent`. It's basically a poor man's static site generator.

I've currently got the following html-webpack-plugin config:

```js
    new HTMLWebpackPlugin({
      title: 'the index page',
      filename: 'index.html',
      templateContent: function () {
        var React = require('react')
        var IndexTemplate = require('./modules/components/IndexTemplate')
        return DOCTYPE + React.renderToStaticMarkup(
          React.createElement(IndexTemplate)
        )
      }
    })
```

When I put `./modules/components/IndexTemplate` in webpack's `entry` config, webpack-dev-server correctly recompiles the build when it changes. However, it looks like `templateContent` is only ever called once, so my template doesn't update.

Is this something you guys are interested in supporting? I could probably make a PR if so.

Thanks!

**Comment by jantimon** [comment]
did you try the 2.0 branch?

**Comment by mjackson** [comment]
@jantimon No, sorry. I didn't realize there was one. Can I install it via npm? Or just use git?

**Comment by jantimon** [comment]
npm install html-webpack-plugin@2 --save-dev
