### ISSUE TITLE
Specify which Webpack output (produced files) to include into HTML

### ISSUE THREAD

**Issue by ikornienko** [ampedandwired/html-webpack-plugin#108]
I'm using multiple instances of [ExtractTextPlugin](https://github.com/webpack/extract-text-webpack-plugin) to produce different .css files for every application theme that I have. I.e. I have ``theme-1.scss`` and ``theme-2.scss``, and multiple instances of ExtractTextPlugin (like ``new ExtractTextPlugin('theme-1', 'theme-1-[hash].css')``) to output separate ``theme-1-[hash].css`` and ``theme-2-[hash].css``. Everything is fine except that later HtmlWebpackPlugin inserts all themes into ``<head>``, breaking styling.

It would be nice to have a way to filter out what's included into the resulted HTML. E.g. 
```javascript
new HtmlWebpackPlugin({
  css: {
    included: [`{theme}-[hash].css`]
  }
})
```
(where variable ``theme`` could come via CLI args that are provided when build script is invoked).

Though this way it doesn't look so pretty to me... Maybe I'm just doing it all wrong, or is it a valid request to have ability to filter the Webpack output to be included into HTML?

**Comment by jantimon** [comment]
Couldn't you solve this with a template?
There is a include/exclude feature already but its for each chunk

**Comment by ikornienko** [comment]
Yes, ``chunks`` and ``excludeChunks`` doesn't fit well in my case. But template... I somehow missed the whole opportunity to specify ``inject: false`` and do all the logic of filtering in the template. It's exactly what I need! @jantimon thanks a lot for pointing at it!

Don't see any reason to bloat this nice plugin with additional filtering options, so closing this issue.
