### ISSUE TITLE
Sort of the chunks in HTML

### ISSUE THREAD

**Issue by tamascsaba** [ampedandwired/html-webpack-plugin#109]
I use this config:
```
    new HtmlWebpackPlugin({
      title: HTML.title,
      filename: HTML.filename,
      chunks: ['common', 'vendors', 'app']
    })
```

but chunks in template render wrong:
```
    <script src="common.js"></script>
    <script src="app.js"></script>
    <script src="vendors.js"></script>
```

My webpack config looks like:
https://github.com/AngularClass/angular2-webpack-starter/blob/master/webpack.config.js

**Comment by tamascsaba** [comment]
If I remove orderEntryLast from 206. line, then order is good.

**Comment by jantimon** [comment]
Maybe we could export this as a config setting which allows you to give an array of chunk names (for an explicit order), 'auto' for orderEntryLast as default or 'none'

**Comment by tamascsaba** [comment]
It would be great  :)

**Comment by tamascsaba** [comment]
https://github.com/ampedandwired/html-webpack-plugin/pull/110

**Comment by jantimon** [comment]
Okay merged it into master and on the 2.x.x beta branch.
Could you please add some unit tests so we can release a new version?

**Comment by tamascsaba** [comment]
Yes, of course :)

**Comment by jantimon** [comment]
Released as 1.7.0 and 2.1.0

**Comment by tamascsaba** [comment]
thx :+1:

**Comment by alex88** [comment]
There's no doc about sortchunks right?

**Comment by alex88** [comment]
Nvm found it's chunksSortMode

**Comment by tamascsaba** [comment]
chunksSortMode: Allows to control how chunks should be sorted before they are included to the html. Allowed values: 'none' | 'auto' | 'dependency' | {function} - default: 'auto'

**Comment by alex88** [comment]
Yeah I've seen that, thanks!
