### ISSUE TITLE
Not serving the main plus html on Windows. Works fine on Mac OS X

### ISSUE THREAD

**Issue by AddictArts** [ampedandwired/html-webpack-plugin#111]
I get the directory browser, listing of the files, on Windows. On a Mac I get my react components. Don't see any errors, or why it is happening.

Project is at https://github.com/SRI-SAVE/react-components

Thanks for the help.

**Comment by jantimon** [comment]
probably a webpack-dev-server issue

**Comment by AddictArts** [comment]
My bad, I'm really sorry. If you use a regex to detect webpack-dev-server in the args it appears without ".js" on *nix and with ".js" on Windows. So, that is all I needed to fix. I was conditionally adding the plugin. Maybe separate webpack configs is better and avoid the noise of conditional logic. Please close this non-issue.
