### ISSUE TITLE
Template variables are not evaluated. What am I doing wrong?

### ISSUE THREAD

**Issue by 0x80** [ampedandwired/html-webpack-plugin#112]
This is my template.html
```html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>{%=o.htmlWebpackPlugin.options.title || 'Webpack App'%}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body>
    <div id='app'></div>
  </body>
</html>
```

And my plugin config
```javascript
new HtmlWebpackPlugin({
      title: 'My App',
      filename: 'index.html',
      template: 'template.html',
      inject: true
    }),
```

In the output the title is still `{%=o.htmlWebpackPlugin.options.title || 'Webpack App'%}`. What am I missing?

Since I'm at it maybe someone would like to clarify 2 things for me as well:
- Why doesn't the default template have a div element to attach your app to? Doing this on the body tag directly is considered bad practice afaik. It's the only reason I'm creating my own template here...
- I don't quite understand the new html loader feature in v2. Why whould you want to use an html loader?

**Comment by jeberly** [comment]
I had the same issue fwiw, new install.

**Comment by jantimon** [comment]
The template language changed from 1 to 2: https://github.com/ampedandwired/html-webpack-plugin/tree/feature/loaders 

Try:

```
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8"/>
    <title><%= htmlWebpackPlugin.options.title %></title>
  </head>
  <body>
  </body>
</html>
```

The loader allows you to use any template language you like, jade, ejs, even react.

**Comment by 0x80** [comment]
Aha! :+1: 

Can you maybe also tell me in what scenario you'd want to use an html loader?

**Comment by jantimon** [comment]
You can use your prefered template language and it gathers resources like images for your result bundle.

It also allows you to prerender a single page application.

**Comment by 0x80** [comment]
Sounds good :smile:  Any example code you could point me to?

**Comment by jantimon** [comment]
Take a look at the 2.0 readme: 
https://github.com/ampedandwired/html-webpack-plugin/tree/feature/loaders
