### ISSUE TITLE
History API and url mismatch

### ISSUE THREAD

**Issue by prasannavl** [ampedandwired/html-webpack-plugin#118]
When using the history API, with route `/test/test2`

And when the default html files is `/index.html`
All the css, and js that are automatically added by the plugin fails to load, since its path is relative. Any way to fix this?

Either make an absolute path available, or derive from the public path, which is "/"?

**Comment by prasannavl** [comment]
Well, that's odd, because I do have public path set to "/". But the plugin seems to be adding the full path to it ending up in failed css, and js requests.

**Comment by thomasgwatson** [comment]
I'm experiencing this issue now with webpack 2, React Router (history API) and this puligin and got it working with the below (based on the publicPath advice above)

```javascript
 const {ifProd, ifNotProd, ifDev} = getIfUtils(env)

    entry: {
      app: resolve(PATHS.app, './main.js'),
      vendor: ['react'],
    },
    output: {
      path: PATHS.build,
      filename: ifProd('bundle.[name].[chunkhash].js', 'bundle.[name].js'),
      pathinfo: ifNotProd(),
      publicPath: '/',
    },
...
    devServer: {
      contentBase: resolve(__dirname, '../src'),
      port: 3030,
      historyApiFallback: {index: '/'},
    },
```
