### ISSUE TITLE
Automatically add JS/CSS to HTML files for CDN resources

### ISSUE THREAD

**Issue by cowwoc** [ampedandwired/html-webpack-plugin#12]
Tobias seems to think this feature request might be a good fit for your library: https://github.com/webpack/webpack/issues/754#issuecomment-72536024

I have the following concerns:
1. I want to provide an existing HTML file.
2. Ideally, I want to work with well-formed HTML files (not containing any templates). I expect the plugin to append `<script>` and `<link>` tags to the end of `<head>`.

What do you think? Are you willing to add this to this plugin?

**Comment by jantimon** [comment]
I really like the idea of appending to an existing html file.

This would allow to drop the blueimp template system and have a much cleaner interface.
What do you think about this @ampedandwired ?
