### ISSUE TITLE
Master out of sync?

### ISSUE THREAD

**Issue by franz-josef-kaiser** [ampedandwired/html-webpack-plugin#122]
After reading #112 I was looking at `master` and comparing it to the `2.0.4` beta tag. Could it be that there was something getting out of sync and maybe some branch wasn't merged? The `master` still features the "old" template tag style, while the v2.x already features the new template language?

**Comment by jantimon** [comment]
The link on the readme page redirects to the 2.x.x branch: https://github.com/ampedandwired/html-webpack-plugin/tree/feature/loaders
