### ISSUE TITLE
Page-per-entry point

### ISSUE THREAD

**Issue by loganb** [ampedandwired/html-webpack-plugin#125]
Hello, 

I was looking over the documentation, but I can't to find a way to build one page per entry point. I have multiple entry points in my project, one per "page." 

I know I can include HtmlWebpackPlugin multiple times in my webpack config, but I can't figure out how to specify which entry point goes with each page. Any thoughts? Thanks!

**Comment by jantimon** [comment]
You can limit the chunks for each html file: https://github.com/ampedandwired/html-webpack-plugin#filtering-chunks
