### ISSUE TITLE
replace script tag's src attribute

### ISSUE THREAD

**Issue by todo-mvc** [ampedandwired/html-webpack-plugin#126]
what about just replace the script tag's  src attribute without create new file;
i have a file which name is index.ejs(who is a template for ejs or other template engine)
(index.ejs);
``` ... <script src="index.js" ></script> ... ```
to
``` ...  <script src="index.[hash].js"></script>  ... ```

course of i will upload static files to cdn server, but webserver will runs on ourself server,& i don't want to replace the tags manaul,
is there any idear?

**Comment by jantimon** [comment]
Try `{%=o.htmlWebpackPlugin.webpack.hash%}` inside the template

**Comment by PinkyJie** [comment]
@jantimon Thanks, works for me, but it should be `{%=o.webpack.hash%}`.

**Comment by jantimon** [comment]
Oh - okay cool :+1:
