### ISSUE TITLE
[1.7.0] o.htmlWebpackPlugin.files.js misses files

### ISSUE THREAD

**Issue by liubko** [ampedandwired/html-webpack-plugin#127]
After I updated to `1.7.0` I have this problem that `index.tmpl` doesn't include all necessary files.

I use the following code in my `index.tmpl`
```
{% o.htmlWebpackPlugin.files.js.forEach(function(item) { %}
    <script src="{%= item %}" type="text/javascript"></script>
{% }); %}
```
but in only creates one `<script>` tag, when should have been created two.

If it make any difference, I use `webpack-split-by-path`

**Comment by jantimon** [comment]
Maybe because of: https://github.com/ampedandwired/html-webpack-plugin/pull/115
Maybe webpack split by path does not add "initial" to the bundle

**Comment by GreenGremlin** [comment]
Adding css-loader to the ignore option fixed this, for me.

``` JavaScript
    new SplitByPathPlugin(
      [{ name: 'vendor', path: __dirname + '/node_modules' }],
      { ignore: [__dirname + '/node_modules/css-loader'] }
    ),
```
