### ISSUE TITLE
[2.1.0] css and js are not injected when html minified via html-loader

### ISSUE THREAD

**Issue by avaragado** [ampedandwired/html-webpack-plugin#128]
I'm using html-webpack-plugin 2.1.0 to process a jade template into html (using html-loader 0.4.0 and jade-html-loader 0.0.3, with webpack 1.12.6).

Everything works fine until I turn on minimisation. With minimisation on, the built html does not include the injected link and script tags, and consequently the page is broken.

Loader configuration:

```js
{
    test: /\.jade$/,
    loaders: [
        'html',
        'jade-html',
    ]
},
```

Plugin configuration: 

```js
new HtmlWebpackPlugin({
    filename: 'index.html',
    template: path.resolve(__dirname, 'src', 'index.jade')
}),
```

I've tracked down the cause. When minimisation is on, html-loader calls the html minifier with `removeOptionalTags` true. This breaks the `HtmlWebpackPlugin.prototype.injectAssetsIntoHtml` method, which looks for closing head and closing body tags. The html minifier has removed the head and body tags, as they're optional, so the link and script tags are never injected.

See https://github.com/webpack/html-loader/blob/master/index.js#L71

Workaround: explicitly disable `removeOptionalTags` in html-loader:

```js
{
    test: /\.jade$/,
    loaders: [
        'html?removeOptionalTags=false',
        'jade-html',
    ]
},
```

**Comment by jantimon** [comment]
Wow nice! :+1: 

As said in the following article it is not possible to place a script at the end of a body tag if there is no body tag:
http://perfectionkills.com/experimenting-with-html-minifier/#remove_optional_tags

However we should at least print a warning:
https://github.com/ampedandwired/html-webpack-plugin/blob/feature/loaders/index.js#L459-L475

**Comment by jantimon** [comment]
Looks like the html-loader might be fixed: https://github.com/chrisnicola/html-loader/commit/b797acf13765c425836588f4fa4d24ac942db730

**Comment by jantimon** [comment]
Fixed: https://github.com/ampedandwired/html-webpack-plugin/commit/68428b583f359849c798f71e64855613b67ae4e8
