### ISSUE TITLE
Conflict with Jinja2 Template Engine

### ISSUE THREAD

**Issue by lifei** [ampedandwired/html-webpack-plugin#136]
Both Jinja2 and blueimp templates using {{ }} as markers. They are conflict. There is no way to change blueimp templates's markers.

**Comment by jantimon** [comment]
Have you tried the 2.x beta branch with a loader?

**Comment by jantimon** [comment]
Duplicate of #137

**Comment by lifei** [comment]
This one is different from #137 , this one is talk about markers, #137 is talk about {% extends %}

**Comment by jantimon** [comment]
But the solution is the same. 1.x does not support Jinja2 please use 2.x.
