### ISSUE TITLE
CAT NOT use Jinja2 extends features with html-webpack-plugin

### ISSUE THREAD

**Issue by lifei** [ampedandwired/html-webpack-plugin#137]
jinja2 templates:

base.html

<head></head><body>{% block content %}</body>

a.html

{% extends 'base.html' %}
{% block content %}
balabala
{% endblock %}

b.html

{% extends 'base.html' %}
{% block content %}
balabala
{% endblock %}

there's no way to inject output code.

**Comment by jantimon** [comment]
Have you tried the 2.x beta branch with a loader?

**Comment by lifei** [comment]
thank you for reply, is there a example?

**Comment by jantimon** [comment]
The 2.0 readme is a good start: https://github.com/ampedandwired/html-webpack-plugin/tree/feature/loaders

And there is an example for jade which should be very similar to your case:
https://github.com/ampedandwired/html-webpack-plugin/tree/feature/loaders/examples/jade-loader
