### ISSUE TITLE
Add disable option

### ISSUE THREAD

**Issue by cesarandreu** [ampedandwired/html-webpack-plugin#139]
It would be convenient to have a `disable` option. There's other plugins that provide an option to disable em, for example: [extract-text-webpack-plugin](https://github.com/webpack/extract-text-webpack-plugin#api).

I'm using a single file as my webpack configuration builder, and it generally works out nicely. However, in cases where I want to toggle a plugin on or off, it gets somewhat more difficult to read.

Here's an example of how it would look with a disable option:

```js
{
  // ... other config
  plugins: [
    // ... other plugins
    new HtmlWebpackPlugin({
      templateContent: htmlTemplate,
      inject: true,
      disable: TEST
    })
  ]
}
```

In this example, when I make a build, whether it's for production or development, I want to to output the `index.html`. However, if I'm generating a test build I want to turn it off.

Right now it ends up looking something akin to this:

```js
{
  // ... config options
  plugins: [
    // ... plugins
    ...(TEST
      ? []
      : [
        new HtmlWebpackPlugin({
          // html config
        })
      ]
    ),
    // ... more plugins
  ]
}
```

I could move it into a function, but then you need to jump more to follow the config.

Thoughts?

**Comment by jantimon** [comment]
The reason why extract text plugin provides the disabled function is that the loader would crash if the plugin is not there
