### ISSUE TITLE
Watch for Changes in template files

### ISSUE THREAD

**Issue by arb** [ampedandwired/html-webpack-plugin#141]
I'm using Jade to build essentially a static site and I want to use this plugin to add the script to the Jade compilation. How can I have webpack watch the jade files and rerun the build without having to include them in the bundle?

I tried the `IgnorePlugin` as well as trying a "noop" style loader for the .jade files and it did not work.

**Comment by jantimon** [comment]
Are you using 1.x or 2.x?

**Comment by arb** [comment]
1. I try to avoid beta versions whenever possible. If there isn't a solution using version 1, what would the solution be using version 2?

**Comment by jantimon** [comment]
Loaders work only with 2.x not with 1.x - you can only watch blueimp templates with 1.x

**Comment by arb** [comment]
Assuming I do use the loader route, how do I pass in the data provided by plugin into the tempateing engine to add the correct script tag? That was one of the things I liked about just supplying a function, I had complete control over the rendering context.

**Comment by jantimon** [comment]
Use the inject feature instead - it will just add the scripts automatically.

**Comment by jantimon** [comment]
Take a look at the examples: https://github.com/ampedandwired/html-webpack-plugin/tree/feature/loaders/examples/html-loader
