### ISSUE TITLE
Output HTML is not compressed by Compression Webpack Plugin

### ISSUE THREAD

**Issue by akrawchyk** [ampedandwired/html-webpack-plugin#142]
When using this with [Compression Webpack Plugin](https://github.com/webpack/compression-webpack-plugin), webpack does not output an `index.html.gz` even though the bundled js files are output as `.gz`:

Relevant Webpack config:

```
var fs = require('fs')
var path = require('path')
var webpack = require('webpack')
var HtmlWebpackPlugin = require('html-webpack-plugin')
var CompressionPlugin = require("compression-webpack-plugin")
var zlib = require('zlib')

// workaround for suporting gzip level 9, see http://is.gd/FP9niA
function gzipMaxCompression(buffer, done) {
  return zlib.gzip(buffer, { level: 9 }, done)
}

module.exports = {
  entry: './src/index.js',
  output: {
    path: path.join(__dirname, 'public'),
    filename: 'bundle.[hash:8].js'
  },
  resolve: {
    extensions: ['', '.js', '.jsx', '.jpg', '.png']
  },
  module: {
    loaders: [
      {
        test: /\.js(x)?$/,
        exclude: /node_modules/,
        loaders: [
          'babel?presets[]=es2015&presets[]=react&plugins[]=transform-runtime&cacheDirectory=true'
        ]
      },
      {
        test: /\.(jpe?g|png|gif|svg)$/,
        loader: 'url?limit=100000&name=[name].[hash:8].[ext]'
      }
    ]
  },
  plugins: [
    new webpack.optimize.OccurenceOrderPlugin(true),
    new webpack.optimize.UglifyJsPlugin({
      comments: false,
      sourceMap: false
    }),
    new webpack.BannerPlugin(
      fs.readFileSync('./banner.txt', 'utf8').replace('@date', new Date()),
      { raw: true }
    ),
    new HtmlWebpackPlugin({
      template: 'src/index.html',
      minify: {
        collapseWhitespace: true,
        removeComments: true,
        removeRedundantAttributes: true,
        removeScriptTypeAttributes: true,
        removeStyleLinkTypeAttributes: true
      }
    }),
    new CompressionPlugin({
      algorithm: gzipMaxCompression,
      regExp: /\.(js|html)$/,
      minRatio: 0
    })
  ]
}
```

Output:

```
> webpack --config webpack.prod.config.js

Hash: 3084f4d22ab56dd105ec
Version: webpack 1.12.4
Time: 3143ms
                    Asset     Size  Chunks             Chunk Names
       bundle.3084f4d2.js   471 kB       0  [emitted]  main
    bundle.3084f4d2.js.gz   213 kB          [emitted]
               index.html  2.55 kB          [emitted]
    + 311 hidden modules
```

**Comment by jantimon** [comment]
Could you please investigate why it does not compress the html?

**Comment by Peekab0o** [comment]
I did not even running compression js - why?

var zlib = require('zlib');
var CompressionPlugin = require("compression-webpack-plugin");

function gzipMaxCompression(buffer, done) {
  return zlib.gzip(buffer, { level: 9 }, done)
}


var webpackDevConfig = {
	entry: [
		'webpack-dev-server/client?http://0.0.0.0:' + DEV_PORT,
		'webpack/hot/only-dev-server',
		'./' + PROJECT_NAME + '/src/scripts/app'
	],
	devtool: "eval",
	debug: true,
	output: {
		path: path.join(__dirname, PROJECT_NAME + '/public'),
		filename: 'build.js',
		publicPath: './'
	},
	resolveLoader: {
		modulesDirectories: ['node_modules']
	},
	plugins: [
		new webpack.HotModuleReplacementPlugin(),
		new webpack.NoErrorsPlugin(),
		new CompressionPlugin({
			algorithm: gzipMaxCompression,
			regExp: /\.(js|html)$/,
			minRatio: 0
		})
	],
	resolve: {
		extensions: ['', '.js', '.cjsx', '.coffee']
	},
	module: {
		loaders: [
			{ test: /\.sass$/, loaders: ['style', 'css', 'sass?indentedSyntax'] },
			{ test: /\.cjsx$/, loaders: ['react-hot', 'coffee', 'cjsx'] },
			{ test: /\.coffee$/, loader: 'coffee' }
		]
	}
};

**Comment by jantimon** [comment]
Could you please add a debugger statement or console.log here?
https://github.com/webpack/compression-webpack-plugin/blob/master/index.js#L27

**Comment by akrawchyk** [comment]
Is this closed on purpose? I'm not able to dig in yet with my project launching soon, but I would be able to help next week.

**Comment by akrawchyk** [comment]
@jantimon I logged out each `file` from `async.forEach(Object.keys(assets), function(file, callback) {` at https://github.com/webpack/compression-webpack-plugin/blob/9a6a85a608e4d4417716d04f3543470194ba8fd2/index.js#L28. The HTML files are not listed. I'm going to look at https://github.com/alexpalombaro/modernizr-webpack-plugin#htmlwebpackplugin to if I can figure out how that plugin captures the HTMLWebpackPlugin's assets.

**Comment by jantimon** [comment]
Closed because of inactivity - thought you wouldn't come back sorry ;)

The reason for this issue is, that this plugin waits for the emit phase and the `compression-webpack-plugin` is compressing before that (during `optimize-assets`).

Unfortunately the compression-webpack-plugin is written by @sokra so I guess it will take very long to get feedback on this.

**Comment by n8downs** [comment]
I'm new to this webpack stuff, but it would seem to me that `html-webpack-plugin` should be doing its work towards the end of the `compile` phase rather than during `emit`. If that were the case, then built html assets would naturally be optimized by `compression-webpack-plugin` during `optimize-assets`. It doesn't seem to me that the reverse (compression happening during `emit`) would be correct.

I went ahead and [forked](https://github.com/opuslabs/html-webpack-plugin) this repo to see if I could get something to work, and I've got compression working on my index.html. I moved the main work for building html into `optimize-chunk-assets`, which seems clunky, but it works for my (simple) example. I'd love feedback on this!

**Comment by jantimon** [comment]
@n8downs unfortunately this would not allow to integrate with the appcache plugin which adds the manifest during emit

**Comment by akrawchyk** [comment]
@jantimon with the impending demise of AppCache (https://jakearchibald.github.io/isserviceworkerready/) maybe we'll get lucky and won't be required to support it. Still a ways to go on browser support though. Just a thought :sunglasses:

**Comment by NekR** [comment]
@jantimon @akrawchyk there is this plugin https://github.com/NekR/offline-plugin which is now used in projects such as https://github.com/mxstbr/react-boilerplate instead of appcache plugin.

`offline-plugin` also adds assets to compilation during `'emit'`, but `html-webpack-plugin` doesn't need to support it as it does for appcache-plugin since `offline-plugin` uses JS runtime to register and load `ServiceWorker`/`AppCache`.

**Comment by jantimon** [comment]
@nekr the appcache plugin is added to the <html> element without any configuration necessary.
Configuration:
https://github.com/ampedandwired/html-webpack-plugin/blob/master/examples/appcache/webpack.config.js#L18

Outcome:
https://github.com/ampedandwired/html-webpack-plugin/blob/master/examples/appcache/dist/index.html#L1

Could this be done with offline-plugin?

**Comment by jantimon** [comment]
@akrawchyk offline is relevant especially for mobile devices and iOS has a good market share but zero support for serviceworker. The html-plugin-webpack project is meant to work as seamlessly as possible with every plugin out there.
We might ask the maintainers of the compression plugin to compress the template by using the "html-webpack-plugin-after-emit" event.

**Comment by NekR** [comment]
@jantimon yes, you just add `new OfflinePlugin()` to `webpack.config.js` and add `require('offline-plugin/runtime').install()` somewhere in your bundle, typically something like `app.js`. Nothing needed to be added to `index.html` or whatever `.html`.

See https://github.com/mxstbr/react-boilerplate/blob/v3.0.0/webpack/webpack.prod.babel.js#L75 (there is configuration for the plugin, but it's not required)
And here install https://github.com/mxstbr/react-boilerplate/blob/v3.0.0/app/app.js#L102

**Comment by jantimon** [comment]
@NekR I guess your understanding of appcache is way better than mine and can help me to understand the runtime part. Does this mean the appcache does only work after the javascript was executed?

**Comment by NekR** [comment]
@jantimon at first time `AppCache` is loaded only after JS is loaded. It creates hidden iframe to the special `.html` page which contains manifest. This is kinda "best practice" for `AppCache`. Next time `AppCache` works as it always works (files are gotten from cache), then to try download new version, JS needs to be loaded. 

There possible are ways to install runtime directly/inline from `index.html` via embedding entry to it. I also thought about exporting runtime as a separate entry, but do not need much use cases for it. After all, no one wants `AppCache` to start working until page is loaded (and I believe it works this way anyway, even if added to `index.html`'s manifest attribute). 

Or your concern is about supporting sites without JavaScript? Then you need old `AppCacheWebpackPlugin`, indeed. `offline-plugin`'s main thing is `ServiceWorker` (which absolutely requires JS), `AppCache` is just a fallback there.

P.S. Of course, there possibly is a way to load `AppCache` with such model even without JS, by putting `iframe` directly to the page:
```
<noscript>
  <iframe src"appcache/manifest.html" style="display: none"></iframe>
</noscript>
```

But not sure if it's needed.

**Comment by TomDeBacker** [comment]
Crossposting for future readers.. I created a plugin that does this, maybe it helps someone:
 https://github.com/TomDeBacker/html-compression-webpack-plugin
