### ISSUE TITLE
[feature/loaders] html-loader strips </body> when minimizing

### ISSUE THREAD

**Issue by blandinw** [ampedandwired/html-webpack-plugin#144]
If you use the html-loader (that minimizes per default), the regexes to inject tags will break as html-loader uses the `removeOptionalTags` option from html-minimizer, which removes `</body>` etc.

One has to be careful and explicitly set `html?removeOptionalTags=false!<my-template>`.
We should emit a warning if the option is not explicitly set to `true`.

**Comment by jantimon** [comment]
Probably the same as #135 and #128.

I also opened an issue for the html-loader: https://github.com/webpack/html-loader/issues/40

**Comment by jantimon** [comment]
Looks like the html-loader might fix this soon: https://github.com/chrisnicola/html-loader/commit/b797acf13765c425836588f4fa4d24ac942db730

**Comment by jantimon** [comment]
Fixed: https://github.com/ampedandwired/html-webpack-plugin/commit/68428b583f359849c798f71e64855613b67ae4e8
