### ISSUE TITLE
browsersync is not reload

### ISSUE THREAD

**Issue by chen844033231** [ampedandwired/html-webpack-plugin#147]
when i use webpack html-webpack-plugin with browsersync.  every time i rebundle. the index.html will rechange. 
```
index.html    2.19 kB          [emitted]
commons.js    23.1 kB       3  [emitted]  commons
```
i use browser sync to watch css file change. but it do not work when css change. beaseof index.html change every time.
it it has a way to make the plug-in run only once? Or other solutions?

thk

**Comment by jantimon** [comment]
FIles which were emitted once stay so this would definitely be possible however right now I have no time to implement it.

**Comment by jantimon** [comment]
Solved on 2.x branch
