### ISSUE TITLE
support write html file when webpack use memory fs system

### ISSUE THREAD

**Issue by luqin** [ampedandwired/html-webpack-plugin#150]

**Comment by jantimon** [comment]
??

**Comment by luqin** [comment]
@jantimon 
I can not get the html file when I use webpack-dev-server and handle backend by nginx.
I want to write the html to nginx server by this plugin.
Can you give i idea what should I do?

**Comment by jantimon** [comment]
How the file is written to the disk/memory is handled by webpack not by the plugin itself.
