### ISSUE TITLE
Can I use conditional comments to import entry script?

### ISSUE THREAD

**Issue by Pliman** [ampedandwired/html-webpack-plugin#155]
I have multiple entry like:

    entry: {
      foo: 'foo.js'
      bar: 'bar.js'
      ie: 'ie.js'
    },
    output: {
      path: path.join(__dirname, '/dist/'),
      filename: '[name]-[hash].min.js'
    }

when I use HtmlWebpackPlugin, It's for certain to import or not import an entry, using chunks.
I hope to generate conditional comments in HTML file, like:

    

Any idea on how to achieve that?

**Comment by jantimon** [comment]
You have to create a custom index file:
https://github.com/ampedandwired/html-webpack-plugin/blob/master/default_index.html#L15

**Comment by Pliman** [comment]
Ops, I missed that part.

work great for me, thanks a lot.

my scripts:

**Comment by jantimon** [comment]
Cool :+1:

**Comment by saalmaan** [comment]
syntax has changes now, change regular expression according to your chunks
``

**Comment by Pliman** [comment]
Thanks for notification.

**Comment by bammoo** [comment]
@saalmaan How to filter those ie chunks from regular injection?

**Comment by jantimon** [comment]
@bammoo take a look at the [html-webpack-exclude-assets-plugin](https://github.com/jamesjieye/html-webpack-exclude-assets-plugin) by @jamesjieye - it allows filtering by regular expressions

**Comment by lastobelus** [comment]
link is broken, even when changing github user.
