### ISSUE TITLE
default template not parsing v2.4

### ISSUE THREAD

**Issue by joemaller** [ampedandwired/html-webpack-plugin#158]
Using v2.4, template files aren't being parsed. I stripped everything down to this:
```js
const webpack = require('webpack');
const HtmlWebpackPlugin = require('html-webpack-plugin')

const config = {
  entry: './source/index.js',
  output: {
    path: 'build',
    filename: 'bundle.js'
  },
  plugins: [
    new HtmlWebpackPlugin({
      template: 'source/default.html'
    })
  ]
};

module.exports = config;
```

Where `source/default.html` is just a copy of the [default template](https://github.com/ampedandwired/html-webpack-plugin/blob/master/default_index.html).

Building this does not parse the template, the output `index.html` file is just a copy of the default template with the `bundle.js` script tag injected at the end.  If `new HtmlWebpackPlugin` is used without a template, the default appears to be parsing correctly. 

Am I missing a step or is this a bug?

**Comment by joemaller** [comment]
I grabbed the wrong file (master branch). The correct [default index template](https://github.com/ampedandwired/html-webpack-plugin/blob/387ca2448ac87e28b166aa7bd9ce72f9f0e10e8f/default_index.html) is a lodash template and renders correctly with the above config.

**Comment by joemaller** [comment]
Just in case someone else gets tripped up by this, the default template link from features/loaders points to the file in master, so it's easy to accidentally slip between branches and end up looking at the wrong file.

**Comment by jantimon** [comment]
@joemaller thx fixed it in https://github.com/ampedandwired/html-webpack-plugin/commit/fd415c047ce8b969db1672fcc4f971912b5c7093
