### ISSUE TITLE
when only modify html template, `compiler.watch()` not re-compile, then manually re-compile, compilation hash not change

### ISSUE THREAD

**Issue by kerryChen95** [ampedandwired/html-webpack-plugin#169]
I only modify my html template, `compiler.watch()` does not re-compile, so I just manually restart build script, but compilation hash not change.
[appcache-webpack-plugin](https://github.com/lettertwo/appcache-webpack-plugin) use compilation hash as the version of manifest file, so when I only modify my html template, manifest file's content does not change, browser still load from cache.

**Comment by jantimon** [comment]
Does the hash option help?
