### ISSUE TITLE
ERROR in HtmlWebpackPlugin: template error ReferenceError: require is not defined

### ISSUE THREAD

**Issue by wandergis** [ampedandwired/html-webpack-plugin#175]
I were use `"html-webpack-plugin": "^1.7.0"`，I want to require image from `img:src` ,so I edit my template as it below:
![image](https://cloud.githubusercontent.com/assets/5799374/12377953/f59f1682-bd69-11e5-9b48-2167604b118e.png)
But it throw an error:
`Error: HtmlWebpackPlugin: template error ReferenceError: require is not defined`
That is really a great problem,I don't know how to auto load image from template‘s img:src with `html-webpack-plugin`,does anyone have  any idea with this problem?

**Comment by jantimon** [comment]
There is no way to do this with 1.7.
You will have to switch to the 2.x beta branch see an example which uses the html-loader to "require" the image: https://github.com/ampedandwired/html-webpack-plugin/tree/feature/loaders/examples/html-loader

**Comment by wandergis** [comment]
@jantimon thanks,I'll try 2.x

**Comment by liuliangsir** [comment]
thx~
