### ISSUE TITLE
The loader is not same with templates, so the title can't work

### ISSUE THREAD

**Issue by wandergis** [ampedandwired/html-webpack-plugin#180]
I have three templates,for example:`header.html`、`index.tpl.html`and`footer.html`, so zhe dist index.html is build from these three.
this is my `index.tpl.html`
```
<%= require('html!../../templates/header.html') %>
<div>this is content</div>
<%= require('html!../../templates/footer.html') %>
```
and i special the loader to underscore:
![image](https://cloud.githubusercontent.com/assets/5799374/12407297/04cf06d0-be91-11e5-87be-447f67521f4c.png)

when i enter `webpack`,i found that the`footer.html`and the`header.html` is load by html-loader,and `index.tpl.html` is load by underscore-template-loader as it below. 

### I didn't special any html-loader with ` /\.html$/`

![image](https://cloud.githubusercontent.com/assets/5799374/12407307/21ce8c24-be91-11e5-9e9c-270642815a86.png)

**Comment by jantimon** [comment]
What do you think means the 'html!' in `html!../../templates/footer.html`?

**Comment by wandergis** [comment]
Oh! Haha That's my fault. I'm so sorry! Thx very much.

**Comment by jantimon** [comment]
:)
