### ISSUE TITLE
Support for base element

### ISSUE THREAD

**Issue by MarkLunney** [ampedandwired/html-webpack-plugin#181]
I'm currently using html-webpack-plugin with react-router on a subdirectory, which requires me to set the base path for deployment, but keep as "/" for development

https://github.com/rackt/history/blob/master/docs/BasenameSupport.md

I have created a custom index template to achieve this by adding this tag, with basePath set in the HtmlwebpackPlugin config:

`<base href="{%=o.htmlWebpackPlugin.options.basePath || '/'%}" />`

Is there a way of doing this without a custom template? If not, perhaps this would be a useful option to add.

**Comment by jantimon** [comment]
I guess this would a perfect fit for: https://github.com/jaketrent/html-webpack-template

**Comment by MarkLunney** [comment]
I agree jantimon, I've posted the issue on their repro instead.
