### ISSUE TITLE
lodash template parsing and html-loader

### ISSUE THREAD

**Issue by joemaller** [ampedandwired/html-webpack-plugin#182]
I know this has been touched on in other issues, but it would be useful if we could run html-loader on the  default lodash-template output. I know something like [underscore-template-loader](https://github.com/emaphp/underscore-template-loader) would work, but it seems silly to tack on another dependency which only duplicates functionality already present in html-webpack-plugin.

A workaround I've been playing with is to use set the custom template to a basic HTML skeleton, then use a lodash/ejs include for the html. Something like this as a default template:

```html
<!doctype html>
<html>
  <head>
    <title><%= htmlWebpackPlugin.options.title %></title>
  </head>
  <body>

    <%= require('html!./content.html') %>

  </body>
</html>
```

...then `content.html` could include dependencies like images or whatever: 

```html
<div>
    <img src="./images/kittens.jpg">
</div>
```
While this seems to be working pretty well, it seems unnecessarily complex.

Adding a more explicit option to the conditional on [line 488](https://github.com/ampedandwired/html-webpack-plugin/blob/d5c4e0845731389e7264b52df8fb8880ec5e651a/index.js#L488)  would be good to have. Something like a  `parseTemplate` boolean in the base config should be able to enable other loaders without affecting existing behavior. 

Curious about your thoughts before trying anything.

**Comment by jantimon** [comment]
@joemaller thx for your post. Combining lodash and html-loader is on my agenda right now.
The html loader uses regular expression to modify the template. This might cause serious issues when combined with template code. Just consider `<%= '<img src="' + x ? '1.png' : '2.png'"> %>`.

Right now I don't understand what you menat with adding a more explicit option as you are in full control:

You can specify a template e.g. 'my-fancy-template.html' and declare a html-loader (or any other loader) in your loader configuration.
you can also specify a loader directly e.g `{template: 'html!my-fancy-tempalte.jade'}`
or you can just use the default template which will use underscore.

**Comment by joemaller** [comment]
@jantimon Sorry for not being more clear. I'd like to see the template parsed first, then that output passed to other loaders. My example above reverses that, fragments go through the html-loader before being pulled into the lodash template. What I'm imagining would have lodash parse the template first, then run the output through other loaders. 

To specifically address the regex problem you posed above, html-loader should never see the template code. It would be parsed and rendered, then handed off. 

Being able to use lodash templates like this should enable more composition of loaders. The template would finish first, then the result would just be a static HTML blob. That rendered blob could then be sent through html-loader, inliners, minifiers, etc.

Adding an option to the default config could be used to override the condition in loader.js:

``` js
    if(self.options.parseTemplate || template.indexOf('!') === -1) {
````
(Not tested at all.) I'm not sure what else would need to happen, but that seems like it should parse the template before handing off the output. I'm sure there's more that I'm not getting, but that's the basic idea.

**Comment by jantimon** [comment]
The idea is good - but it has some challenges:

* A far as I know the child compilation of the html-loader has to be done in the make phase where we don't know the assets/chunks etc
* A loader is run in node so it can't use loaders by it's own unless it returns javascript code. However the html-loader does not support javascript code in the template.

Maybe you could fiddle around with a fork or create your own loader so I get a better idea how you would implement it.

**Comment by joemaller** [comment]
ok. The workaround posted above is fine for now but I'll take a look if I get some time. There is a lot of magic to unravel. 

I'll re-open this if I make some progress.

**Comment by jantimon** [comment]
Okay cool if I can help you with that let me know
