### ISSUE TITLE
Inline/hot doesn't work with 2.X

### ISSUE THREAD

**Issue by arcanis** [ampedandwired/html-webpack-plugin#183]
I'm currently trying to use html-webpack-plugin along with webpack-dev-server, with the inline/hot options enabled. According to what I read on the closed issues, it's not possible with the 1.X releases, but it should with the 2.X. However, I can't figure out how to make it work - would you have some documentation about this?

In my current setup, I'm running the following:

```
$> npm install html-webpack-plugin@2
$> webpack --inline --hot
```

However, when I access the dev server root, the inline script hasn't been injected.

**Comment by jantimon** [comment]
Hi @arcanis we just fixed this in #179 - do you use the latest version?

**Comment by arcanis** [comment]
Yep, I'm using the 2.6.5 release. The source code I get is the following:

```html

<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Webpack App</title>
  <link href="mobile.css" rel="stylesheet"></head>
  <body>
  <script src="mobile.js"></script></body>
</html>
```

**Comment by arcanis** [comment]
And here is my webpack configuration:

```js
/*global module, require, __dirname*/

var ExtractTextPlugin = require( 'extract-text-webpack-plugin' );
var HtmlWebpackPlugin = require( 'html-webpack-plugin' );

module.exports = {

    resolveLoader : {
        root : __dirname + '/node_modules/'
    },

    resolve : {
        extensions : [ '', '.js' ],
        root : __dirname,
        alias : { 'mobile': __dirname + '/sources/mobile/' }
    },

    entry : {
        'mobile' : 'mobile/index'
    },

    output : {
        path : __dirname + '/builds/',
        filename : '[name].js',
        chunkFilename : '[id].js'
    },

    module : {
        loaders : [ {
            test : /\.less$/,
            loader : ExtractTextPlugin.extract( 'style-loader', 'css-loader!less-loader' )
        } ]
    },

    plugins : [
        new ExtractTextPlugin( '[name].css' ),
        new HtmlWebpackPlugin( )
    ]

};
```

**Comment by jantimon** [comment]
This is not a valid hot loader config is it?

**Comment by arcanis** [comment]
I think it is - first time I write one, so I'll check. However, the config wasn't the issue - I was :(

For some reason I assumed the inline script would be injected ... well, inline, via a `<script/>` tag. However, since the way webpack-dev-server works is by adding dependencies to the `entry` configuration, these scripts are directely embedded in the entry files (in my case, `mobile.js`). Since I was monitoring the DOM tab and not the console (or the network tab), I missed it.

So actually, using 2.6.5, it works fine. Thanks for helping me!

**Comment by jantimon** [comment]
Happens to all of us :) glad it works
