### ISSUE TITLE
some question of working with extract-text-webpack-plugin 

### ISSUE THREAD

**Issue by honger05** [ampedandwired/html-webpack-plugin#184]
I'm sorry to bother you.

my configration `entry` segment 

````js
entry: {
  index: '....',
  detail: '....'
}
````

use extract-text-webpack-plugin as the following will generator each entry chunks

 like `index.css` in `index.html` and `detail.css` in `detail.html`

````
new ExtractTextPlugin('./[name].css'),

new HtmlWebpackPlugin({
    filename: 'index.html',
    template: 'src/tmpl/index.html',
    inject: 'body',
    chunks: [ 'index']
  })

new HtmlWebpackPlugin({
    filename: 'detail.html',
    template: 'src/tmpl/detail.html',
    inject: 'body',
    chunks: [ 'detail']
  })
````

It's good.

but when I specify common files

````js
entry: {
  index: '....',
  detail: '....',
  common: ['jquery', 'underscore']
}
````

extract-text-webpack-plugin will generator a `common.css`. not `index.css` and `detail.css`.

and html-webpack-plugin will also inject the `index.css` and `detail.css`, not the `common.css`.

but there is no such files. so it inject nothing.

anyway, the javascript files injected normally.

How could I make it inject the `common.css`, otherwise I must do it manually.

**Comment by jantimon** [comment]
Hmm sorry didn't have those issues - but pull requests to fix this would be welcome :)
The CSS gathering is done here:
https://github.com/ampedandwired/html-webpack-plugin/blob/9e8259ae269b78b3c5498bb3320f250ca5d9a476/index.js#L386
