### ISSUE TITLE
templateContent version 2.x

### ISSUE THREAD

**Issue by beckend** [ampedandwired/html-webpack-plugin#189]
It has been changed as of version 2.x.
README Async version:

`templateContent: function(templateParams, compilation, callback)`

README Sync version:
`templateContent: function(templateParams, compilation)`

[index.js Line 197](https://github.com/ampedandwired/html-webpack-plugin/blob/master/index.js#L197)
Source code states:
`HtmlWebpackPlugin.prototype.executeTemplate = function (templateFunction, chunks, assets, compilation)`

**Comment by jantimon** [comment]
Is this a question?

**Comment by beckend** [comment]
I guess not, I tried to use the async version and got a `callback is not a function` error.

**Comment by jantimon** [comment]
This was a breaking change in 2.x - please take a look at the migration guide: https://github.com/ampedandwired/html-webpack-plugin/blob/master/migration.md#isomorph-apps
