### ISSUE TITLE
Template not injected into index

### ISSUE THREAD

**Issue by mikaa123** [ampedandwired/html-webpack-plugin#190]
Hey there,

First, thanks for the project, it's a really useful one!

I'm having trouble using the `template` option. Here is my webpack.config.js

~~~
  plugins: [
    new HtmlWebpackPlugin({
      template: 'template.html'
    })
  ]
~~~

Whenever I run `webpack`, my build contains `index.html` and `template.html`. The content of `index.html` is:

~~~
/template.html<script src="/vendor.bundle.js"></script><script src="/bundle.js"></script>
~~~

I'm using version 2.7.2. Any idea?

Thanks bunch

**Comment by mastertinner** [comment]
@mikaa123, do you have any other loaders defined for `test: /\.html$/`? I'm having the same problems and am not sure how to solve it... But the problem seems to be another loader I have defined for `HTML` files.

**Comment by mikaa123** [comment]
@mastertinner nice man, that was the problem. I had the exact same loader as you. Removing it does the trick. I guess another solution would be to exclude index.html from that test.

**Comment by mastertinner** [comment]
@mikaa123, `exclude` is a good idea. I didn't even know that existed. Thanks!

**Comment by mikaa123** [comment]
@mastertinner you're welcome! Closing this issue now.

**Comment by wonyun** [comment]
@jantimon, 
I have the same problems and know how to resolve it，though I don't understand why.
can you tell us why this plugin does't work fine in combination with the use file-loader plugin?thanks very much!
