### ISSUE TITLE
Can you provide a full working example using underscore/ejs templating ?

### ISSUE THREAD

**Issue by LiorSaadon** [ampedandwired/html-webpack-plugin#193]
Can you provide a full working example of using underscore/ejs templating with webpack and html-webpack-plugin ?

- what should we install as a dependency in order for the new templating to work the same way as the old version (1.6.2) worked
- i went over the migration doc you added and still can't make it work.

**Comment by jantimon** [comment]
Are you using the html-loader to gether with a template.**html** file?
Because then the html-loader would kick in instead of the lodash loader.

There are several examples in the examples folder:

https://github.com/ampedandwired/html-webpack-plugin/tree/master/examples/custom-template

**Comment by LiorSaadon** [comment]
i tried to run the "custom-template" example and it failed on build, i guess you might have a dependency installed globally that resolve this issue, can you please check it?

Html Webpack Plugin:
< pre>
  Error: Child compilation failed:
  Module parse failed: C:\html-webpack-plugin-master\html  -webpack-plugin-master\lib\loader.js!C:\html-webpack-pl  ugin-master\html-webpack-plugin-master\examples\custom-template\template.html   Unexpected token (1:0)
  You may need an appropriate loader to handle this file type.
  | <!doctype html>
  | < html lang="en">< head>< link href="styles.css" rel="stylesheet">< /head>
  | < head>:
  SyntaxError: Unexpected token (1:0)
  
  - compiler.js:78 
    C:/html-webpack-plugin-master/html-webpack-plugin-mas    ter/lib/compiler.js:78:16
  
  - Compiler.js:243 Compiler.<anonymous>
    [npm]/[webpack]/lib/Compiler.js:243:10

**Comment by jantimon** [comment]
All examples are built on [windows](https://ci.appveyor.com/project/jantimon/html-webpack-plugin) and [unix](https://travis-ci.org/ampedandwired/html-webpack-plugin) so it should just work.
AppVeyor and Travis shouldn't have any dependencies installed beside the package dependencies and package dependencies.

How did you run it?

**Comment by LiorSaadon** [comment]
running on windows
1. "npm install" for the whole project
2. cd C:\html-webpack-plugin-master\html-webpack-plugin-master\examples\custom-template
3. run "webpack"
4. failed on this line in the template file: < %= require('html!./partial.html') %>

**Comment by jantimon** [comment]
Could you please just run `npm install` and then `npm test` and check if the build works with your node version, npm version, webpack version and install packages?

**Comment by LiorSaadon** [comment]
webpack 1.12.12
npm: 3.5.3
node: v4.2.4

test are failing:

Failures:

  1) HtmlWebpackPlugin Examples custom-template example
   Message:
6) HtmlWebpackPlugin Examples jade-loader example
 Message:
   Expected false to be true.

**Comment by jantimon** [comment]
Hmm this really similar to the automated test run:
https://ci.appveyor.com/project/jantimon/html-webpack-plugin/build/job/7f0c05i87wiyhtto

```
node --version
v4.2.4
npm --version
2.14.12
npm test
```

This is probably because of the peer dependencies which are no longer installed for npm 3.
I guess you have to install them by hand.

**Comment by LiorSaadon** [comment]
Thanks, i'll try that...
if i'll come up with something i'll update

**Comment by jantimon** [comment]
Cool :+1:

**Comment by jantimon** [comment]
Can I close this?

**Comment by LiorSaadon** [comment]
yeah close it, i still couldn't find the reason why its not working but i guess its a missing dependency
