### ISSUE TITLE
App manifest support

### ISSUE THREAD

**Issue by bottleofwater** [ampedandwired/html-webpack-plugin#200]
Hi,

I'd like to set a [Web App manifest](https://github.com/w3c/manifest) on my project. What's the best way to do it with this plugin?

The only thing required is to have this meta tag:

```html
<link rel="manifest" href="manifest.webmanifest">
```

If html-webpack-plugin doesn't yet support this natively, could it be possible to add it? For example by giving the ability to specify the module name as an option when instanciating the plugin.

Thanks,

**Comment by jantimon** [comment]
Create a custom template - it's very very simple. See the default template:

https://github.com/ampedandwired/html-webpack-plugin/blob/master/default_index.ejs

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title><%= htmlWebpackPlugin.options.title %></title>
  </head>
  <body>
  </body>
</html>
```

**Comment by tusharmath** [comment]
@jantimon but what would be the URI for the manifest?

**Comment by jantimon** [comment]
You could use the file loader like <%= require("manifest") %>

**Comment by jantimon** [comment]
I believe the favicons-webpack-plugin does this for you

**Comment by tusharmath** [comment]
@jantimon — I get this error 
```
    ..."stylesheet" href={{require('./manifest'
    -----------------------^
    Expecting 'ID', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', got 'INVALID'

```

**Comment by jantimon** [comment]
Looks like handlebars doesn't support dynamic requires.
