### ISSUE TITLE
Template Issue

### ISSUE THREAD

**Issue by wpitallo** [ampedandwired/html-webpack-plugin#202]
Hi, I have been trying to use the latest version with a custom template but the template does not seem to work. When I run the devserver all i see is the default template: /index-template-dd9595.html

**Comment by jantimon** [comment]
Could you please post your loader and plugin configuration?

**Comment by wpitallo** [comment]
var path = require('path'),
    webpack = require("webpack"),
    libPath = path.join(__dirname, '/modules/authentication/init'),
    wwwPath = path.join(__dirname, 'www'),
    pkg = require('./package.json'),
    HtmlWebpackPlugin = require('html-webpack-plugin');


var config = {
    entry: path.join(libPath, 'index.js'),
    output: {
        path: path.join(wwwPath),
        filename: 'bundle-[hash:6].js'
    },
    module: {
        loaders: [{
            test: /\.html$/,
            loader: 'file?name=templates/[name]-[hash:6].html'
        }, {
            test: /\.(png|jpg)$/,
            loader: 'file?name=img/[name].[ext]' // inline base64 URLs for <=10kb images, direct URLs for the rest
        }, {
            test: /\.css$/,
            loader: "style!css"
        }, {
            test: /\.scss$/,
            loader: "style!css!autoprefixer!sass"
        }, {
            test: /\.js$/,
            exclude: /(node_modules)/,
            loader: "ng-annotate?add=true!babel"
        }, {
            test: [/fontawesome-webfont\.svg/, /fontawesome-webfont\.eot/, /fontawesome-webfont\.ttf/, /fontawesome-webfont\.woff/, /fontawesome-webfont\.woff2/],
            loader: 'file?name=fonts/[name].[ext]'
        }]
    },
    plugins: [
        // HtmlWebpackPlugin: Simplifies creation of HTML files to serve your webpack bundles : https://www.npmjs.com/package/html-webpack-plugin
        new HtmlWebpackPlugin({
            filename: 'index.html',
            pkg: pkg,
            template: path.join(libPath, 'index.html')
        }),

        new webpack.optimize.DedupePlugin()
    ]
};

module.exports = config;

**Comment by wpitallo** [comment]
When I changed back to version 1 it worked perfectly

**Comment by jantimon** [comment]
Okay - version uses webpack for the template rendering - and although it uses a child compiler the loader of the main compilation are used. This is great because it allows to use any webpack supported template language.
Unfortunately your template is called `index.html` and you told webpack to load html pages with the file loader:
```
{
  test: /.html$/,
  loader: 'file?name=templates/[name]-[hash:6].html'
}
```

**Comment by wpitallo** [comment]
Ok great, that makes sense, why does it work with version 1 though or is it being ignored?

**Comment by jantimon** [comment]
The big change from 1 to 2 was adding the loader feature and use webpack to render the file - before it was rendered by nodejs

**Comment by wpitallo** [comment]
OK cool thanks, I tried again without the loader and it looks like it worked for the template but now I get the following error when it's trying to load a file that the file loader was previously loading:

ERROR in ./modules/authentication/views/test/test-account-links.html
Module parse failed: C:\CodeScienceGIT\CodeScience.Client.Base\modules\authentication\views\test\test-account-links.html Unexpected token (2:0)
You may need an appropriate loader to handle this file type.

**Comment by jantimon** [comment]
As I said - rename the file or exclude it.. dont remove the loader ;)

**Comment by pavelsl** [comment]
I use it inside template to connect sub templates, i don't use it in webpack.config file. 

```
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8"/>
    <title><%= htmlWebpackPlugin.options.title %></title>

</head>
<body>
<%= require('html!./inc/header.html') %>
<h1>Some content goes here!!!</h1>
<!-- some comments to remove -->
<%= require('html!./inc/footer.html') %>
<%= require('html!./inc/analytics/google.html') %>
</body>
</html>
```
