### ISSUE TITLE
double head on optimize-minimize

### ISSUE THREAD

**Issue by lalop** [ampedandwired/html-webpack-plugin#203]
I have a double tag head when I build with option `optimize-minimize` and I give custom template

**Comment by jantimon** [comment]
This is because of the output of the html-plugin.
It returns a html without a closing head tag.

Don't use the html-loader for the template or disable the unsafe optimizations similar to the following merge request:
https://github.com/webpack/html-loader/pull/43

**Comment by lalop** [comment]
Oh sad news.
I've disabled the html-loader
