### ISSUE TITLE
cache parameter has no effect

### ISSUE THREAD

**Issue by chen844033231** [ampedandwired/html-webpack-plugin#204]
i use examples/default and examples/appcache project, when I don't have any modification to save example.js, webpack should not emit index.html. but the index.html emitted.

![image](https://cloud.githubusercontent.com/assets/5764308/12776594/38fcdac4-ca92-11e5-8757-ad69cb5eb779.png)

webpack setting
```js
plugins: [
    new HtmlWebpackPlugin({
      template: 'template.js',
      cache: true
    }),
    new ExtractTextPlugin('styles.css')
  ]
```

If I have a wrong setting, or need other conditions? 

thx.

**Comment by jantimon** [comment]
@chen844033231 oh you are right there is a bug in the caching right now.
Will be fixed in 2.7.3.
Unfortunately there are no tests on caching.. 
Maybe you (or someone else) has a cool idea how we could add tests.
