### ISSUE TITLE
Universal (//domain.com/asset.css) publicPath and ExtractTextPlugin: css is missing

### ISSUE THREAD

**Issue by smolyakoff** [ampedandwired/html-webpack-plugin#205]
In my webpack configuration I have a public path configured in such a way that it is not dependent on HTTP/HTTPS server

```js
{
   output: {
      publicPath: '//localhost:8080/'
   }
}
```

The output chunk names look like this:
```js
[ '//localhost:8080/vendor-3a8b12e879b7905f4358.js',
  '//localhost:8080/vendor-3a8b12e879b7905f4358.js.map' ]
[ '//localhost:8080/app-3a8b12e879b7905f4358.js',
  '//localhost:8080/styles.css',
  '//localhost:8080/app-3a8b12e879b7905f4358.js.map',
  '//localhost:8080/styles.css.map' ]
```

CSS is not inserted into the output HTML, probably because *path.extname()* is used to get an .css extension

Can we add a special check to cover this case?

**Comment by jantimon** [comment]
In webpack you should always specify `http` or `https` in your public path during development as it will break background images in css files if you use source maps.
But feel free to create pull request for this issue :+1:

**Comment by smolyakoff** [comment]
@jantimon Thanks for you notice, haven't faced background images yet. This could still be useful when building a package for deployment, urls should work in this case. I've created a pull request, could you take a look?
