### ISSUE TITLE
Update changelog

### ISSUE THREAD

**Issue by austinpray** [ampedandwired/html-webpack-plugin#206]
Looks like the changelog is out of date.

I'm going to go through and look at the commits and contribute a basic summary. However, it would be helpful if someone in the loop could fill in the high-points on breaking changes.

**Comment by jantimon** [comment]
:+1:

**Comment by austinpray** [comment]
Just realized most of the info is in here: https://github.com/ampedandwired/html-webpack-plugin/blob/master/migration.md 

I think I have everything I need

**Comment by oliviertassinari** [comment]
More generally speaking, could we document every release?
