### ISSUE TITLE
Favicon public path?

### ISSUE THREAD

**Issue by austinpray** [ampedandwired/html-webpack-plugin#208]
My favicon always outputs as such:

```html
<link rel="shortcut icon" href="favicon.ico">
```

Which is problematic because my public path is `/` and it really should be `/favicon.ico`. The problem arises when you load a view such as `sub/sub/1` The browser looks for the favicon in `sub/sub/favicon.ico`.

**Comment by pawelniewie** [comment]
Just browsing issues to report the same problem. Thanks for doing that already.

**Comment by austinpray** [comment]
Here is a copy of my webpack config for better clarity: https://github.com/UTD-CRSS/app.exploreapollo.org/blob/f4ce9f20e6c49eb6ed060ee3a7043d11b78ebf67/webpack.config.js

**Comment by jeremejevs** [comment]
How is #215 not merged yet? Still having to stick with 1.x, which was handling it [correctly](https://github.com/ampedandwired/html-webpack-plugin/blob/v1.7.0/index.js#L219).
