### ISSUE TITLE
Jade partials with references to parent (template)

### ISSUE THREAD

**Issue by MarianArlt** [ampedandwired/html-webpack-plugin#209]
With one of the last updates I have issues when I make a reference to a parents jade template file from inside an included jade partial. To better illustrate this my case is something like the following:
    
**Index.jade** _(The template called with HtmlWebpackPlugin)_

    body
        - sections = ['one', 'two', 'three', 'four', …]
        for v, i in sections
            section(id= v)
                if i == 0
                    include ./partials/sectionOne
                if i == 1
                    include ./partials/sectionTwo

**sectionOne.jade** _(The partial)_

    h1= 'This is section number ' + v + '!'
    p= 'Section ' + v ' is definitely and totally the best section of all sections.'
    button= v

Now `v` and `i` from the loop should get passed down to the include where it should be reusable. Instead they will both be `undefined`. I also tried `#{v}` rather than just `v` with no success. _This worked fine before._
If I build another loop inside the include based on the attributes from the parents one, I even get a breaking error in the CLI because, well, undefined has no length. I'm watching all .jade files with `module: { loaders : [ { test: /\.jade$/, ... } ] }`. I tried to set the loader in the HtmlWebpackPlugin section with `template: 'jade!./path/to/index.jade'` which would throw an error about the includes not being exported because of a missing loader type.

I also tried this with the files from the [jade-loader example](https://github.com/ampedandwired/html-webpack-plugin/tree/master/examples/jade-loader) with the same effect.

Do I have to deal differently with this since 2.x? Shouldn't have to, should I?

**Comment by jantimon** [comment]
See the example which uses a jade partial:

https://github.com/ampedandwired/html-webpack-plugin/blob/master/examples/jade-loader/time.jade

Does the jade-loader threat all variables as globals?

**Comment by MarianArlt** [comment]
Sorry I don't know if I get the question right. What do you mean with 

> Are all variables globals for the jade-loader?

 What I can tell you is I've been playing around with the jade example and this is what I found:

- Variable `time` gets passed down to the include if it is prepended `locals.time` in the parent. It can then be called with `y= time` or `y #{time}` within the include.
- Variable `time` **won't** get passed down to the include if it is **not** prepended `locals.time`. It can then neither be called with `y= time` nor `y #{time}` within the include.

Variable `time` was getting passed down just fine to the include no matter the prefix like a month ago or even less. So for the example files if you change `- locals.time = new Date();` to only `- time = new Date();` in the template and then change `p #{time.toISOString()}` to only `p= time` or to only `p #{time}` and comment out all the frontend to make this not disappear immediately `time`will not get displayed at all. _This behavior is new!_ So something must have happened somewhere.

**Comment by jantimon** [comment]
This plugin does nothing special about jade - it only allows to use the jade-loader.
Please ask the jade-loader team :)
If something can be fixed for the plugin feel free to open a pull request.

**Comment by MarianArlt** [comment]
Will do! Gonna report back if necessary. Kudos.

**Comment by MarianArlt** [comment]
Too bad. Jade-loader isn't maintained very well. Guess this will take quite some time to get resolved. Thank you for the moment.

**Comment by MarianArlt** [comment]
Actually I think this could be related to [this question on stackoverflow](http://stackoverflow.com/questions/15035624/jade-templating-variable-scope-in-includes) where compiling the includes itself apparently won't recognize the variable scope. Before 2.x with `templateContent` this somehow worked. I guess since now everything is done by the loader all the includes get compiled before getting called by the main jade file thus not inheriting the variable scope. Funny enough with `locals.variable` this ain't no problem.
I really wouldn't care much to make all my variables `locals.x` but this just won't do for loops. On the other hand if I exclude the partials from the loader then webpack will trace them and complain about the file type.
I rolled back version by version, first html plugin, then jade loader, then jade, then webpack. Do you still think this would be an issue about how jade-loader works? Because I'm telling you, this worked fine before 2.x using `templateContent`.

**Comment by jantimon** [comment]
`templateContent` is node (without jade loader)
2.x uses the webpack way (with jade loader)

**Comment by MarianArlt** [comment]
I did understand that bit. I guess what you're trying to say is that this is the responsibility of the respective engine, since 2.x in this case jade-loader. I totally agree, thank you for your time and close this, since it's not related. Kudos!
