### ISSUE TITLE
How to import HTML template snippets

### ISSUE THREAD

**Issue by mderrick** [ampedandwired/html-webpack-plugin#211]
Thanks for a great plugin, its working exceptionally well except for what may be a very specific use case for myself.

I have a need to actually import HTML snippets into my custom template but I cannot seem to see an obvious way I could do this.

My only solution was to do a find and replace on the template using:

```js
compilation.plugin('html-webpack-plugin-before-html-processing', function (htmlPluginData, callback) {
    var html = fs.readFileSync(path.join(__dirname, '../src/head.html'))
    htmlPluginData.html = htmlPluginData.html.replace('{{ PLACEHOLDER }}', html);
});
```

But this seems a little overkill and I feel like there is probably something to handle this already that I am unaware of. Another issue is that my solution is not actually completely effective as any `<%= %>` lodash variables inside `head.html` won't get parsed.

If this is indeed my only solution, is there an alternative event I can use to do this replace before the template is parsed by lodash?

Thank you!

**Comment by mderrick** [comment]
Further to my question above I ended up running the html back through lodash `_.template()` in order to solve that issue but if you could verify that this indeed is the right way to do this that would be really helpful.

```js
var html = _.template(fs.readFileSync(path.join(__dirname, '../src/head.html')))({
    webpackConfig: compiler.options,
    htmlWebpackPlugin: htmlPluginData.plugin
});
htmlPluginData.html = htmlPluginData.html.replace('{{ PLACEHOLDER }}', html);
```

Thanks again.

**Comment by jantimon** [comment]
Would this example help your?
https://github.com/ampedandwired/html-webpack-plugin/tree/master/examples/custom-template

**Comment by mderrick** [comment]
:laughing: How did I not see this.....

I knew there had to be something! Thank you!

**Comment by jjalonso** [comment]
Im doing the same that in the example but my img tag are in the MAIN template and NOT in a partial template and the template is working but is not copying the img src to the bundle folder.

How i can make the plugin use html-loader also in the main template?
Thanks and good work!

**Comment by jjalonso** [comment]
I think I got it doing:

`new HtmlWebpackPlugin({template: 'underscore-template-loader!./mytemplate.html' ....`

**Comment by jantimon** [comment]
:+1:

**Comment by jjalonso** [comment]
That should be in the doc, because the doc assume that only the partials contains imgs etc to require.

**Comment by jantimon** [comment]
Well this isnt part of the plugin.. you have to understand how loaders work in order to use their features.. the underscore template loader has some big issues and won't be supported by webpack2 afaik
