### ISSUE TITLE
Webpack 2.0.7-beta failing compile

### ISSUE THREAD

**Issue by foglerek** [ampedandwired/html-webpack-plugin#213]
Hi,

I'm having issues compiling with a very basic setup using Webpack 2. Getting two sets of errors ([...] = redacted):
```
ERROR in   Error: Child compilation failed:
  Module parse failed: [...]/node_modules/html-webpack-plugin/lib/loader.js!  [...]/node_modules/html-webpack-plugin/default_index.ejs Unexpected token   (1:0)
  You may need an appropriate loader to handle this file type.
  | <!DOCTYPE html>
  | <html>
  |   <head>:
  SyntaxError: Unexpected token (1:0)

  - compiler.js:78
    [...]/[html-webpack-plugin]/lib/compiler.js:78:16

  - Compiler.js:243 Compiler.<anonymous>
    [...]/[webpack]/lib/Compiler.js:243:10

  - Compiler.js:432
    [...]/[webpack]/lib/Compiler.js:432:12

...
```
and 
```
Child html-webpack-plugin for "index.html":

    ERROR in ./~/html-webpack-plugin/lib/loader.js!./~/html-webpack-plugin/default_index.ejs
    Module parse failed: [...]/node_modules/html-webpack-plugin/lib/loader.js![...]/node_modules/html-webpack-plugin/default_index.ejs Unexpected token (1:0)
    You may need an appropriate loader to handle this file type.
    | <!DOCTYPE html>
    | <html>
    |   <head>
```

The config is 
```
    context: __dirname + '/app',
    entry: { 'app' : './entry' },
    output: {
        path: __dirname + '/public/assets/[hash]',
        publicPath: "/assets/[hash]",
        filename: '[name].js'
    },
...
    devServer: {
        contentBase: "./public",
    }
...
    plugins: [
        new HtmlWebpackPlugin()
    ],
```

Any ideas?

**Comment by jantimon** [comment]
The reason is that the template loader believes that there is already another loader configured.

Could you please add `console.log(this.loaders);` here?

https://github.com/ampedandwired/html-webpack-plugin/blob/master/lib/loader.js#L11

**Comment by foglerek** [comment]
This is the console.log, from L11:

```
[ { request: [Getter/Setter],
    path: '[...]/node_modules/html-webpack-plugin/lib/loader.js',
    query: '',
    normal: [Function],
    pitch: undefined,
    raw: undefined,
    data: null,
    pitchExecuted: true,
    normalExecuted: true } ]
```

**Comment by jantimon** [comment]
Looks like an webpack 2 internal api change then.

**Comment by jantimon** [comment]
Right now I have no time but I'll try build a check which works for webpack 1 and 2 next week.

**Comment by jantimon** [comment]
Feel free to open a pull request if you like

**Comment by foglerek** [comment]
Will have a stab at it :)

**Comment by foglerek** [comment]
So I managed to fix this issue with relative ease, by adding the following to `loader.js`, L12:
```
    // Loader API changed from `loader.module` to `loader.normal` in Webpack 2.
    return (loader.module || loader.normal) !== module.exports;
```

However, there are now issue related to `with()` being used within the lodash/underscore template.
```
    ERROR in ./~/html-webpack-plugin/lib/loader.js!./~/html-webpack-plugin/default_index.ejs
    Module parse failed: [...]/node_modules/html-webpack-plugin/lib/loader.js![...]/node_modules/html-webpack-plugin/default_index.ejs 'with' in strict mode (4:0)
    You may need an appropriate loader to handle this file type.
    | obj || (obj = {});
    | var __t, __p = '';
    | with (obj) {
    | __p += '<!DOCTYPE html>\n<html>\n  <head>\n    <meta charset="UTF-8">\n    <title>' +
    | ((__t = ( htmlWebpackPlugin.options.title )) == null ? '' : __t) +
```

I suspect this might be unrelated however. I use babel for the webpack config file too which automatically inserts use strict, no idea if that is the culprit.

Fixing it is non-trivial however, as it involves changing L24 in `loader.js` to
```
var options = _.defaults(loaderUtils.parseQuery(this.query), { variable: 'data' });
```
Which, while removing the `with(data)` statement, is also breaking as there is no straightforward way to make all templateParams available within the template (without causing breaking changes to old templates).

If you can think of anything let me know.

I'll create a PR for the first fix, however.

**Comment by foglerek** [comment]
Update: the `with()` issue does not seem to be related to the webpack config being parsed by babel. I removed it and it still persists.

**Comment by RahavLussato** [comment]
:+1:  happens to me too

**Comment by RahavLussato** [comment]
i found solution for that, you need to use foglerek suggestion : 
var options = _.defaults(loaderUtils.parseQuery(this.query), { variable: 'data' });
and then inside the template use ' data.htmlWebpackPlugin '
for example : 
<title><%= data.htmlWebpackPlugin.options.title %></title>
instead of :
<title><%= htmlWebpackPlugin.options.title %></title>

**Comment by RahavLussato** [comment]
#216

**Comment by foglerek** [comment]
Yeah, that works but will break all custom templates using the built-in
loader, right?

**Comment by RahavLussato** [comment]
yes because you need to use now "data" variable to get the options

**Comment by foglerek** [comment]
Exactly say that's not a viable solution. I'm afraid this requires a bigger
rewrite, perhaps moving the template creation to the method that has access
to the template parameters.

**Comment by foglerek** [comment]
Hey, I submitted a new PR that fixes this and maintains backwards compatibility with Webpack 1. Please have a look at https://github.com/ampedandwired/html-webpack-plugin/pull/219 .

**Comment by evenfrost** [comment]
Any info when it's merged? Having this issue as well with 2.0.7-beta.

**Comment by jantimon** [comment]
@evenfrost webpack2 broke some stuff..
Right now I am not using webpack2 and don't have the time but I would love to merge stuff into the webpack2 branch to solve those issues:
https://github.com/ampedandwired/html-webpack-plugin/pull/225

**Comment by PainKKKiller** [comment]
Have webpack 2.2.1 and this issue still exists, solution of RahavLussato not working
