### ISSUE TITLE
There is no htmlWebpackPlugin.files.css?

### ISSUE THREAD

**Issue by DelvarWorld** [ampedandwired/html-webpack-plugin#22]
Still investigating, but if I use this:

https://github.com/ampedandwired/html-webpack-plugin/blob/master/default_index.html#L6

I get this error:

    for (var css in o.htmlWebpackPlugin.files.css) { _s
                                                                        ^
    TypeError: Cannot read property 'css' of undefined

**Comment by oliviertassinari** [comment]
The new template isn't available via npm.
Use this line in your package.json.

    "html-webpack-plugin": "git+https://github.com/ampedandwired/html-webpack-plugin.git#COMMIT,

**Comment by ampedandwired** [comment]
New version has been released, please give it a go. Sorry for the confusion.
