### ISSUE TITLE
Special characters not displaying correctly when using html-webpack-plugin 

### ISSUE THREAD

**Issue by tnrich** [ampedandwired/html-webpack-plugin#220]
Hey there,

I'm running into an odd issue where, in production mode (NODE_ENV = 'production'), everything seems to work fine, but when not in production, special characters don't display correctly. 

This change has only happened after including the html-webpack-plugin on my site. I reverted just the html-webpack-plugin change, and things went back to normal. 

I've attached images showing the diffs between the non-working version and the version without html-webpack-plugin:

![image](https://cloud.githubusercontent.com/assets/2730609/13023682/073bfcda-d1a0-11e5-8ad9-c71a39216b8d.png)

![image](https://cloud.githubusercontent.com/assets/2730609/13023687/1000eede-d1a0-11e5-82aa-ab9daa0a63e4.png)

The test character I was looking at was an Å being turned into an Ã.

If you have any ideas as to what might be going on, or if you need more info from me, please let me know.

Thanks!
Thomas

**Comment by jantimon** [comment]
Sorry I have really no idea why this happens :/

**Comment by tnrich** [comment]
It is a super bizarre one... Did I explain the issue well enough? Maybe with time someone else will run into the same problem and we'll find the solution. It has to be something with the fonts not fully loading...

**Comment by jantimon** [comment]
There was already a similar issue some month ago.

**Comment by tnrich** [comment]
Hey @jantimon , can you link to that issue? I'm thinking of just removing html-webpack-plugin but would rather figure out a solution to the issue.

**Comment by jantimon** [comment]
I am sorry we didn't find any starting point to debug - maybe you can

**Comment by jantimon** [comment]
Looks like this will stay a ghost bug which no one wants to investigate.
Closing this for now. If someone has more information how this happens please let me know.
