### ISSUE TITLE
Template variables are not replaced

### ISSUE THREAD

**Issue by jpetitcolas** [ampedandwired/html-webpack-plugin#223]
I got an issue with `2.7.2` version. I am trying to use some templated variables in my template, such as:

```
<title>[<%= htmlWebpackPlugin.options.environment %>] FooBar Project</title>
```

Yet, it doesn't seem to work, even with the related code:

``` js
new HtmlWebpackPlugin({
    filename: '/app/index.html',
    template: __dirname + '/../app/src/index.html',
    hash: true,
    environment: 'dev'
})
```
Am I missing something? :)

**Comment by jantimon** [comment]
If you use a html file and use an html loader the underscore template won't be executed.

**Comment by simshanith** [comment]
@jantimon could he use the same name if chained with the `underscore-template-loader`?

E.g.

```js
new HtmlWebpackPlugin({
    filename: '/app/index.html',
    template: 'undescore-template!'+__dirname + '/../app/src/index.html',
    hash: true,
    environment: 'dev'
})
```

**Comment by jantimon** [comment]
yes this would also work

**Comment by jpetitcolas** [comment]
Indeed, I was using a HTML loader. I solved my issue my excluding my template file from the loader:

``` js
{ test: /\.html$/, loader: 'html', include: [sourceDir, commonDir], exclude: /index\.html$/ },
```

Thanks for your help! :)

**Comment by szymexpawlowski** [comment]
@simshanith thanks for help however could you correct the typo in "undescore-template"?

**Comment by simshanith** [comment]
@szymexpawlowski thus amended

**Comment by nadysaptra** [comment]
i was using raw loader, and just exclude the file i want fix my issue.

`                {
                    test: /\.html$/,
                    use: 'raw-loader',
                    exclude: [helpers.root('src/index.html'), helpers.root('src/map.html')]
                },
`

and htmlWebpackPlugin 

`new HtmlWebpackPlugin({
                template: 'src/index.html',
                title: METADATA.title,
                chunksSortMode: 'dependency',
                metadata: METADATA,
                inject: 'head',
                CHAT: process.env.CHAT
            }),

            new HtmlWebpackPlugin({
                filename: 'map.html',
                template: 'src/map.html',
                title: METADATA.title,
                inject: true,
                chunks: [],
                BASE_URL_API: process.env.BASE_URL_API
            }),
`
