### ISSUE TITLE
ChunksSortMode not working for multiple entry

### ISSUE THREAD

**Issue by pavankumarkatakam** [ampedandwired/html-webpack-plugin#224]
Hi , i have an webpack app with multiple entries, i though chunkSortMode will help to sort these chunks , but order is dynamic when dealing with the multiple entry.

**Comment by jantimon** [comment]
well you can use different sorting styles and if none of them helps out you can write your own sorting function.

**Comment by pavankumarkatakam** [comment]
My problem is im setting chunksSortMode to different values but it is ordering with alphabetical order.

**Comment by jantimon** [comment]
As you can see the unit tests work for the different sorting orders:

https://github.com/ampedandwired/html-webpack-plugin/blob/master/spec/HtmlWebpackPluginSpec.js#L845-L922

**Comment by pavankumarkatakam** [comment]
yes ofcourse i have checked it already, but in my case they are not working im checking all my configuration i will update it.

**Comment by jantimon** [comment]
Okay - you might want to debug here:
https://github.com/ampedandwired/html-webpack-plugin/blob/739d6b93144edf09a35a43b312d316e222417a26/lib/chunksorter.js
This is where all the sorting magic happens

**Comment by jantimon** [comment]
Was this resolved?
