### ISSUE TITLE
Error: Cannot find module 'webpack/lib/node/NodeTemplatePlugin'

### ISSUE THREAD

**Issue by jrs320** [ampedandwired/html-webpack-plugin#226]
Hi,i met a problem,can you help me? (excuse me,my english is very pool  - - )

![image](https://cloud.githubusercontent.com/assets/6623047/13104265/0a06b68a-d597-11e5-904f-90e221546177.png)
my code aboved, i had installed html-webpack-plugin, when i webpack, a error happened:
![image](https://cloud.githubusercontent.com/assets/6623047/13104345/8d33b0f8-d597-11e5-8854-f36974dbb4e0.png)

what can i do,please help me, thanks.

**Comment by jrs320** [comment]
i get it, should install webpack local not global

**Comment by xwchris** [comment]
cool
