### ISSUE TITLE
How to add a apple-touch-icon using plugin

### ISSUE THREAD

**Issue by ysihaoy** [ampedandwired/html-webpack-plugin#227]
I figure out how to add a favicon using html webpack plugin and it works well.

But I want to add more stuff like apple-touch-icon, so we users save my website on their phone can have the logo as well.

Anyone knows how to work this out?

**Comment by jantimon** [comment]
You could write a custom plugin for html-webpack plugin or use a custom index.ejs file.

If you like to write a plugin you can combine the html-webpack-plugin hook `html-webpack-plugin-after-html-processing` and https://github.com/haydenbleasel/favicons

**Comment by graingert** [comment]
@ysihaoy you can use `<meta src="<% - require('./path/toImage'); %>" />`
