### ISSUE TITLE
Publish new version to npm

### ISSUE THREAD

**Issue by necolas** [ampedandwired/html-webpack-plugin#23]
1.1.0 is from August 2014 and the template API has changed since then.

Fixes #19 #22

**Comment by jasich** [comment]
:+1:  please release!

**Comment by oliviertassinari** [comment]
:+1:

**Comment by domderen** [comment]
:+1:

**Comment by emmenko** [comment]
+1

**Comment by aboutlo** [comment]
+1

**Comment by kenjiru** [comment]
It's pretty confusing when there is a mismatch between the documentation and the actual module.

So if there is a new version, please release it.

**Comment by nartamonov** [comment]
+1

**Comment by jordansexton** [comment]
Very confusing. :+1: @ampedandwired @jantimon

**Comment by ampedandwired** [comment]
Done, sorry guys.
