### ISSUE TITLE
Sub template lodash code comes as is in generated HTML

### ISSUE THREAD

**Issue by pavelsl** [ampedandwired/html-webpack-plugin#230]
Hi, i used your custom-template example to try to connect anaytics scripts. So my partial is: 
```
<%= htmlWebpackPlugin.options.title %>12
<% if (htmlWebpackPlugin.options.analytics.google) { %>
    <div>GA development</div>
    <div>GA production</div>
<% } %>

```
That's printed as is in generated index.html. Even "htmlWebpackPlugin.options.title" comes like this, though it works in parent template.

Can you provide any thoughts how to work it out?

**Comment by jantimon** [comment]
Is your file called .html? Do you have a html loader?
Looks like #176 #198 #202

**Comment by pavelsl** [comment]
I use it inside template to connect sub templates, i don't use it in webpack.config file. 

```
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8"/>
    <title><%= htmlWebpackPlugin.options.title %></title>

</head>
<body>
<%= require('html!./inc/header.html') %>
<h1>Some content goes here!!!</h1>
<!-- some comments to remove -->
<%= require('html!./inc/footer.html') %>
<%= require('html!./inc/analytics/google.html') %>
</body>
</html>
```


And it's google.html
```
<%= htmlWebpackPlugin.options.title %>12
<% if (htmlWebpackPlugin.options.analytics.google) { %>
    <div>GA development</div>
    <div>GA production</div>
<% } %>
```

Compiled index.html

```
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8"/>
    <title>SPA App</title>

<link rel="shortcut icon" href="favicon.ico"><link href="dist/main.1fc07eae3bbb8c9a78a9d3b9a71647d0.css" rel="stylesheet"></head>
<body>
<div class="header">
    <span>Header</span>
</div>
<h1>Some content goes here!!!</h1>
<!-- some comments to remove -->
<div class="footer">
    <span>Footer</span>
</div>
<%= htmlWebpackPlugin.options.title %>12
<% if (htmlWebpackPlugin.options.analytics.google) { %>
    <div>GA development</div>
    <div>GA production</div>
<% } %>
<script src="dist/main.4fc254fab2bcddf047a3.js"></script></body>
</html>
```

**Comment by pavelsl** [comment]
Have tried to use webpack.config html loader that ecludes index.html, have tried to use ejs loader -> no luck.

**Comment by jantimon** [comment]
Why do you use the html loader explicitly?

**Comment by pavelsl** [comment]
Actually i have tried different ways, use it in HTML file, use it webpack config loaders list, when i don't use it i get error as i remember. It would be great if you could provide an example of using multi level underscore templates.

BTW: Your example contains html! loader inside underscode template, so that's why i'm trying to use it.
https://github.com/ampedandwired/html-webpack-plugin/tree/master/examples/custom-template

I'm have no enough experience with webpack, and still can't understand complitely what's loader and whyat is the difference with plugin etc. So sorry, it could be complete trash in my code.

**Comment by pavelsl** [comment]
I just can't understand should i install use any EJS or _ loader additionally?

**Comment by pavelsl** [comment]
Ok, i have tried again. I have removed explitely call of HTML loader when i use "<%= require('./inc/footer.html') %>" inside my index.html -> it doesn't work. Throws error. 

So then i added webpack loaders config options:
, {
            test: /\.html$/,
            exclude: /index\.html$/,
            loader: 'html'
        }

To fix these errors. No errors now. But i still can't understand how i can use sub teplates and pass data to them.

Have tried to use ejs-loader and ejs-compiled-loader and they just append some JS instead of HTML into my index.html. 

Completely confused. 

I hope you understand why i'm trying to do this. Imagine we have a project with analytics, To prevent a mess in index.html we create footer.html + analytics.html which could as well require googleAnalytics.html etc templates. 

How to pass them data and make it work? Could you provide juse a quick small example of subtemplates with some strings that should be replaced with some data from JS. From any js, webpack.config or Application module itself.

**Comment by jantimon** [comment]
Please read the introduction of https://webpack.github.io/docs/loaders.html it explains how the `html!filename` syntax works.
Maybe this question suits better for stackoverflow.

You can use any loader. e.g. `ejs`, `jade`
See https://github.com/ampedandwired/html-webpack-plugin/tree/4a69c9a013209a918c7a1bf70a34c5fb1b41cae8/examples/jade-loader as an example.

**Comment by pavelsl** [comment]
Hmm, I see the Jade example and it’s clear.
But what if you need to do the same example with default underscore templates you have in your module.
Could you try? Or we can say that default underscore templates you have works only with index.html (or ejs) template itself and to use JS strings interpolations in internal templates we need use another template engine (loader)

Thanks a lot anyway!

Sincerely yours,
Pavel Shlykov / Software Developer / iTechArt Group
Skype: james_hatfield86
Email: pavel.shlykov@itechart-group.com

**Comment by jantimon** [comment]
The built in loader is only a fallback to keep backwards compatibility for the main template.
If you want to use ejs you should use ejs for everything.
Just do it exactly like the jade example but use an ejs loader e.g. https://github.com/emaphp/underscore-template-loader

**Comment by Harrix** [comment]
I have earned such option code.
Sub template:
```
<footer><%=name%> </footer>
```
Main template:
```
<!DOCTYPE html>
<html>
<head></head>
<body>
<% 
var tmpl = _.template(require('./templates/footer.html'));
var data = {
    name: "Harrix"
}; 
%>
<%= tmpl(data) %>
</body>
</html>
```
Rule for webpack.config.js:
```
      {
        test: /\.html$/,
        include: path.resolve(__dirname, 'src/templates'),
            loader: 'raw-loader',
      },
```
Result:
```
<!DOCTYPE html>
<html>
<head></head>
<body>

<footer>Harrix </footer>
</body>
</html>
```

**Comment by Akumuliation** [comment]
For multi-level nesting templates is not suitable. The drawback is that the paths of the pictures in the parent html remain the same as and were for the sourse folder
