### ISSUE TITLE
Express Server and (React) Routes not injecting JS

### ISSUE THREAD

**Issue by glennreyes** [ampedandwired/html-webpack-plugin#236]
I am confguring a fresh webpack setup with react router and express right now and intend to use your awesome html-webpack-plugin.
I've setup all my routes (```/``` and ```*``` redirects to ```/404```) and server and I wonder how to setup the server correctly to receive the correct routes.
When I try to go to ```http://localhost:3000/something``` f.e., I am getting just the raw HTML template  without the injected JS and stuff that I've configured in the ```webpack.config.js```.

##### Following setup
webpack.config.js
```js
...
      new HtmlWebpackPlugin({
        template: PATHS.src + '/index.html'
      })
...
```
server.js
```js
const Express = require('express');
const path = require('path');
const webpack = require('webpack');
const webpackDevMiddleware = require('webpack-dev-middleware');
const webpackHotMiddleware = require('webpack-hot-middleware');
const config = require('./webpack.config');

const app = new Express();
const port = process.env.PORT || 3000;

const compiler = webpack(config);

app.use(webpackDevMiddleware(compiler, {
  noInfo: true
}));

app.use(webpackHotMiddleware(compiler));

app.use('/', function(req, res, next) {
  res.sendFile(path.join(__dirname, 'src') + '/index.html');
});

app.listen(port, function(error) {
  if (error) {
    console.error(error);
  } else {
    console.info('The express server is running at http://localhost:%s\n', port);
  }
});
```
src/index.html
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>React Boilerplate</title>
  </head>
  <body>
    <div id="root"></div>
  </body>
</html>
```
routes/index.js
```jsx
...
export default (
  <Route path="/" component={App}>
    <IndexRoute component={HomeView} />
    <Route path="/404" component={NotFoundView} />
    <Redirect from="*" to="/404" />
  </Route>
)
```

What do I need to setup to get routings working with html-webpack-plugin? I appreciate every help.

**Comment by jantimon** [comment]
Please ask webpack middleware questions on stackoverflow. Webpack middleware can't be used together with `res.sendFile(path.join(__dirname, 'src') + '/index.html');`
