### ISSUE TITLE
Help needed: How to add SVG to head [solved]

### ISSUE THREAD

**Issue by nelo112** [ampedandwired/html-webpack-plugin#239]
Hi,

I have a .svg file with content like this:
```
<svg xmlns="http://www.w3.org/2000/svg" style="height: 0; width: 0; position: absolute; visibility: hidden">
    <symbol viewBox="0 0 153.852 153.852" id="horizontal-arrow-left-up">
        <polygon points="141,40 141,0 0,0 0,141 40,141 40,65.702 128.148,153.852 153.852,128.148 65.703,40 	"/>
    </symbol>
</svg>
```

I want to add the content of this file as-is into the head of the index.html. I can't for the live of me figure out how to do this.
Can anybody show me how this can be done?

Thanks!

**Comment by jantimon** [comment]
You can use a loader e.g. the svgo loader and a require statement like `<%= require('my.svg'); %>`

**Comment by nelo112** [comment]
Thanks! That was exactly what is was looking for :)
