### ISSUE TITLE
Only generate HTML once

### ISSUE THREAD

**Issue by SimenB** [ampedandwired/html-webpack-plugin#244]
I've noticed that if I exclude `html-webpack-plugin` from tests, the re-compile time is much lower. And while tests don't need the html at all, I need them for regular development.

So I'm wondering if it's possible to generate the HTML only once, and not on rebuilds?

**Comment by SimenB** [comment]
I was able to hack it together, and recompiles went from 10-12 seconds to less than 7. (we have a very slow recompile, working on it!)

```patch
 index.js | 6 +++++-
 1 file changed, 5 insertions(+), 1 deletion(-)

diff --git a/index.js b/index.js
index 7714d4e..70a8d19 100644
--- a/index.js
+++ b/index.js
@@ -23,7 +23,8 @@ function HtmlWebpackPlugin (options) {
     showErrors: true,
     chunks: 'all',
     excludeChunks: [],
-    title: 'Webpack App'
+    title: 'Webpack App',
+    noRecompiles: false
   }, options);
 }
 
@@ -35,6 +36,7 @@ HtmlWebpackPlugin.prototype.apply = function (compiler) {
   this.options.template = this.getFullTemplatePath(this.options.template, compiler.context);
 
   compiler.plugin('make', function (compilation, callback) {
+    if (self.options.noRecompiles && self.compiled) return callback();
     // Compile the template (queued)
     compilationPromise = childCompiler.compileTemplate(self.options.template, compiler.context, self.options.filename, compilation)
       .catch(function (err) {
@@ -53,6 +55,7 @@ HtmlWebpackPlugin.prototype.apply = function (compiler) {
   });
 
   compiler.plugin('emit', function (compilation, callback) {
+    if (self.options.noRecompiles && self.compiled) return callback();
     var applyPluginsAsyncWaterfall = Promise.promisify(compilation.applyPluginsAsyncWaterfall, {context: compilation});
     // Get all chunks
     var chunks = self.filterChunks(compilation.getStats().toJson(), self.options.chunks, self.options.excludeChunks);
@@ -160,6 +163,7 @@ HtmlWebpackPlugin.prototype.apply = function (compiler) {
       })
       // Let webpack continue with it
       .finally(function () {
+        self.compiled = true;
         callback();
         // Tell blue bird that we don't want to wait for callback.
         // Fixes "Warning: a promise was created in a handler but none were returned from it"
2.6.2
```

**Comment by SimenB** [comment]
See linked PR

**Comment by jantimon** [comment]
Well actually this what caching is for - if the caching is broken we should rather fix it.

**Comment by SimenB** [comment]
`cache` tries to be smart, and still does a lot of work before checking if it should return early. My "implementation" forces it to return early without doing any work.

And while it does enter into the `return callback()` of the `if`, a new template is still emitted

**Comment by jantimon** [comment]
Have you tried `iron-node`? It's imho the only way to deal with this blackbox

**Comment by SimenB** [comment]
I haven't tried it no, I just debug within IntelliJ/WebStorm. Though I suppose Chrome has an even better debugger for JS!

**Comment by jantimon** [comment]
The first step to solve this mess would to make it testable

**Comment by jantimon** [comment]
@SimenB I have just released [a small util](https://github.com/jantimon/webpack-recompilation-simulator) which would allow us to test the cache - what do you think?

The test might look similar to the included tests (however we would have to add spies):
https://github.com/jantimon/webpack-recompilation-simulator/blob/master/test/index.js

**Comment by jantimon** [comment]
@SimenB I've added some simple test cases to verify that the html is compiled only once.
Could you please add a scenario where the caching did not work?

**Comment by jantimon** [comment]
Doesn't seem to bring real benefits. See #263

**Comment by moimael** [comment]
That would decrease our recompile time by more than half. We have multiple entrypoint and emmitiing html on each rebuild adds ~3s to the compile time. Our hot reload time went from 5.5s to 1.9s when the plugin do not emit html files on each rebuild.
