### ISSUE TITLE
Consider option for output path

### ISSUE THREAD

**Issue by sunyang713** [ampedandwired/html-webpack-plugin#250]
Hi, so it seems that the plugin outputs the generated index.html to the `publicPath` along with all other files. Is there a way to specify the output path?

If there is, I'm sorry for the noise, and please ignore everything below this.

EDIT: I've just come across this: https://github.com/ampedandwired/html-webpack-plugin/issues/234
I still stick by my argument below, because ultimately I want to supply the compiled files & generated index.html to a backend server, and when that happens, index.html is not an "asset" in the same scope as css, js, or image files.

Here is the webpack config:

```javascript
module.exports = {
  . . .
  output: {
    filename: "[name].js",
    path: "build",
    publicPath: ""
  },
  . . .
  plugins: [
    new HtmlWebpackPlugin({
      template: "index.html"
    })
    . . .
  ],
  . . .
}
```

The consequential build package looks like so:

```
|-- build/
\
  |-- index.html
  |-- main.js
```

However, I would like to separate the javascript files into its own folder, so that the structure looks like so:
```
|-- build/
\
  |-- index.html
  |-- js/
  \
    |-- main.js
```

There are a number of ways to achieve this currently, and none of them are difficult, but none are ideal or 'correct' in my opinion. I think the ideal solution allows all "assets" (.js, .css, .jpg, etc...) to be placed in the `publicPath` directory, and the `index.html` should still remain in the root `build/` directory (specified by the `output.path` option in the webpack config).

I could manually write the `index.html` file and place it at the root-level of `build/`, but this would stop me from taking advantage of auto-generating the `index.html` file with hashes (or at least, make it very annoying).

I can specify the output path in the name for all files except for the index.html file, but it feels like an anti-pattern to have to adjust every other file via the name field except for index.html, instead of the other way around. If I use the `commonsChunkPlugin`, I have to do it for each of those bundles. If I have multiple commons chunks, I will need to specify the path for each one. If I extract the css-sheets, I have to specify the path there. I don't know how to specify the path for images yet. This is what it would look like:

```javascript
module.exports = {
  . . .
  output: {
    filename: "assets/[name]-[hash].js",
    path: "build",
    publicPath: ""
  },
  . . .
  plugins: [
    new HtmlWebpackPlugin({
      template: "index.html"
    }),
    new webpack.optimize.CommonsChunkPlugin({
      name: "commons",
      filename: "assets/[name]-[hash].js"
    }),
    new ExtractTextPlugin(
      "assets/[name]-[hash].css"
    ),
    . . .
  ],
  . . .
}
```

Instead, I think the ideal config might look like this:
```javascript
module.exports = {
  . . .
  output: {
    filename: "[name]-[hash].js",
    path: "build",
    publicPath: "assets"
  },
  . . .
  plugins: [
    new HtmlWebpackPlugin({
      template: "index.html",
      path: "build"
    }),
    new webpack.optimize.CommonsChunkPlugin({
      name: "commons",
      filename: "[name]-[hash].js"
    }),
    new ExtractTextPlugin(
      "[name]-[hash].css"
    ),
    . . .
  ],
  . . .
}
```

Let me know what you think!

**Comment by svenanders** [comment]
Agree, I want all my assets in assets and the index.html in the root. Currently, I can't find a way to do that.

**Comment by jantimon** [comment]
Please see: https://github.com/ampedandwired/html-webpack-plugin/issues/234
