### ISSUE TITLE
No option to inject _some_ chunks into `head`, and _some_ assets into `body`

### ISSUE THREAD

**Issue by Birch-san** [ampedandwired/html-webpack-plugin#252]
Maybe I am misunderstanding how to use this, but I get the impression that *all* chunks must be co-located:

```js
new HtmlWebpackPlugin({
	chunks: ['above-fold', 'deferred-content'],
	template: 'games/index.html',
	inject: 'body' // *all* chunks have to go in `body` :(
})
```

I would really like the "above-fold" chunk to be injected into `head`. _Bonus points for inlining it!_

But I would like the "deferred-content" chunk to be injected into `body`. _Bonus points for *not* inlining it!_

It looks like this boolean is enforced even under-the-hood:

https://github.com/ampedandwired/html-webpack-plugin/blob/master/index.js#L435-L440
```js
// Add scripts to body or head
if (this.options.inject === 'head') {
	head = head.concat(scripts);
} else {
	body = body.concat(scripts);
}
```

Is there some way for me to choose where each chunk gets injected?

Proposed syntax:

```js
new HtmlWebpackPlugin({
	chunks: [{
		name: 'above-fold',
		inject: 'head',
		inline: true
	}, {
		name: 'deferred-content',
		inject: 'body',
		inline: false
	}],
	template: 'games/index.html'
})
```

**Comment by jantimon** [comment]
You have to turn injection of and handle it completely by your own.
The template variables contain all information to handle it without injection

**Comment by jantimon** [comment]
https://github.com/jaketrent/html-webpack-template
https://github.com/jaketrent/html-webpack-template/blob/master/index.ejs

**Comment by Birch-san** [comment]
So I would put something like this in the head and in the body?

```ejs
<% for (var chunk in htmlWebpackPlugin.files.chunks) { %>
<script src="<%= htmlWebpackPlugin.files.chunks[chunk].entry %>"></script>
<% } %>
```

Is there anything I can write into the `HtmlWebpackPlugin` definition:

```js
new HtmlWebpackPlugin({
    chunks: ['above-fold', 'deferred-content']
})
```

To help my `.ejs` know the difference between each entry in `htmlWebpackPlugin.files.chunks`? For example: I can see that a naming convention might do the trick; `chunks: ['head:above-fold', …]`. Is that the best way available?

**Comment by jantimon** [comment]
Did this work out for you?

**Comment by Birch-san** [comment]
for a short-term solution I smashed everything in as inline CSS, rather than wrestle with webpack.
probably on the weekend I'll have a crack at the templating solution.
feel free to close this issue (or leave it open to hear how it goes)

**Comment by jantimon** [comment]
You could also write a small plugin - the html-webpack-plugin offers some hooks.
Would love to hear the final outcome.

**Comment by benelliott** [comment]
For anyone else who finds this thread after having similar issues, I hacked around it by defining my own template file which looks as follows:
# `template.html`
```
...
<head>
    <% for (var chunk in htmlWebpackPlugin.options.heads) { %>
    <script src="<%= htmlWebpackPlugin.files.chunks[htmlWebpackPlugin.options.heads[chunk]].entry %>"></script>
    <% } %>
</head>
<body>
<% for (var chunk in htmlWebpackPlugin.options.bodys) { %>
<script src="<%= htmlWebpackPlugin.files.chunks[htmlWebpackPlugin.options.bodys[chunk]].entry %>"></script>
<% } %>
</body>
...
```

This let me split my list of chunks into two arrays: `heads` and `bodys`. The plugin configuration then looked like this (chunk names are just placeholders):

# `webpack.config.js`
```
...
new HtmlWebpackPlugin({
    template: '<<path to template.html>>',
    inject: false,
    chunks: ['bodyChunkA', 'bodyChunkB', 'headChunkA', 'headChunkB'],
    heads: ['headChunkA', 'headChunkB'],
    bodys: ['bodyChunkA', 'BodyChunkB']
})
...
```
Note that any chunks you want to include in the head or body must still be referenced in `chunks` or they will not be resolved properly.

The solution is far from elegant but it works for the time being.

**Comment by chauhanvishaal** [comment]
Hi Benelliott! I am trying to implement the solution you suggested, however the html template doesnt seem to get processed. HtmlWebpackPlugin simply duplicates the template as is.  would really appreciate if you could suggest possible issue/ fix. Many thanks..

**Comment by benelliott** [comment]
@chauhanvishaal Can you share your template and webpack config?

**Comment by chauhanvishaal** [comment]
Thanks for your reply Ben.
I got this working finally. apart from the config you've mentioned, Had to update the template as below.
 { template: 'underscore-template-loader!./index.html', } 
any other loader didn't seem to work.
So the complete HtmlWebpackPlugin config based on your suggestion is as below: 
CommonModule.plugins.push(new HtmlWebpackPlugin({
    filename: "index.html",
    inject: false, //"head",
   template: 'underscore-template-loader!./index.html',
    chunks: ['indexhead','indexbody', 'framework', 'libs', 'main'],
    head: ['indexhead'],
    body: ['indexbody', 'framework', 'libs', 'main']
}));
