### ISSUE TITLE
update Changelog

### ISSUE THREAD

**Issue by mistadikay** [ampedandwired/html-webpack-plugin#253]
Hey guys,

could you please update changelog regularly with every release. It's really a couple of minutes for you, but it's a huge deal for everyone who uses this package, because they don't need to scroll commit history in order to find out what changed.

Thanks

**Comment by jantimon** [comment]
Could you please add a merge request to update it to the current state?
Then I will try to update it from now on.

**Comment by mistadikay** [comment]
@jantimon I can try, but since I'm not a regular contributor I'm not sure if I'll do it right

**Comment by jantimon** [comment]
Cool I guess people would love you for it :+1:

**Comment by mistadikay** [comment]
@jantimon done. I hope I didn't miss anything
