### ISSUE TITLE
How to make my custom variables work when I use server rendering?

### ISSUE THREAD

**Issue by leozdgao** [ampedandwired/html-webpack-plugin#262]
I am using server rendering for my project, and generate some data on the server for first screen. And I have some data like `{ initData: { ... }, title: "my-title" }`. And I have template like this:

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <meta name="screen-orientation" content="portrait">
    <meta name="x5-orientation" content="portrait">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
    <title><%= title %></title>
    <link href="//cdn.bootcss.com/font-awesome/4.5.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="//cdn.bootcss.com/highlight.js/9.1.0/styles/tomorrow.min.css" rel="stylesheet">
    <script type="text/javascript">
    var initData = <%= JSON.stringify(initData) %>
    </script>
  </head>
  <body>
    <div class="site-wrapper">
      <%= body %>
    </div>
    <script src="//cdn.bootcss.com/highlight.js/9.1.0/highlight.min.js"></script>
  </body>
</html>
```

I try to put my variables to `app.locals` (yes, express app), but it didn't work. And I check the template examples, but only access the variable `htmlWbpackPlugin.options`. So does custom variables supported? How to make them works? Thanks.

**Comment by jantimon** [comment]
You should precompile it with webpack and escape `<%= JSON.stringify(initData) %>` then you can use it with your express app.

**Comment by leozdgao** [comment]
@jantimon Sorry, I couldn't fully understand your solution, I think it use ejs by default, and why I have to escape `<%= JSON.stringify(initData) %>`.

**Comment by jantimon** [comment]
Could you please post your loader configuration?

**Comment by leozdgao** [comment]
@jantimon Sure, here it is:

```js
const webpack = require('webpack')
const HtmlWebpackPlugin = require('html-webpack-plugin')
const path = require('path')
const env = require('../env')

const entry = env.entry
const browsers = JSON.stringify({ browsers: [ "IOS >= 7", "Android >= 4" ] })
const cssLoader = `style!css?importLoaders=1&sourceMap!autoprefixer?${browsers}`

module.exports = {
  devtool: 'cheap-module-eval-source-map',
  entry,
  output: {
    path: env.publicPath,
    filename: 'bundle.js',
    publicPath: '/'
  },
  plugins: [
    new webpack.HotModuleReplacementPlugin(),
    new webpack.DefinePlugin({
      'process.env': JSON.stringify('development')
    }),
    new webpack.ProvidePlugin({
      riot: 'riot'
    }),
    new HtmlWebpackPlugin({
      template: './server/views/index.html'
    })
  ],
  resolve: {
    extensions: [ '', '.js', '.tag' ]
  },
  module: {
    loaders: [
      {
        test: /\.js$/,
        loader: 'babel',
        exclude: /node_modules/
      },
      {
        test: /\.tag$/,
        loader: 'riotjs',
        exclude: /node_modules/
      },
      {
        test: /\.scss$/,
        loader: `${cssLoader}!sass`,
        exclude: /node_modules/
      },
      {
        test: /\.css$/,
        loader: cssLoader
      },
      {
        test: /\.woff(2)?(\?v=[0-9]\.[0-9]\.[0-9])?$/,
        loader: "url?limit=10000&mimetype=application/font-woff"
      },
      {
        test: /\.(ttf|eot|svg)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
        loader: "file"
      }
    ]
  },
  sassLoader: {
    includePaths: [
      path.resolve(__dirname, "../../node_modules/normalize-scss/sass/"),
      path.resolve(__dirname, "../../node_modules/support-for/sass/"),
      path.resolve(__dirname, "../../src/__shared/sass/")
    ]
  }
}
```

**Comment by jantimon** [comment]
The html-webpack-plugin uses the `ejs` loader only if no other loader was specified.

So one solution might be to use the `html-loader`:

```js
new HtmlWebpackPlugin({
    template: '!!html!./server/views/index.html'
})
```

Then the result would still contain your ejs code.

**Comment by leozdgao** [comment]
Still have some problems, I use `connect-history-api-fallback` to rewrite the url, I get the result which contains my ejs code, but I want to compile it on server with initial data. If I use `res.render`, I can't let this plugin do the magic.

So could I get the result of this plugin (a string from memory maybe, and the js bundle script link has been inserted), and I render it with my ejs compiler.

**Comment by jantimon** [comment]
You could probably use the outputFileSystem:
```js
var compiler = webpack({/* config */});
compiler.outputFileSystem
```

**Comment by jantimon** [comment]
Or you could use the `html-webpack-plugin-after-emit` event:

```js
var compiler = webpack({/* config */});
compiler.plugin('compilation', function(compilation) {
  compilation.plugin('html-webpack-plugin-after-emit', function(htmlPluginData, callback) {
    console.log(htmlPluginData);
    callback();
  });
});

**Comment by sunyang713** [comment]
hi @jantimon , referring to your first response, how can you 'escape' a line? I keep getting 'unexpected token %' when I try to write `<%% some stuff %>`

**Comment by jantimon** [comment]
Couldn't you just use a loader which ignores the underscore template? I don't know how underscore escaping works exactly - sorry - I am just using it ;)

**Comment by sunyang713** [comment]
Yeah, you're definitely right. Using a loader (for handlebars, jade, ejs, whatever) would definitely be a more powerful solution, allowing you to use their syntax instead of the somewhat limited underscore template. In my case, I'm actively trying to limit the new packages and new tech/syntax I'm bringing into my project, and the underscore syntax was good enough for my needed solution.
