### ISSUE TITLE
Script selection

### ISSUE THREAD

**Issue by sirwolfgang** [ampedandwired/html-webpack-plugin#264]
Is there a way to only include/inject a selected script, while compiling the rest?

I have multiple entry points, and with to only use one in the generated HTML file.

**Comment by sirwolfgang** [comment]
Ahh. Sorry, its done with chunks
```plugins: [
  new HtmlWebpackPlugin({
    chunks: ['app']
  })
]```

**Comment by jantimon** [comment]
:+1:
