### ISSUE TITLE
Possibility to inline bundle content into html?

### ISSUE THREAD

**Issue by floelhoeffel** [ampedandwired/html-webpack-plugin#268]
Hey There,

I was wondering if it is possible to use the html-webpack-plugin to inline the actual content of a bundle in a template instead of referencing the file?

So I have:

bundle.js
`alert(1);`

and in my template I would want

`<!DOCTYPE html><html><body><script>alert(1);</script></body></html>`

instead of

`<!DOCTYPE html><html><body><script src="bundle.js"></script></body></html>`

Thanks!

**Comment by jantimon** [comment]
Please take a look at the inline example.

**Comment by floelhoeffel** [comment]
Great, I should have looked there first. Thanks!

**Comment by jantimon** [comment]
It's quite new so please just let me know if something fails.

**Comment by floelhoeffel** [comment]
Works like a charm. Except, when I run webpack with watch flag, it will not reprocess the html file after changes in the JS. What is the best way to achieve that? Thanks!

**Comment by jantimon** [comment]
Oh yes sorry - you have to disable the caching. Should work with the `cache` : false flag.

**Comment by floelhoeffel** [comment]
Perfect - works - thanks!

**Comment by jantimon** [comment]
K I'll update the example

**Comment by le93us** [comment]
Is it possible to inject bundle without template engine, such like `jade`?

**Comment by le93us** [comment]
There is a [plugin to yout plugin](https://github.com/dustinjackson/html-webpack-inline-source-plugin), but, IMHO, it will be ok if it will be core feature.
