### ISSUE TITLE
Find the generated file and render it

### ISSUE THREAD

**Issue by vini175pa** [ampedandwired/html-webpack-plugin#269]
Hi everyone! I need some help. I have a view ( .hbs ) and I'm using this plugin to inject the bundle link in it, but I wanna render it on one of my routes. I'm using `koa-views` to render my views. In localhost, I can find the "parsed" view on `locahost:8080/index.html`, but I'm not being able to make it work properly. I doesn't find the file.

What I wanna do: Find my view after injection and render it with `koa-views`.

Entire code: https://github.com/vini175pa/koa-redux-starterkit
Routes: https://github.com/vini175pa/koa-redux-starterkit/blob/master/server/routes/index.js
Webpack.config.js https://github.com/vini175pa/koa-redux-starterkit/blob/master/webpack.config.js

Can anyone help me?

**Comment by jantimon** [comment]
Might this help?
https://github.com/ampedandwired/html-webpack-plugin/issues/262#issuecomment-198968660
