### ISSUE TITLE
CSS files are not found when hashes are enabled

### ISSUE THREAD

**Issue by jordansexton** [ampedandwired/html-webpack-plugin#27]
When the option `hash: true` is passed, [this will always return false](/ampedandwired/html-webpack-plugin/blob/master/index.js#L114) since the filename is going to be something like `application.css?0fc37e2ac45d38db73b8`

What this means is that the `css` property of [the files object](/ampedandwired/html-webpack-plugin/blob/master/index.js#L19) will always be an empty array.

This may have been introduced in [6a9d902] but it could easily be earlier. It's hard to tell as there are [no CSS tests](/ampedandwired/html-webpack-plugin/blob/master/spec/HtmlWebpackPluginSpec.js), only JS tests.

**Comment by jantimon** [comment]
Hey @jordansexton - thanks for the feedback.
This issue was already resolved with #26 - which is part of #15 and will be released soon in 1.3.0.

**Comment by jordansexton** [comment]
Ah, good to know. Thanks!
