### ISSUE TITLE
Problem with custom-template example

### ISSUE THREAD

**Issue by yanyu0517** [ampedandwired/html-webpack-plugin#270]
I have a problem with custom-template example:
I have added a img tag in template.html like:
`<body>
  .........
<img src="abc.png">
</body>`

After webpack build, the abc.png still is abc.png in dist/webpack1/index.html
`<body>
 .......
<img src="abc.png">
</body>`

I think the abc.png should be complied to some thing like [hash].png, is that right?

**Comment by jantimon** [comment]
This is done by a loader not by the plugin. Choose the html-loader or the underscore-template-loader or any similar loader which supports files.
