### ISSUE TITLE
Possible to use JS file for template?

### ISSUE THREAD

**Issue by jschr** [ampedandwired/html-webpack-plugin#271]
Is it possible to use js for the template file? Similar to [static-site-generator-webpack-plugin](https://github.com/markdalgleish/static-site-generator-webpack-plugin). If it is, can someone provide an example of a working index.js? 

```js
// webpack.config.js
{
  module: {
    loaders: [
      { test: /\.js$/, loader: 'babel' }
    ]
  }
  plugins: [
    new HtmlWebpackPlugin({
      filename: 'index.html',
      template: 'src/index.js',
      inject: false,
      title: 'My App'
    })
  ]
}

// src/index.js
export default function (options) {
  return `
    <html>
      <head>
        <title>${ options.title }</title>
      </head>
       ...
    </html>
  `
}
```

**Comment by jschr** [comment]
This appears to work but for some reason webpack dev server's live reload isn't working

```js
// src/index.js
module.exports = function ({ htmlWebpackPlugin: { files, options } }) {
   return `
    <html>
      <head>
        <title>${ options.title }</title>
      </head>
       ...
    </html>
  ` 
}
```

**Comment by jantimon** [comment]
which part of the live reloading fails?
afaik webpack supports only css and js hot reloading but not html

**Comment by jschr** [comment]
with an .ejs template file webpack seems to detect the file change and auto reload the browser (not hot reload).
with the above .js template changes aren't detected and I need to manually reload the browser.

**Comment by jantimon** [comment]
Well the technology is the same - webpack shouldn't see any difference..

**Comment by jschr** [comment]
fair enough, didn't investigate too much further and just switched back to ejs. I posted my findings in case anyone else was curious. I'll post back here if I end up getting it to work properly.

**Comment by jantimon** [comment]
Cool :) also open for pull requests on this.
