### ISSUE TITLE
Need better diagnostics 

### ISSUE THREAD

**Issue by SteveALee** [ampedandwired/html-webpack-plugin#272]
I spent a large part of yesterday trying to get `html-webpack-plugin` working with hot loading. A SO Question convinced me it should be possible and in the end it turned out to be very sensitive to the `index.html` path. I had to handle it differently between hot serving and build. At least I did get it working

Any sort of error message would really help with this sort of problem. Form SO it's clear others have problems.

Here is my config 
https://github.com/OpenDirective/brian/blob/master/package.json https://github.com/OpenDirective/brian/blob/master/client/webpack.config.js

In particular build:

```javascript
    plugins: [new HtmlWebpackPlugin({filename: path.join(PATHS.dist, 'index.html'),
                          template: path.join(PATHS.src, 'index.html'),
                          inject: true
                          }),
              new CopyWebpackPlugin([{from: path.join(PATHS.src, 'favicon.ico'), to: '..'},
                          {from: path.join(PATHS.src, 'CNAME'), to: '..'},
                                {from: path.join(PATHS.src, 'img'), to: '../img'}]), // abs paths to: don't work
              new webpack.NoErrorsPlugin(),
              new ExtractTextPlugin('../css/[name].css'),
              new webpack.optimize.UglifyJsPlugin({minimize: true})
  ]
 
```

and dev serve:

```javascript
    plugins: [
      new HtmlWebpackPlugin({filename: 'index.html',
                              template: path.join(PATHS.src, 'index.html'),
                              inject: true
                            })
    ]
```

Thanks

**Comment by jantimon** [comment]
Cool thanks I don't understand the problem but please open a pull request for a better error message - would love to merge it
