### ISSUE TITLE
The ejs file has a img element, look like url-loader don't loader it

### ISSUE THREAD

**Issue by zhangsanshi** [ampedandwired/html-webpack-plugin#275]
the plugins 

> new HtmlWebpackPlugin({
>             filename: './index.html',
>              publicPath: publicPath,
>             hash: true,
>             minify: {
>                 removeComments: false, 
>                 collapseWhitespace: false 
>             },
>             template: './index.tmpl.ejs'
>         })

the loaders 

> {
>             test: /\.(png|jpeg|jpg|gif|svg)$/,
>             loaders: [
>                 'url?limit=10000&name=imgs/[name].[ext]?[hash:7]',
>                 'image-webpack?{bypassOnDebug:true,progressive:true, optimizationLevel: 7, interlaced: false, pngquant:{quality: "65-90", speed: 4}}'
>             ]
>         },{
>             test: /\.html$/,
>             loader: 'html-loader'
>         }

**Comment by jantimon** [comment]
Ejs has no image loader support - please try the https://github.com/emaphp/underscore-template-loader
