### ISSUE TITLE
Template Require via environment variable

### ISSUE THREAD

**Issue by Hanterdro** [ampedandwired/html-webpack-plugin#277]
Hey,

based on this Example (https://github.com/ampedandwired/html-webpack-plugin/tree/master/examples/custom-template) I created an similar setup which requires the sub html file via an environment var.

```
function generate_page(config) {
	var tempateUrl = config.templateUrl ? config.templateUrl : 'src/template.html';
	return new HtmlWebpackPlugin({
		filename:  config.filename,
		template: tempateUrl,
		xhtml: true,
		environment: {templateUrl:  config. subTemplateUrl}
	});

}
```

My src/template.html' requires this subtemplate:

```
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
</head>
<body>
<% require('html!'+ htmlWebpackPlugin.options.environment.templateUrl ) %>
</body>
</html>
````

But when I run ``` webpack  --progress --colors --watch -d``` I just get that error:

```
ERROR in Template execution failed: Error: Cannot find module "."

ERROR in   Error: Cannot find module "."
  
  - template.html:57 webpackMissingModule
    /Users/xxx/PycharmProjects/webpack-test/src/template.html:57:47
  
  - template.html:57 
    /Users/xxx/PycharmProjects/webpack-test/src/template.html:57:125
  
  - template.html:62 module.exports
    /Users/xxx/PycharmProjects/webpack-test/src/template.html:62:4
  
  - index.js:228 
    [webpack-test]/[html-webpack-plugin]/index.js:228:16
  
  - util.js:16 tryCatcher
    [webpack-test]/[bluebird]/js/release/util.js:16:23
  
  - promise.js:503 Promise._settlePromiseFromHandler
    [webpack-test]/[bluebird]/js/release/promise.js:503:31
  
  - promise.js:560 Promise._settlePromise
    [webpack-test]/[bluebird]/js/release/promise.js:560:18
  
  - promise.js:597 Promise._settlePromiseCtx
    [webpack-test]/[bluebird]/js/release/promise.js:597:10
  
  - async.js:131 Async._drainQueue
    [webpack-test]/[bluebird]/js/release/async.js:131:12
  
  - async.js:136 Async._drainQueues
    [webpack-test]/[bluebird]/js/release/async.js:136:10
```

If I write the same subTemplateUrl in the template.html file instead of the variable everything works fine:

```
<% require('html!./test.html' ) %>
```

**Comment by jantimon** [comment]
It seems like your variable contains only `"."`.

**Comment by Hanterdro** [comment]
Yes, but this is not true.
If I write the variable instead of require it than I get the correct url.

```
<% htmlWebpackPlugin.options.environment.templateUrl %>
-->
./test.html
```

**Comment by jantimon** [comment]
Oh - I believe webpack can't handle dynamic require statements.

**Comment by Hanterdro** [comment]
Basically it should:

https://webpack.github.io/docs/context.html

**Comment by jantimon** [comment]
But your are using it wrong.
Please ask questions about the webpack context require statements on stackoverflow.

**Comment by Hanterdro** [comment]
Hi Jantimon,

thank you for your response. I added this question to stackoverflow.
After you figured out that I'm using it wrong I'm sure that you know what I do wrong and answer the Question at Stackoverflow:
http://stackoverflow.com/questions/36387544/require-variable-with-html-webpack-plugin

:-)
