### ISSUE TITLE
add beautify param for result html

### ISSUE THREAD

**Issue by DragorWW** [ampedandwired/html-webpack-plugin#278]
I use twig template engine, after compiled, html is looks bad.

**Comment by jantimon** [comment]
this plugin has nothing to do with twig - please talk to the twig loader developer

**Comment by rondonjon** [comment]
I am using html-webpack-plugin together with the favicons plugin. The favicon-injected markup does not contain any linebreaks, the rest of the html looks nice, so I assume that there is some kind of tidying implemented, but the order seems wrong. Can I somehow tell html-webpack-plugin to finish the inclusions first and then tidy everything?
