### ISSUE TITLE
Favicon 

### ISSUE THREAD

**Issue by cgarvis** [ampedandwired/html-webpack-plugin#28]
Any suggestions on adding a favicon?

**Comment by jantimon** [comment]
You could use a custom template or templateContent

**Comment by SimenB** [comment]
@jantimon Will Webpack pick up the usage and include the image in it's build?

**Comment by jantimon** [comment]
No unfortunately it won't as webpack gathers only files from the loaders.

**Comment by SimenB** [comment]
@jantimon I just got it working locally, I'll throw together a PR later today

**Comment by jantimon** [comment]
Cool

**Comment by tomatau** [comment]
How does this work? Trying to add a favicon to my webpack dist. Currently trying this:

```
  entry:
    "main" : [
      "#{SRC}/favicon.ico"
    ]
  module:
    loaders: [{
      test: /\.ico$/,
      loader: ExtractTextPlugin.extract('file')
    }
  plugins: [
    new ExtractTextPlugin("favicon.ico",
      allChunks: false
    )
 ]
```
More recent browsers don't need the favicon file specified in the html so nothing needed by HtmlWebpackPlugin.

This gets the favicon and puts it into the correct output but the file isn't valid... 
This is probably outside the remit of your plugin but I can't find any other discussions about this! Any help appreciated!

**Comment by SimenB** [comment]
@tomatau You could try it's own loader for `favicon` (just `file`), then set the name, so that webpack doesn't just give it a MD5 name

**Comment by jantimon** [comment]
The solution for 1.4.0 allows to add favicon (however it hasn't been merged into the master branch yet):

```javascript
new HtmlWebpackPlugin({
  favicon: 'my-favicon.ico'
})
```

Specifying a favicon name allows you to have different icons for different environment. (e.g. development, stage, prod)

**Comment by tomatau** [comment]
does this favicon file get picked up without being added as an entry or required by a webpack bundled codebase elsewhere?

**Comment by jantimon** [comment]
Yes it is - however the name isn't getting hased by now - so if anyone could add this I would love to merge it.

**Comment by jantimon** [comment]
Should we add https://github.com/haydenbleasel/favicons ?
