### ISSUE TITLE
Another approach to inlining styles now available.

### ISSUE THREAD

**Issue by numical** [ampedandwired/html-webpack-plugin#283]
The [examples](https://github.com/ampedandwired/html-webpack-plugin/tree/master/examples/inline) show one way of doing inline styles using a jade template.
There is now a [plugin](https://github.com/numical/style-ext-html-webpack-plugin) which offers an alternative approach.
All feedback/bugs/etc. most welcome.
Hope it helps.

**Comment by jantimon** [comment]
Cool 👍

**Comment by numical** [comment]
No sense leaving this open as an issue.
