### ISSUE TITLE
Prepend paths with forward slash

### ISSUE THREAD

**Issue by egeriis** [ampedandwired/html-webpack-plugin#284]
We're experiencing an issue which is a conflict of using deep URLs and a single index.html which serves all routes. The issue is that html-webpack-plugin inject the JS and CSS files into `index.html` like this:

```
<script src="vendor.fb23ccc1786d9f1e6f8f.js"></script>
```

We've set publicPath to `/`, but this seems to be ignored. It works fine in the cases where we have an application serves in a sub-folder, e.g. `/admin/`.

Is there a solution to this or how would we go about solving this?

We're looking for output similar to below or similar solution.

```
<script src="/vendor.fb23ccc1786d9f1e6f8f.js"></script>
```

**Comment by jantimon** [comment]
The public path should be added:

https://github.com/ampedandwired/html-webpack-plugin/blob/master/index.js#L388

**Comment by egeriis** [comment]
@jantimon What do you mean? That it's supposed to work?

**Comment by jantimon** [comment]
Yep :)

**Comment by egeriis** [comment]
@jantimon Alright. That is great news and bad news. Means I didn't find the cause :) Onwards and upwards. Thank you for taking the time to answer.

**Comment by milushov** [comment]
@jantimon use canonical links PLEEEEASE

(just type `y` letter on the page)
