### ISSUE TITLE
How to remove the original script and link-css label in template ?

### ISSUE THREAD

**Issue by yuyang041060120** [ampedandwired/html-webpack-plugin#285]

**Comment by jantimon** [comment]
Turn inject off

**Comment by yuyang041060120** [comment]
@jantimon I want to remove the exiting script label.

**Comment by jantimon** [comment]
Label?

**Comment by yuyang041060120** [comment]
`template:'index.html'`
```html
<!DOCTYPE html>
<html ng-app="myApp">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<script src="node_modules/angular/angular.js"></script>
</body>
</html>
```

`after run webpack `

```html
<!DOCTYPE html>
<html ng-app="myApp">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="styles.f92a3de1b573b7c29adaf9288cc96b59.css" rel="stylesheet"></head>
<body>

<script src="node_modules/angular/angular.js"></script>
<script src="vendor.14625f75c4c48f41dde8.js"></script>
<script src="bundle.57f35d8c1619b36c661b.js"></script>
</body>
</html>
```

I want to remove the first script which exits.

**Comment by jantimon** [comment]
I am sorry I really don't understand the problem. Remove it from index.html ?

**Comment by yuyang041060120** [comment]
yes

**Comment by yuyang041060120** [comment]
@jantimon yes

**Comment by jantimon** [comment]
Please try stackoverflow.com maybe someone might help you there :)

**Comment by yuyang041060120** [comment]
@jantimon Can you get my point?

**Comment by jantimon** [comment]
no sry I really don't understand the issue

**Comment by Catlite91** [comment]
use templateContent
1.add the special attribute to the script what you want to remove. such as
 <script **data-debug** src="node_modules/angular/angular.js"></script>
2.read the file 'index.html' then use cheerio to remove $('[data-debug]').remove()
3.return the result to templateContent

**Comment by Catlite91** [comment]
But I don't think this is a good way to resolve the problem.
Have you fixed the problem, any good idea?

**Comment by jantimon** [comment]
Why don't you just use two different templates?

**Comment by Catlite91** [comment]
i think that is an easy way to understand and make two entries may make me
confuse.
2016年4月18日 下午6:52，"Jan Nicklas" <notifications@github.com>写道：

**Comment by cnweibo** [comment]
@Catlite91 , you can use gulp-inject, that do exactly what you want. 
Currently, i am asking @jantimon  with an issue https://github.com/ampedandwired/html-webpack-plugin/issues/388 , how to customize where to inject the js and css assets into the final html if the final html is only a partial and have no head, body tag? That comes from gulp-inject pattern. We specify  in the template, gulp-inject will inject js there.

**Comment by Catlite91** [comment]
But... How to remove a script?

**Comment by cnweibo** [comment]
I use gulp.src('') with a dummy source file to workaround it:)

**Comment by cnweibo** [comment]
@Catlite91 , another option to remove a script is to use gulp-inject transform option, you define a function to return ''
