### ISSUE TITLE
can i add a 'path' option in the plugin?

### ISSUE THREAD

**Issue by Wellaiyo** [ampedandwired/html-webpack-plugin#286]
Like this:

    new HtmlWebpackPlugin({
        path: './scripts',       // based on output.publicPath
        filename: '../index.html',
        template: './static/index.html',
        inject: 'body'
    })

I made a change in the 350th line of index.js, and it works.

    ? path.resolve(compilation.mainTemplate.getPublicPath({hash: webpackStatsJson.hash}), self.options.path || '')

**Comment by jantimon** [comment]
Why can't you use the public path or use a custom template?
