### ISSUE TITLE
Pass additional variables into custom template

### ISSUE THREAD

**Issue by FredyC** [ampedandwired/html-webpack-plugin#287]
My use case is related to closed #31 where @Ciantic wanted to add React script as external asset. I want to do a same, but with custom ThreeJS build. Normally using commons chunk would be just fine, however after I tried to apply UglifyJS, it got broken for some reason. So I need to externalize this and have it served separately.

I am sure that allowing to pass additional variables into template from within webpack configuration might be generally handy for various other cases. Or ideally be more specific and allow specify list of extra scripts that should be added along the compiled assets.

**Comment by jantimon** [comment]
That is already possible - you can pass any information like the just like the `title` to the template

**Comment by FredyC** [comment]
@jantimon Can you show me some small example? I am not sure how do you mean it.

**Comment by jantimon** [comment]
https://github.com/ampedandwired/html-webpack-plugin/blob/master/examples/custom-template/template.html#L5

**Comment by FredyC** [comment]
Ahh, so whole `options` object is just accessible from the template? Alright, that should be enough. Thanks!

**Comment by jantimon** [comment]
Correct 👍

**Comment by c0debreaker** [comment]
I tried this by adding app property but I'm getting an error during webpack build

```
    new HtmlWebpackPlugin({
      app: 'myapp',
      title: 'Example title',
      favicon: 'assets/images/favicon.ico',
      inject: 'body',
      template: path.resolve(__dirname, 'node_modules', 'webapps', 'assets', 'partials', 'index.html'),
      chunks: ['myapp', 'vendor']
    })
```

The error I'm getting is 
```
ERROR in Template execution failed: ReferenceError: myapp is not defined
ERROR in   ReferenceError: myapp is not defined
```

then on the template, I have this code
```
    <script>
      var myapp = <%= htmlWebpackPlugin.options.myapp %>
   </script>
```
