### ISSUE TITLE
Keep getting "Uncaught TypeError: Cannot read property 'replaceChild' of null".

### ISSUE THREAD

**Issue by tetsushiomi** [ampedandwired/html-webpack-plugin#288]
Original version of index.html(not minified) works without problem, but after I minify index.html with html-webpack-plugin, I keep getting "Uncaught TypeError: Cannot read property 'replaceChild' of null". Note that my web app is working well regardless, but this error is driving me crazy.

Part of my webpack config:

>       new HtmlWebpackPlugin({
        template: 'app/main.html',
        filename: 'index.html',
        minify: {
          collapseWhitespace: true,
          removeComments: true,
          removeRedundantAttributes: true,
          removeScriptTypeAttributes: true,
          removeStyleLinkTypeAttributes: true,
        },
      })

**Comment by tetsushiomi** [comment]
I found the problem. 

Every time I minify the html file, it produces two script tags, which is strange because there is only one script tag in the original html file.

Original one only has `<script src="./app.js"></script>` while the minified version produces `<script src="./app.js"></script><script src="app.js"></script>`.

There is an redundant `<script src="app.js"></script>`.

Any idea how to solve this?

**Comment by tetsushiomi** [comment]
I solved the problem.


Docs:
> The plugin will generate an HTML5 file for you that includes all your webpack bundles in the body using script tags. 

So, I can remove `<script` `src="./app.js"></script>` from template.

**Comment by jantimon** [comment]
Yes you could also set `inject:false` if you want to add them by yourself.
