### ISSUE TITLE
Using template: "TypeError: First argument needs to be a number, array or string."

### ISSUE THREAD

**Issue by mraxus** [ampedandwired/html-webpack-plugin#29]
Hi,

Just started working with webpack and still trying to wrap my head around a lot of things. However, this plugin seems pretty straight forward. But I am trying to convert a gulp-heavy project to a more native react/webpack version but taking stuff small pieces at a time. That includes trying to get a predefined template to be used by this plugin, but when I use the 'template' options, it fails:

    $ webpack --progress --colors --watch -d
     95% emit
    buffer.js:188
            throw new TypeError('First argument needs to be a number, ' +
                  ^
    TypeError: First argument needs to be a number, array or string.
        at new Buffer (buffer.js:188:15)
        at Tapable.writeOut (/Users/wrapp/go/src/wrappmin/node_modules/webpack/lib/Compiler.js:247:16)
        at Tapable.<anonymous> (/Users/wrapp/go/src/wrappmin/node_modules/webpack/lib/Compiler.js:236:20)
        at /Users/wrapp/go/src/wrappmin/node_modules/webpack/node_modules/async/lib/async.js:125:13
        at Array.forEach (native)
        at _each (/Users/wrapp/go/src/wrappmin/node_modules/webpack/node_modules/async/lib/async.js:46:24)
        at Object.async.each (/Users/wrapp/go/src/wrappmin/node_modules/webpack/node_modules/async/lib/async.js:124:9)
        at Tapable.emitFiles (/Users/wrapp/go/src/wrappmin/node_modules/webpack/lib/Compiler.js:225:20)
        at /Users/wrapp/go/src/wrappmin/node_modules/webpack/node_modules/mkdirp/index.js:29:20
        at Object.oncomplete (fs.js:108:15)

webpack.config.js:

    webpack = require('webpack');
	var HtmlWebpackPlugin = require("html-webpack-plugin");
	
	module.exports = {
		entry: './src/app.jsx',
		output: {
	        path: './build',
	        public: '/',
			filename: 'bundle.js'
		},
		plugins: [
			new HtmlWebpackPlugin({
				template: './src/index.html'
			})
			//new webpack.optimize.DedupePlugin(),
			//new webpack.optimize.OccurenceOrderPlugin(),
			//new webpack.optimize.UglifyJsPlugin()
		],
		module: {
			loaders: [
				{
					//tell webpack to use jsx-loader for all *.jsx files
					test: /\.jsx?$/,
					loader: 'jsx-loader?insertPragma=React.DOM&harmony'
				},
				{
					test: /\.css$/,
					loader: 'style!css'
				},
				{
					test: /\.json$/,
					loader:'json-loader'
				}
			]
		},
		resolve: {
			extensions: ['', '.js', '.jsx', '.json', '.css']
		}
	};

template:

    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="utf-8">
            <meta http-equiv="X-UA-Compatible" content="IE=edge">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css"/>
            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css"/>
            <link rel="stylesheet" href="https://d3ddaigw5mx5fo.cloudfront.net/next/res11/css/fonts.css"/>
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.3/leaflet.css" />
            <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.3/leaflet.js"></script>
            <script src="{%=o.htmlWebpackPlugin.files.chunks.head.entry%}"></script>
        </head>
        <body>
            <script src="{%=o.htmlWebpackPlugin.files.chunks.main.entry%}"></script>
        </body>
    </html>

As you might understand I want to replace the CDN stuff as well but that I will do when I get the current issue solved.

Would love to get some help with this.

Cheers
--Marcus

**Comment by mraxus** [comment]
Well, after some more digging, I found your template example which made more sense. I think there could be some clearer explanation in the docs.

**Comment by jantimon** [comment]
Would happy to merge a pull request for a better readme

**Comment by Shershnev-AV** [comment]
@mraxus, I've the same problem and I don't understand how to set variable `o`.
Can you help me?

**Comment by bebraw** [comment]
Just bumped into this. I suppose it would be enough if you just replaced README example with `default_index.html` content. There's something wrong with the current example (yields error at Webpack).

**Comment by jantimon** [comment]
Its already corrected in the 1.4. release.
