### ISSUE TITLE
Using templates in non-standard locations

### ISSUE THREAD

**Issue by icfantv** [ampedandwired/html-webpack-plugin#292]
This is a usage question so if better served by using StackOverflow, please let me know.

My project is still using a main.jsp page for the main webpage so I want my `template` to point to `path/to/main.jsp` but the build is barfing in lodash with the following:

```
ERROR in   Error: Child compilation failed:
  Module build failed: SyntaxError: missing ) after argument list
  
  - Function
  
  - lodash.js:13902 
    [sia-web-template]/[html-webpack-plugin]/[lodash]/lodash.js:13902:16
  
  - lodash.js:431 apply
    [sia-web-template]/[html-webpack-plugin]/[lodash]/lodash.js:431:27
  
  - lodash.js:14295 
    [sia-web-template]/[html-webpack-plugin]/[lodash]/lodash.js:14295:16
  
  - lodash.js:9873 
    [sia-web-template]/[html-webpack-plugin]/[lodash]/lodash.js:9873:31
  
  - lodash.js:13901 Function.template
    [sia-web-template]/[html-webpack-plugin]/[lodash]/lodash.js:13901:20
```
I think it may be trying to parse the contents of the file...?

If i remove `template` and just keep `inject: 'body'` (there's nothing else present in the config object) the build succeeds, but obviously is not using my template anymore.  Any ideas here?  Is there a better solution that still let's me use cache busting?

The second issue is going to be that `filename` is relative to webpack's 'output.path' config property.  I'm going to need it in a different directory.  Is my best bet for that to use the copy plugin assuming I can get the first part working?

**Comment by icfantv** [comment]
Additional research seems to indicate that at the very least, the parser used by this plugin is having issues with the JSP syntax used elsewhere in the page.  E.g., JSP pages use `<%` for its own syntax.  Removing that from my JSP page temporarily moves beyond the above error and gives another/different one.

**Comment by icfantv** [comment]
turns out, i need the `!raw` loader in front of my JSP page entry for the template.  All working.....closing.

**Comment by derwaldgeist** [comment]
Hey, I'm having the same problem in a project where the customer requires a JSP file as an entry point. Where exactly do I have to add the `!raw` loader?

**Comment by icfantv** [comment]
@derwaldgeist, this was for Webpack 1.13.1 so YMMV, but here's the relevant code snippet:

```javascript
new HtmlWebpackPlugin({
  inject: 'body',
  template: 'raw!./src/main/webapp/WEB-INF/jsp/main-template.jsp'
})
```

Viel Glück
