### ISSUE TITLE
How can I include "Critical / above the fold" CSS to the <head> ?

### ISSUE THREAD

**Issue by JustFly1984** [ampedandwired/html-webpack-plugin#294]
I have several entry points, and I have "*.ejs" template for each of them.
So I have HTML-webpack plugin instance for all of them.

The problem is: I need to inline Critical css to each of this templates by hand, and change all of them.

I think this should be automated with your plugin.

**Comment by numical** [comment]
Maybe [style-ext-html-webpack-plugin](https://github.com/numical/style-ext-html-webpack-plugin) might help.

**Comment by jantimon** [comment]
Inline all files called *.critical.css:

```
module: {
  loaders: [
    { test: /^(?!.*\.critical).*\.css$/, loader: 'style-loader!css-loader' }
    { test: /\.critical\.css$/, loader: StyleExtHtmlWebpackPlugin.inline() }
  ]           
},
plugins: [
  new HtmlWebpackPlugin(),
  new StyleExtHtmlWebpackPlugin()
]  
```

**Comment by JustFly1984** [comment]
Thank you very much, your advise has been very helpful!

**Comment by jantimon** [comment]
Trending right now https://twitter.com/smashingmag/status/721908493289021440
