### ISSUE TITLE
Plugin conflicts with ProvidePlugin when providing lodash

### ISSUE THREAD

**Issue by Fire-Dragon-DoL** [ampedandwired/html-webpack-plugin#297]
Seems weird but if you expose "_": "lodash" with ProvidePlugin, `HtmlWebpackPlugin` fails with compiler errors (will tell error tomorrow, don't have it right now).

**Comment by Fire-Dragon-DoL** [comment]
I found the reason, basically it uses the version you are using in your frontend. It also uses the loaders that you use on the frontend, so I was using the expose loader/script loader and it was conflicting with the internal lodash when provided with ProvidePlugin, not sure if that can be of any help

**Comment by aledoroshenko** [comment]
I think i have something similar - trying to use ProvidePlugin and have errors with html-webpack-template. I have this in webpack config:

```
...
module: {
    loaders: {
        ...
        {
            test: require.resolve('lodash'),
            loader: 'expose?_'
        }
    }
}

...

plugins: [
        new webpack.ProvidePlugin({
            _: path.resolve(__dirname, 'src', 'lodashMixins.js')
        }),
        new HtmlWebpackPlugin({
            inject: false,
            template: webpackTemplate,
            appMountId: 'app'
        })
    ],

...

And got this errors:

![](https://i.imgur.com/Salildz.png)

**Comment by jantimon** [comment]
Maybe we could require lodash using `require('!!lodash')` to ignore loaders..
Would you like to create pull request?

**Comment by aledoroshenko** [comment]
I would like to, but i don't get where to look at :) I've tried to use that !! in requires here and there in plugin folder - no luck.
