### ISSUE TITLE
Error trying to pass querystring params to html loader

### ISSUE THREAD

**Issue by fabiosussetto** [ampedandwired/html-webpack-plugin#301]
Hi, I got into this issue while trying to pass some querystring options to the html loader for my template file:

```
new HtmlWebpackPlugin({
            template: '!html?html?attrs[]=img:src&attrs[]=link:href!./src/index_fr-fr.html',
            inject: true,
            filename: '../templates/index_fr-fr.html'
        }),
```
The html loader supports this syntax to require additional tag attributes. In my case I needed to extract the mobile icons using the file loader.

Compilation errors with this misleading message:
```
RROR in   Error: Child compilation failed:
  Entry module not found: Error: Cannot resolve 'file' or 'directory' /Users/fabio.sussetto/Code/manhattan_web/src/client/  html in /Users/fabio.sussetto/Code/manhattan_web/src/client:
  Error: Cannot resolve 'file' or 'directory' /Users/fabio.sussetto/Code/manhattan_web/src/client/html in /Users/fabio.sus  setto/Code/manhattan_web/src/client

  - compiler.js:78
    [client]/[html-webpack-plugin]/lib/compiler.js:78:16

  - Compiler.js:214 Compiler.<anonymous>
    [client]/[webpack]/lib/Compiler.js:214:10

  - Compiler.js:403
    [client]/[webpack]/lib/Compiler.js:403:12

  - Tapable.js:67 Compiler.next
    [client]/[tapable]/lib/Tapable.js:67:11

  - CachePlugin.js:40 Compiler.<anonymous>
    [client]/[webpack]/lib/CachePlugin.js:40:4

  - Tapable.js:71 Compiler.applyPluginsAsync
    [client]/[tapable]/lib/Tapable.js:71:13

  - Compiler.js:400 Compiler.<anonymous>
    [client]/[webpack]/lib/Compiler.js:400:9

  - Compilation.js:577 Compilation.<anonymous>
    [client]/[webpack]/lib/Compilation.js:577:13

  - Tapable.js:60 Compilation.applyPluginsAsync
    [client]/[tapable]/lib/Tapable.js:60:69

  - Compilation.js:572 Compilation.<anonymous>
    [client]/[webpack]/lib/Compilation.js:572:10

  - Tapable.js:60 Compilation.applyPluginsAsync
    [client]/[tapable]/lib/Tapable.js:60:69

  - Compilation.js:567 Compilation.<anonymous>
    [client]/[webpack]/lib/Compilation.js:567:9

  - Tapable.js:60 Compilation.applyPluginsAsync
    [client]/[tapable]/lib/Tapable.js:60:69

  - Compilation.js:563 Compilation.<anonymous>
    [client]/[webpack]/lib/Compilation.js:563:8

  - Tapable.js:60 Compilation.applyPluginsAsync
    [client]/[tapable]/lib/Tapable.js:60:69

  - Compilation.js:525 Compilation.seal
    [client]/[webpack]/lib/Compilation.js:525:7

  - Compiler.js:397 Compiler.<anonymous>
    [client]/[webpack]/lib/Compiler.js:397:15

  - Tapable.js:103
    [client]/[tapable]/lib/Tapable.js:103:11

  - Compilation.js:445 Compilation.<anonymous>
    [client]/[webpack]/lib/Compilation.js:445:10

  - Compilation.js:344 Compilation.errorAndCallback
    [client]/[webpack]/lib/Compilation.js:344:3

  - Compilation.js:358 Compilation.<anonymous>
    [client]/[webpack]/lib/Compilation.js:358:11

  - NormalModuleFactory.js:29 onDoneResolving
    [client]/[webpack]/lib/NormalModuleFactory.js:29:20

  - NormalModuleFactory.js:85
    [client]/[webpack]/lib/NormalModuleFactory.js:85:20

  - async.js:726
    [client]/[async]/lib/async.js:726:13

  - async.js:52
    [client]/[async]/lib/async.js:52:16

  - async.js:241 done
    [client]/[async]/lib/async.js:241:17

  - async.js:44
    [client]/[async]/lib/async.js:44:16

  - async.js:723
    [client]/[async]/lib/async.js:723:17

  - async.js:167
    [client]/[async]/lib/async.js:167:37

  - async.js:52
    [client]/[async]/lib/async.js:52:16
```
After digging into your code I suspect the culprit can be this regex here:
https://github.com/ampedandwired/html-webpack-plugin/blob/master/index.js#L532
```
// Resolve template path
  return template.replace(
    /(\!)([^\/\\][^\!\?]+|[^\/\\!?])($|\?.+$)/,
    function (match, prefix, filepath, postfix) {
      return prefix + path.resolve(filepath) + postfix;
    });
```
which doesn't seem to support querystring params for the loader.

My workaround was to just add another entry in my module.loaders config for this specific file, where I can pass my options as normal.

Thanks!

**Comment by jantimon** [comment]
It supports querystrings but your configuration seems broken why do you have two querystrings?

**Comment by ccorcos** [comment]
I have the same issue.

this works:

```
        template: `!html!${config.html}`,
```

this doesnt

```
        template: `!html?interpolate!${config.html}`,
```

along with the traceback above:

```
Child html-webpack-plugin for "index.html":

    ERROR in Entry module not found: Error: Cannot resolve 'file' or 'directory' /Users/chetcorcos/code/web-ux/skeleton/html in /Users/chetcorcos/code/web-ux/skeleton
webpack: bundle is now VALID.
```

**Comment by jantimon** [comment]
Try `!!html` instead of `!html`

**Comment by ccorcos** [comment]
this works

        template: `!!html!${config.html}`,

this doesn

        template: `!!html?interpolate!${config.html}`,

**Comment by jantimon** [comment]
Looks like a loader issue

**Comment by ccorcos** [comment]
yeah... :(

**Comment by Bnaya** [comment]
I have the same issue
this plugin and html loader won't play nicely when interpolate is on.

**Comment by ccorcos** [comment]
I have a little workaround you can use though. Its pretty simple.

I'm using the html plugin for doing all of the assets stuff still

      new HtmlWebpackPlugin({
        template: `!html!${config.html}`,
        inject: 'body',
      }),

And then I have another plugin that does the injection separately

      // inject development configuration
      new ConfigureHtml(config.inject)

And heres the plugin definition.

    // use the html webpack plugin events to inject paramters into index.html
    // https://github.com/ampedandwired/html-webpack-plugin#events
    function ConfigureHtml(tags) {
      this.tags = tags || {}
    }

    ConfigureHtml.prototype.apply = function(compiler) {
      compiler.plugin('compilation', (compilation) => {
        compilation.plugin('html-webpack-plugin-before-html-processing', (htmlPluginData, callback) => {
          // for every key, we'll replace with a stringified version of the value
          var str = htmlPluginData.html
          Object.keys(this.tags).forEach((key) => {
            str = str.split(key).join(this.tags[key])
          })
          htmlPluginData.html = str
          callback(null, htmlPluginData);
        });
      });
    }
