### ISSUE TITLE
Wrong bundle order when CommonsChunkPlugin with extra bundle is used

### ISSUE THREAD

**Issue by mostr** [ampedandwired/html-webpack-plugin#302]
Whe using CommonsChunkPlugins trick to get correct bundle hashes, bundles are sorted incorrectly (https://github.com/webpack/webpack/issues/2378). Looks like passing `chunksSortMode: 'dependency'` works, but I guess sorting by id (default) should work too as ids are provided by webpack are correct.

Probably the `id` sort function in `chunksorter.js` might be changed to 
```
module.exports.id = function (chunks) {
  return chunks.sort(function orderEntryLast (a, b) {
    if (a.entry !== b.entry) {
      return b.entry ? 1 : -1;
    } else {
      return a.id - b.id; // <--- change from b.id - a.id 
    }
  });
};
```

This change really sorts them in correct order when `entry` property doesn't differ

**Comment by jantimon** [comment]
Sort by id is a little bit broken for webpack 1.
For webpack 2 ´chunksSortMode: 'dependency'` is already the default sorting mode
