### ISSUE TITLE
Jade was renamed to pug

### ISSUE THREAD

**Issue by Arelav** [ampedandwired/html-webpack-plugin#304]
According to copyright issue (https://github.com/pugjs/pug/issues/2184) Jade was renamed to pug.
And npm packages was renamed too.
jade => pug
jade-html-loader => pug-html-loader

**Comment by jantimon** [comment]
would you be so kind and create a pull request?

**Comment by jantimon** [comment]
I am using the jade loader not the jade html loader

**Comment by Arelav** [comment]
pug-loader was resolved also all I need.
