### ISSUE TITLE
the version of webpack which you are using is too old

### ISSUE THREAD

**Issue by yuyichen** [ampedandwired/html-webpack-plugin#306]
when I try to use this plugin,the console says
>Cannot find module webpack/lib/node/NodeTemplatePlugin

and I found that some files no longer exist  in webpack of latest versions,please check that

**Comment by jantimon** [comment]
Which version do you use?

**Comment by jantimon** [comment]
Works fine with the newest webpack 1 & 2 versions https://travis-ci.org/ampedandwired/html-webpack-plugin/builds/125625610
