### ISSUE TITLE
Failure with "chunks" option & hot loading

### ISSUE THREAD

**Issue by MoOx** [ampedandwired/html-webpack-plugin#308]
I have used the "chunks" option with the name of my chunck and `webpack-dev-server --inline --hot`.
When a hot loading is pushed and fail to do a live update, the page is fully refreshed but the html only contains the "{hash}.hot-update.js" in the body. So the app cannot start.

**Comment by jantimon** [comment]
Would #281 solve this for you?

**Comment by MoOx** [comment]
I just tested this PR and it is definitely solving my issue.

**Comment by jantimon** [comment]
Cool 👍 I'll merge it as soon as I wrote the test. (should be this week)
