### ISSUE TITLE
Safari 9.1.1. Issue - "A problem repeatedly occurred"

### ISSUE THREAD

**Issue by pburtchaell** [ampedandwired/html-webpack-plugin#309]
Earlier this month I noticed an issue with some websites I built HTML for using this plugin: when landed in Safari, the page is reloaded several times and finally, shows "A problem repeatedly occurred." 

![screen shot 2016-04-27 at 10 32 14 am](https://cloud.githubusercontent.com/assets/3857324/14858295/21caa632-0c65-11e6-9949-402b6089b4c4.png)

Initially, I thought it was an issue with permissions from AWS S3 or an issue with my code. However, after digging a bit further, I discovered something rather alarming: if you use `<script src="/app.js"></script>` the page reloads. If you use `<script type="text/javascript" src="/app.js"></script>`, the page loads as expected. Considering it is [a part of the HTML5 standard](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script) to exclude the `type` attribute, I am wondering... is this actually a Safari bug or am I missing something here? Is anyone else having this issue?

Note, this also occurs when I do not use this plugin (such as when I am using local development server). However, considering the script tag is central to this plugin, I figured I'd make an issue here to see if anyone else encountered this.

Edit, some examples of websites:
- http://pburtchaell.com
- http://lawnchair.io
- http://segment.social

**Comment by jantimon** [comment]
You are right - this has to be fixed.
If you have time to fix it please update it here: https://github.com/ampedandwired/html-webpack-plugin/blob/master/index.js#L441

Otherwise I will do it myself in the next days.

**Comment by pburtchaell** [comment]
PR opened in #311.

**Comment by jantimon** [comment]
Closed because of #311
