### ISSUE TITLE
webpack external script tags, automatically

### ISSUE THREAD

**Issue by Ciantic** [ampedandwired/html-webpack-plugin#31]
Suppose one uses react or jquery, then it's good idea (sometimes) to use this [`externals` feature of webpack](http://webpack.github.io/docs/library-and-externals.html):

**webpack.config.js**
```
module.exports = {
    // ...
    externals: {
        "react" : "React"
    }
};
```

For instance, my index.js went from *640kB* to *4kB*. With that one line! Yes I know I must include a `<script />` tag for react & assume React global does not clash. But it's nicer way sometimes.

It would be cool if HtmlWebpackPlugin had a way to inject those externals almost automatically. Even this would be a improvement:

**package.json**
```
{
  "dependencies": {
    "react": "0.13.2"
  },
  "external-scripts" : {
    "react" : "https://cdnjs.cloudflare.com/ajax/libs/react/0.13.2/react.min.js"
  }
}

```

Notice that I intentionally would like to put my external script URLs in `package.json` because it includes version numbers already.

**Comment by Ciantic** [comment]
I made a world ugliest workaround to inject external scripts:

```
var HtmlWebpackPlugin = require('html-webpack-plugin')
var html = new HtmlWebpackPlugin();
html.htmlWebpackPluginAssets = function () {
    var assets = HtmlWebpackPlugin.prototype.htmlWebpackPluginAssets.apply(this, arguments);
    assets.chunks['react'] = {
        id : -1,
        entry: 'https://fb.me/react-0.13.2.min.js'
    };
    var i = assets.chunks['index'];
    delete assets.chunks['index'];
    assets.chunks['index'] = i;
    return assets;
}
module.exports = {
    // ...
    entry: {
        index: ['./index.js']
    },
    output: {
        path: './build/',
        filename: './[name].js'
    },
    plugins: [
        html
    ],
    externals: {
        "react" : "React"
    }
};
```

**Comment by jantimon** [comment]
Why don't you use the common chunks plugin?

http://webpack.github.io/docs/code-splitting.html#split-app-and-vendor-code

**Comment by thakerng** [comment]
At some point if I have a vast vendors code to run in common chunk, it takes a long time to recompile but I think by natural of vendor code is always static that shouldn't be compiled every time when I run with Webpack I think to work with external feature should be better

**Comment by SteveVanOpstal** [comment]
@jantimon The common chunks plugin does not solve this issue.
What if you want to use a cdn? splitting your code into app and vendor does not really help with that.
