### ISSUE TITLE
Error when processing BannerPlugin Raw

### ISSUE THREAD

**Issue by TheMcMurder** [ampedandwired/html-webpack-plugin#312]
In an effort to include some simple build information in the deployed code, I generate an javascript object to include in the banner. 

I realized that the html-webpack-plugin was parsing the raw input and throwing an error. So for example...

````javascript
webpackConfig.plugins = [
  new webpack.DefinePlugin(config.globals),
  new webpack.BannerPlugin(getBanner(), {raw: true}),
  new HtmlWebpackPlugin({
    showErrors: true,
    template: paths.client('index.html'),
    hash: false,
    favicon: paths.client('static/favicon.ico'),
    filename: 'index.html',
    inject: 'body',
    minify: {
      collapseWhitespace: false
    }
  })
]

function getBanner() {
  return "var thing = 'test'"
}
````

I've simplified greatly I'm actually including an object that contains the buildNumber, and last commit so I can ensure that I'm delivering the code I intend to deliver.

I'm getting the following errors with the above code:

````
ERROR in   TypeError: "test" is not a function
  
  - index.html:3 
    /Users/<REDACTED>/src/index.html:3:10
  
  - index.js:210 HtmlWebpackPlugin.evaluateCompilationResult
    [fraud-app]/[html-webpack-plugin]/index.js:210:26
  
  - index.js:107 
    [fraud-app]/[html-webpack-plugin]/index.js:107:21
  
  - util.js:16 tryCatcher
    [fraud-app]/[bluebird]/js/release/util.js:16:23
  
  - promise.js:502 Promise._settlePromiseFromHandler
    [fraud-app]/[bluebird]/js/release/promise.js:502:31
  
  - promise.js:559 Promise._settlePromise
    [fraud-app]/[bluebird]/js/release/promise.js:559:18
  
  - promise.js:604 Promise._settlePromise0
    [fraud-app]/[bluebird]/js/release/promise.js:604:10
  
  - promise.js:683 Promise._settlePromises
    [fraud-app]/[bluebird]/js/release/promise.js:683:18
  
  - promise.js:628 Promise._fulfill
    [fraud-app]/[bluebird]/js/release/promise.js:628:18
  
  - promise.js:445 Promise._resolveCallback
    [fraud-app]/[bluebird]/js/release/promise.js:445:14
````

Is there a way I can get the plugin to ignore my raw banner?

**Comment by TheMcMurder** [comment]
I recognize that this is probably non-standard. I really appreciate your help!

**Comment by jantimon** [comment]
Probably you would have to use another loader e.g. the underscore-template-loader for the template.

**Comment by skyiea** [comment]
Have the same issue.
@jantimon Can you elaborate why it is a problem of loader? I'm using *pug-loader*, and it worked swell in combination with this plugin, until I've tried to prepend custom JS code (as author did). I don't think that loader evaluates JS code and throws this error, is he?
