### ISSUE TITLE
There is a conflict between html-webpack-plugin && ngmin-webpack-plugin !

### ISSUE THREAD

**Issue by harole** [ampedandwired/html-webpack-plugin#317]
When I was using html-webpack-plugin and ngmin-webpack-plugin at the same time, there is an error.
Anyone knows the reason, please help me. Thanks!

code:
![image](https://cloud.githubusercontent.com/assets/4095799/15043664/7366c316-1301-11e6-8157-3ee879a74216.png)

error:
![image](https://cloud.githubusercontent.com/assets/4095799/15043574/acb3a1f8-1300-11e6-92c5-fb3f877da68e.png)

**Comment by jantimon** [comment]
Ngmin is deprecated - please use https://www.npmjs.com/package/ng-annotate-loader

**Comment by harole** [comment]
Thanks！ It is well done for ng-annotate-webpack-plugin.

**Comment by jantimon** [comment]
The loader is faster
