### ISSUE TITLE
IN HtmlWebpackPlugin config [name] does not work but [hash] does work

### ISSUE THREAD

**Issue by NabilKhan** [ampedandwired/html-webpack-plugin#318]
'use strict';

const path = require('path');

const Webpack = require('webpack');
const HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = {
  debug: true,
  entry: {
        home:  'home.jsx',
        about: 'about.jsx'
  },
  output: {
    path:       '/',
    publicPath: '/',
    filename:  '/[name]-bundle.js',
  },
  module: {
    loaders: [
      {
        test:     /\.jsx?$/, 
        exclude:  /node_modules/, 
        loader:   'babel-loader',
        query: {
            cacheDirectory: true,
            presets:        ['es2015', 'react']
        }
      }
    ]
  },
  plugins: [
      new HtmlWebpackPlugin({ 
        template: 'build/index.ejs',
        filename: 'bunldes/[name].html',
        inject: 'body',
        appMountId: 'app', 
      })
  ]
};

**Comment by NabilKhan** [comment]
this outputs file 0.html instead of about.html and home.html

**Comment by jantimon** [comment]
Generating file per entry is not supported. You could loop over your entries and add a instance per entry

**Comment by rdandnayak** [comment]
can this support be added?

**Comment by rdandnayak** [comment]
what exactly you mean by "You could loop over your entries and add a instance per entry"

**Comment by smcelhinney** [comment]
Presume something like this would work for you.. 

```
const entry = {
  'foo': './foo',
  'bar': '.bar'
};

const plugins = [];

Object.keys(entry).forEach(e => {
  const hwp = new HtmlWebpackPlugin({
    filename: `${e}.html`
  });
  plugins.push(hwp);
});

module.exports = {entry, plugins};
```
