### ISSUE TITLE
Conflict with thymeleaf template syntax.

### ISSUE THREAD

**Issue by luozhihua** [ampedandwired/html-webpack-plugin#322]
This is my template for html-webpack-plugin:
```html
<!DOCTYPE html>
<html xmlns:th="http://www.thymeleaf.org" lang="en">
<head>
    <title>${titleByThymeleaf}</title>

    <% for (var chunk in htmlWebpackPlugin.files.chunks) { %>
    <script src="<%= htmlWebpackPlugin.files.chunks[chunk].entry %>"></script>
    <% } %>
</head>
<body></body>
</html>
```
When I run ```webpack -p```, webpack throw out an error:
```shell
ERROR in Template execution failed: ReferenceError: titleByThymeleaf is not defined.
```
How did I setting html-webpack-plugin than it can ignore `${...}` .

**Comment by jantimon** [comment]
This plugin comes with a fallback loader - if you don't specify a loader for your template it will kick in.

The fallback loader won't work with your syntax.

**Comment by florian-bd** [comment]
In case someone is interested:
Use the ejs loader, then in your webpack config, redefine the interpolate property for ejs since it tries to parse ${ }

`ejsLoader: {
            interpolate : /{{([\s\S]+?)}}/g,
        }`

for example

**Comment by erichstark** [comment]
hello @luozhihua, how do you handle th:replace/include with webpack?

**Comment by Leon9429** [comment]
@luozhihua did you reslove the problem about ${...} ?

**Comment by luozhihua** [comment]
@Leon9429 I wrote Thymeleaf variables in template use `@@@@{titleByThymeleaf}`， and replace `@@@@{titleByThymeleaf}` back to `${titleByThymeleaf}` after webpack build. 

*0*

**Comment by pensz** [comment]
you can set 
```
loader: 'ejs-loader',
query: {
  interpolate: '<%=([\\s\\S]+?)%>'
}
```

to make lodash disable reEsTemplate.
