### ISSUE TITLE
Dynamic routes not parsed

### ISSUE THREAD

**Issue by raypatterson** [ampedandwired/html-webpack-plugin#325]
Hi,

I have a configuration using [`underscore-template-loader`](https://github.com/emaphp/underscore-template-loader) and I cannot seem to get it to parse any routes that are created dynamically with this plugin.

By that I mean, if I create a non-dynamic image tag:

```html
<img src="/test-1.jpg" />
```

The `file-loader` discovers, loads and emits the asset, however if I create the tag like so:

```html
<img src="<%= htmlWebpackPlugin.image.src %>" />
```

The asset is not discovered by the file loader.

As an aside, the following works:

```html
<img src="<%= require('/test-1.jpg') %>" />
```

But using a variable produces an error:

```html
<img src="<%= require(htmlWebpackPlugin.image.src) %>" />
```

My configuration for the template loader looks like:

```javascript
webpackConfig.module.loaders.push({
	test: /\.ejs$/i,
	loader: 'underscore-template',
	query: {
		root: cfg.dir.source,
		parseDynamicRoutes: true,
		attributes: [
			'img:src'
		]
	}
});
```

A post loader will not work as the template is not rendered until it reaches the plugin. I can inspect the rendered HTML within the `html-webpack-plugin-after-html-processing` event handler but I'm not sure what to do with it at that point since it's already passed though the loader pipeline.

In order to get this far I referenced the following issues:

1. https://github.com/ampedandwired/html-webpack-plugin/issues/71
1. https://github.com/ampedandwired/html-webpack-plugin/issues/133
1. https://github.com/ampedandwired/html-webpack-plugin/issues/174
1. https://github.com/ampedandwired/html-webpack-plugin/issues/182
1. https://github.com/ampedandwired/html-webpack-plugin/issues/275

Please let me know if I'm missing something or if I can provide some more information.

Thanks

**Comment by jantimon** [comment]
The require part is done by webpack so it inherits all features and limitations of webpacks require.

What you could try is the following:

https://webpack.github.io/docs/context.html

`<%= require.context("./assets/", true, /^\..*\.jpeg$/)(htmlWebpackPlugin.image.src) %>`

Which would basically require all images but use only the one of your variable.

**Comment by raypatterson** [comment]
Thanks for the suggestion. Ideally I'd like to keep webpack syntax out of the template.
Right now I'm looking for a way to add a resource during one one of the plugin events.

I unsuccessfully tried:

```javascript
function HtmlInspect() {}
HtmlInspect.prototype.apply = compiler => {
  compiler.plugin('compilation', compilation => {
    compilation.plugin('html-webpack-plugin-before-html-generation', (htmlPluginData, callback) => {
        let assetJson = JSON.parse(htmlPluginData.plugin.assetJson);
        assetJson.push('/test-1.jpg');
        htmlPluginData.plugin.assetJson = JSON.stringify(assetJson);
        callback(null, htmlPluginData);
    });
  });
};
module.exports = HtmlInspect;
```

Do you know of a way I could pass the rendered template HTML though a loader during one of these events to allow webpack to discover the additional resources?

**Comment by jantimon** [comment]
Use a JavaScript file as root template - require the real template and use the require context to load the additional assets - pass the result to your template and return the string
