### ISSUE TITLE
Weird Error, Suddenly Pops up in html-webpack-plugin

### ISSUE THREAD

**Issue by bboysathish** [ampedandwired/html-webpack-plugin#326]
Hi,

I am getting weird error, suddenly from today, well it was working till last week. 

```js
Html Webpack Plugin:
<pre>
  TypeError: Cannot read property 'html-webpack-plugin-before-html-generation' o  f undefined
 
  - Tapable.js:75 Object.applyPluginsAsyncWaterfall
    [ss_ap]/[tapable]/lib/Tapable.js:75:19
 
  - util.js:26 Object.tryCatcher
    [ss_ap]/[bluebird]/js/main/util.js:26:23
 
 
  - index.js:118
    [ss_ap]/[html-webpack-plugin]/index.js:118:16
 
  - util.js:26 tryCatcher
    [ss_ap]/[bluebird]/js/main/util.js:26:23
 
  - promise.js:507 Promise._settlePromiseFromHandler
    [ss_ap]/[bluebird]/js/main/promise.js:507:31
 
  - promise.js:581 Promise._settlePromiseAt
    [ss_ap]/[bluebird]/js/main/promise.js:581:18
 
  - promise.js:697 Promise._settlePromises
    [ss_ap]/[bluebird]/js/main/promise.js:697:14
 
  - async.js:123 Async._drainQueue
    [ss_ap]/[bluebird]/js/main/async.js:123:16
 
  - async.js:133 Async._drainQueues
    [ss_ap]/[bluebird]/js/main/async.js:133:10
 
  - async.js:15 Immediate.Async.drainQueues [as _onImmediate]
    [ss_ap]/[bluebird]/js/main/async.js:15:14
 
</pre>
```

This error is pushed to index.html, instead of creating the html. 

Webpack version: 1.12.14
html-webpack-plugin : 2.17.0 & 2.16.1

Any ideas ?? Or Do you need more information please post here.

**Comment by jantimon** [comment]
Hm no idea - does updating webpack fix this?

**Comment by bboysathish** [comment]
No it doesn't.. Same was working till last week.. Node_modules folder remains same... This issue occurs on particular system.. Doesn't occur on my another machine.. Is there a way I can collect logs about what plugins does and post the log here???

**Comment by bboysathish** [comment]
ping @jantimon

**Comment by jantimon** [comment]
You will have to look into Tapable.js:75 Object.applyPluginsAsyncWaterfall
    [ss_ap]/[tapable]/lib/Tapable.js:75:19

**Comment by bboysathish** [comment]
@jantimon Suddenly this is not re producible. well Tapable.js, which module it contains ? :) ?

**Comment by jantimon** [comment]
https://github.com/webpack/tapable/blob/master/lib/Tapable.js

Can I close this?

**Comment by bboysathish** [comment]
yes you can, if the issue, i will open once again with more detail. Thanks.

**Comment by that70schris** [comment]
@jantimon I am having this issue as well upgrading from 1.6.1

webpack: 1.13.1
html-webpack-plugin: 2.22.0
tapable: 0.1.10 & 0.2.4

**Comment by mjsgreen01** [comment]
upgrading my node version solved this for me. v5.0->6.8

**Comment by cameronroe** [comment]
Try upgrading to `webpack@2.1.0-beta.28`
