### ISSUE TITLE
Explain `showErrors` Option

### ISSUE THREAD

**Issue by MarkHerhold** [ampedandwired/html-webpack-plugin#328]
Could someone explain what exactly the `showErrors` option does? The docs say

> `showErrors`: `true | false` if `true` (default) errors details will be written into the html page.

Does this mean the literal index/whatever.html file? Or does this really just mean the console? If it is the literal html file, what does this look like?

Thanks!

**Comment by jantimon** [comment]
It's really the html.
This happens especially if your template is a javascript file and you are creating a isomorphic app.

**Comment by MarkHerhold** [comment]
Interesting. Do you have an example handy? Just a quick copy paste would suffice. I'm trying to find this for myself and can't find it. Do you have to have a template string for this to be inserted into the HTML?

**Comment by jantimon** [comment]
In the examples folder :)
