### ISSUE TITLE
how can set the variable in custom html template

### ISSUE THREAD

**Issue by jarry** [ampedandwired/html-webpack-plugin#332]
https://github.com/ampedandwired/html-webpack-plugin/tree/master/examples/custom-template
<%= require('html!./partial.html') %>

<%= require('html!./htmlWebpackPlugin.options.partialHTML') %>  **like this ??**

I want use config.js options  to replace the `partial.html`

if I write this <%= require('html!../inc/partial.html') %> It can be correct.

but I use this it can't run. 
<% partialHTML = 'html!../inc/partial.html' %>
<%= require(partialHTML) %>
get Error: Cannot find module 'html!../inc/partial.html'.

**Comment by jarry** [comment]
<% partialHTML = htmlWebpackPlugin.options.partialHTML %>
<%= require(partialHTML) %>

I got these error:
Error: Cannot find module 'html!../inc/partial.html'.

**Comment by jarry** [comment]
if I write this <%= require('html!../inc/partial.html') %> It can be correct.

but I use this it can't run. 
<% partialHTML = 'html!../inc/partial.html' %>
<%= require(partialHTML) %>
get Error: Cannot find module 'html!../inc/partial.html'.

**Comment by jantimon** [comment]
You could only use dynamic requires: https://webpack.github.io/docs/context.html

**Comment by jarry** [comment]
Thanks.but I try this: <%= require.context("./", true, /^\..*\.html$/)(pageFragment) %>.

But I have got error yet.
ERROR in Template execution failed: Error: Cannot find module '../test.html'.
ERROR in   Error: Cannot find module '../test.html'.

**Comment by jarry** [comment]
I solve this problem, the variable `partialHTML` can't include prefix of path.
<%= require(partialHTML) %>
should using <%= require('html../' + partialHTML) %>, the partialHTML value is  `inc/partial.html`

**Comment by jantimon** [comment]
👍
