### ISSUE TITLE
Does plugin order matter?

### ISSUE THREAD

**Issue by rnsloan** [ampedandwired/html-webpack-plugin#336]
I am using the DefinePlugin like so 

```
new webpack.DefinePlugin({
	__DEVELOPMENT__: true,
}));
```

And using the value inside my html template

```
 <% if (__DEVELOPMENT__){ %>
...
<% } %>
```

From my testing this works regardless of the order `DefinePlugin` and `HtmlWebpackPlugin` declared in the code, but I wanted to check this is safe and not open to race conditions.

**Comment by jantimon** [comment]
Plugin order matters - but not in this case.

The html-webpack-plugin is subscribing to the webpack `emit` hook so if another plugin adds assets in the emit hook but is added later the html-webpack-plugin would not know about them.

**Comment by rnsloan** [comment]
Thanks for the response. So if a plugin is subscribed to the `emit` hook does that mean it does not run until after the main webpack compiler has finished?

**Comment by jantimon** [comment]
That's correct however this plugin starts a child compilation.
