### ISSUE TITLE
Generate  relative js path error

### ISSUE THREAD

**Issue by liaosong** [ampedandwired/html-webpack-plugin#337]
config as follows
```javascript
let createHtml = new HtmlWebpackPlugin({
	title: 'My App',
	filename: '../index.html',
	template:'./src/bin/index.ejs',
	inject:'body',
	hash: true
})
```

webpack config
```javascript
output: {
	filename: 'app.js',
	path: './dist/' + config.name + '/js/',
	publicPath: '/'
}
```

The file generated as I expected, the dir as follow
![image](https://cloud.githubusercontent.com/assets/3927282/15732451/e0a0f53c-28af-11e6-89bd-3b83a502a9e7.png)

But, the `app.js` path is not correct in `index.html` 
![image](https://cloud.githubusercontent.com/assets/3927282/15732529/891e877e-28b0-11e6-8eda-174118c27950.png)

I need the `app.js` path is `/js/app.js`, is a bug? thanks.

**Comment by jantimon** [comment]
Your public path is `/` so the script will be on `/app.js`.
