### ISSUE TITLE
How is it possible to load fonts from a CDN?

### ISSUE THREAD

**Issue by kripod** [ampedandwired/html-webpack-plugin#341]
I would like to know the best practices available about loading CSS-stored fonts (like the ones at Google Fonts) from a CDN.

**Comment by kripod** [comment]
At the end, I just need to automatically insert `<link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>` to the generated page.

**Comment by jantimon** [comment]
Just use a custom template.

**Comment by kripod** [comment]
Okay, thank you!
