### ISSUE TITLE
Dynamic script tag isnt showing hash

### ISSUE THREAD

**Issue by marr** [ampedandwired/html-webpack-plugin#344]
I have a build like so:

```
  new HtmlWebpackPlugin({
      template: 'index.hbs', // Load a custom template
      inject: 'body', // Inject all scripts into the body
      chunks: [ 'app' ],
      app: JSON.stringify(app)
    }),
```

and the generated file looks like so

`<script type="text/javascript" src="/app.js"></script>`

Shouldn't this .js reference include the hash of the file that was created?

**Comment by jantimon** [comment]
depends on your entries - did you try hash:true ?

**Comment by marr** [comment]
That does add the ?<hash> to the url, however I am still seeing the following:

Failed to parse SourceMap: http://localhost:8080/app.js.map

I think because its emitting out the hashes in the files from webpack.

![screen shot 2016-06-09 at 3 09 25 pm](https://cloud.githubusercontent.com/assets/44376/15948194/3ab96eba-2e54-11e6-994b-9270e01102cc.png)

My entries look like:

```
 entry: {
    app: './app/app.js',
    unauthorized: './app/unauthorized.js'
  },
  devtool: 'source-map',
  debug: true,
  output: {
    path: __dirname + '/dist',
    publicPath: '/',
    filename: 'assets/js/[name].[hash].js',
    chunkFilename: '[name].chunk.js'
  },

```

**Comment by marr** [comment]
sorry that was my prod config. my dev (middleware) one is:

```
const hot = 'webpack-hot-middleware/client?path=/__webpack_hmr&timeout=20000'

const config = {
  entry: {
    app: ['./app/app.js', hot ],
    unauthorized: [ './app/unauthorized.js', hot ]
  },
  devtool: 'source-map',
  debug: true,
  output: {
    path: '/',
    publicPath: '/',
    filename: '[name].js',
    chunkFilename: '[name].chunk.js'
  },
```

**Comment by marr** [comment]
oddly, using `eval-source-map` fixed my issue.

**Comment by jantimon** [comment]
Wow that's really strange. If you gonna find out why please let me know
