### ISSUE TITLE
Watcher/run adds <script> tag everytime/multiple times

### ISSUE THREAD

**Issue by Skuriles** [ampedandwired/html-webpack-plugin#347]
Hello,

I'm using webpack in Visual Studio (with taskrunner extension).
Problem is:
everytime I do a run webpack (same as start it in console) the generated files are added to the index.html.

First run:
`<script type="text/javascript" src="public/scripts/vendor.js"></script><script type="text/javascript" src="public/scripts/app.js"></script>
</body>`

second run:
`<script type="text/javascript" src="public/scripts/vendor.js"></script><script type="text/javascript" src="public/scripts/app.js"></script><script type="text/javascript" src="public/scripts/vendor.js"></script><script type="text/javascript" src="public/scripts/app.js"></script>
</body>`

and so on. 

If I start watch it does this multiple times in some kind of a loop (without changing anything in a file)
in index.html I get e.g. 10 times the <script> tags until the watcher stops with an error message:

Error: EBUSY, open 'D:\proj\CTM\WebClient\index.html'

webpack.config.js
`var webpack = require('webpack');
var HtmlWebpackPlugin = require('html-webpack-plugin');
var ExtractTextPlugin = require('extract-text-webpack-plugin');
var helpers = require('./config/helpers');

module.exports = {
    entry: {
        'vendor': './config/vendor.ts',
        'app': './public/app/main.js'
    },
    output: {
         filename: 'public/scripts/[name].js'
    },
    resolve: {
        extensions: ['', '.js', '.ts']
    },

    module: {
        loaders: [
            {
                test: /\.ts$/,
                loader: 'ts',
                exclude: helpers.root('node_modules', 'bootstrap')
            },
            //{
            //    test: /\.html$/,
            //    loader: 'html'
            //},
            {
                test: /\.(png|jpe?g|gif|svg|woff|woff2|ttf|eot|ico)$/,
                loader: 'file?name=assets/[name].[hash].[ext]'
            },
            {
                test: /\.css$/,
                exclude: helpers.root('public', 'app'),
                loader: ExtractTextPlugin.extract('style', 'css?sourceMap')
            },
            {
                test: /\.css$/,
                include: helpers.root('public', 'css'),
                loader: 'raw'
            }
        ]
    },

    plugins: [
        new webpack.optimize.CommonsChunkPlugin({
            name: ['app', 'vendor']
        }),

        new HtmlWebpackPlugin({
            template: './index.html'
        })
    ]
};`

How can I prevent that this script tags are added everytime or get the watcher working correctly?

**Comment by jantimon** [comment]
Oh okay - well the plugin (should) just pick up the assets from the webpack compilation result.
Please add a console.log somewhere here and let me know if `var webpackStatsJson = compilation.getStats().toJson();` is also growing:

https://github.com/ampedandwired/html-webpack-plugin/blob/c229fcbab27126c427dfd2678d10b410c3de275b/index.js#L406-L444

**Comment by Skuriles** [comment]
Hm,

ok. I've added a console.log in the loop rigth under assets.chunks[chunkName] = {};

console.log(JSON.stringify(webpackStatsJson).length);

It is the same for each loop...

Or did you have something different in mind?

Just let me know how I can support you

Thanks in advance

**Comment by jantimon** [comment]
https://github.com/ampedandwired/html-webpack-plugin/blob/c229fcbab27126c427dfd2678d10b410c3de275b/index.js#L408

just add here `console.log(chunk);`.

Whats your plugin configuration and template code?

**Comment by Skuriles** [comment]
Output
`chunk 0: {"id":1,"rendered":true,"initial":true,"entry":true,"extraAsync":false,"size":332170,"names":["externalLibs"],"files":["public/scripts/externalLibs.js"],"hash":"f6202c26e66b4fff3cfa","parents":[],"origins":[{"moduleId":0,"module":"D:\\proj\\CTM\\WebClient\\node_modules\\ts-loader\\index.js!D:\\proj\\CTM\\WebClient\\config\\externalLibs.ts","moduleIdentifier":"D:\\proj\\CTM\\WebClient\\node_modules\\ts-loader\\index.js!D:\\proj\\CTM\\WebClient\\config\\externalLibs.ts","moduleName":"./config/externalLibs.ts","loc":"","name":"externalLibs","reasons":[]}]}
Process terminated with code 0.
chunk 1: {"id":2,"rendered":true,"initial":true,"entry":false,"extraAsync":false,"size":2129480,"names":["vendor"],"files":["public/scripts/vendor.js"],"hash":"17f4e5c141580858e63c","parents":[1],"origins":[{"moduleId":0,"module":"D:\\proj\\CTM\\WebClient\\node_modules\\ts-loader\\index.js!D:\\proj\\CTM\\WebClient\\config\\vendor.ts","moduleIdentifier":"D:\\proj\\CTM\\WebClient\\node_modules\\ts-loader\\index.js!D:\\proj\\CTM\\WebClient\\config\\vendor.ts","moduleName":"./config/vendor.ts","loc":"","name":"vendor","reasons":[]}]}
chunk 2: {"id":0,"rendered":true,"initial":true,"entry":false,"extraAsync":false,"size":14810,"names":["app"],"files":["public/scripts/app.js"],"hash":"fc46d3827477af1379cb","parents":[2],"origins":[{"moduleId":0,"module":"D:\\proj\\CTM\\WebClient\\public\\app\\main.js","moduleIdentifier":"D:\\proj\\CTM\\WebClient\\public\\app\\main.js","moduleName":"./public/app/main.js","loc":"","name":"app","reasons":[]}]}`


index.html

`<html>
<head>
    <base href=/>
    <title>Consyd Time Management</title>
    <meta charset=UTF-8>
    <meta name=viewport content="width=device-width,initial-scale=1">
    <link rel=stylesheet href=public/css/styles.css>
    <link rel=stylesheet href=node_modules/bootstrap/dist/css/bootstrap.min.css>
    <script src=public/scripts/externalLibs.js></script>
    <script src=node_modules/core-js/client/shim.min.js></script>
    <script src=node_modules/zone.js/dist/zone.js></script>
    <script src=node_modules/reflect-metadata/Reflect.js></script>
</head>
<body>
    <div id=main class=container-fluid> <start-page>Loading...</start-page> </div>    
    <script type="text/javascript" src="public/scripts/externalLibs.js"></script>
    <script type="text/javascript" src="public/scripts/vendor.js"></script>
    <script type="text/javascript" src="public/scripts/app.js"></script>
</body>
</html>`

I've no special plugin config for this plugin. 

vendor.ts
`// Angular 2
import '@angular/platform-browser';
import '@angular/platform-browser-dynamic';
import '@angular/core';
import '@angular/common';
import '@angular/http';
import '@angular/router-deprecated';
// RxJS
import 'rxjs';`


externalLibs.ts
`import 'bootstrap'`

**Comment by jantimon** [comment]
Okay so here are two possible errors:

1) If you use a html-loader the index.html might get processed by it
2) You have already the script tags in your index.html and the plugin will inject them for you so they will be inserted twice

**Comment by Skuriles** [comment]
hm..

I removed the html loader from webpack.config.js and removed all entries for the three files in index.html

-> run => added three script tags once
-> run again => added three script tags again
-> run again => added three script tags third time..and so on.

It is not so important for me. I will just the add the three script tags once.
Just wanted to let you know.

**Comment by jantimon** [comment]
Okay maybe just another windows issue 😉
If you can find out why please let me know..

**Comment by jantimon** [comment]
What you could try is rename your index.html to index.ejs

**Comment by jantimon** [comment]
Oh wait - do you use the same file for input and output?

**Comment by Skuriles** [comment]
hm...

my entry point is main.js.

and in Plugins:
 new HtmlWebpackPlugin({
            template: './index.html'
        }),

so I don't have an explicit entry point for html files...

**Comment by jantimon** [comment]
Could you try to change the template to './index.ejs' and rename your file?

**Comment by Skuriles** [comment]
renamed index.html to index.ejs

changed webpack.config.js -> template to index.ejs

run - > new index.html is builded
added all script tags twice 
rerun -> file didn't change

so the only bug is that the scripts are added twice But this could be caused by another loader module maybe

**Comment by jantimon** [comment]
Just remove the script tags from your index.ejs and you should be good to go :)

**Comment by Skuriles** [comment]
oh, my fault. 

Didn't think about that index.html does not work as input and output. 
Problem fixed!

Thank you for your fast help.

**Comment by jantimon** [comment]
cool 👍

**Comment by alphapilgrim** [comment]
@jantimon I have a similar problem, in development, it'll add the scripts to the index.html and console logs tried to load angular twice. if I remove the scripts the plugin added from the index, they still load and I don't get an error. is there something I missing?
