### ISSUE TITLE
templateContent cannot be empty

### ISSUE THREAD

**Issue by mgol** [ampedandwired/html-webpack-plugin#355]
If you fire up the plugin with `templateContent: ''` in its settings, you'll get the default template. This is because the [check for `templateContent`](https://github.com/ampedandwired/html-webpack-plugin/blob/943c5556650759813936550aa92744ab1f5dff42/index.js#L110) just checks its truthiness.

I think the code should be changed to:
```js
if (self.options.templateContent != null) {
  return self.options.templateContent;
}
```

**Comment by jantimon** [comment]
Why would you like to generate an empty file?

We could add `templateContent !== undefined`

**Comment by mgol** [comment]
Not an empty file but a file with only injected script tags and nothing else. I have the following in plugins:
```js
new HtmlWebpackPlugin({
    templateContent: ' ',
    filename: 'something.html',
    inject: true,
    hash: true,
})
```

**Comment by jantimon** [comment]
This is definitely not an expected use case 😄 but it won't hurt to fix the bug.
Could you please prepare a pull request?

**Comment by mgol** [comment]
Sure, I'll try to submit a PR next week.

**Comment by jantimon** [comment]
Can I close this?

**Comment by mgol** [comment]
Sorry for the delay. Could you reopen? I've submitted a PR: #375.
