### ISSUE TITLE
Injecting javascript application state

### ISSUE THREAD

**Issue by andrewmclagan** [ampedandwired/html-webpack-plugin#356]
Any suggestions on how to inject initial state for a javascript application?

Initial state would be unique for each visitor, so after webpack compilation has already run and the html file is built?

**Comment by jantimon** [comment]
This plugin generates a static html file so this is not possible.

What you could do is to generate a template instead of a html file and render it from your backend.

**Comment by andrewmclagan** [comment]
Can this plugin generate templates!?

**Comment by jantimon** [comment]
It generates text files with a extension you choose. - So yes.
