### ISSUE TITLE
template can't use loaders

### ISSUE THREAD

**Issue by IvanProdaiko94** [ampedandwired/html-webpack-plugin#359]
In documentation I found that 

> template: Path to the template. Supports loaders e.g. html!./index.html

But in a current vercion it seems that it's broken functionality.
```
new HtmlWebpackPlugin({
                title: 'gambling',
                filename: '/gambling.html', // relative path from "output" directory
                template: "html?interpolate!"+srcDir + '/test.html' // source file
            })
```

allways fails with 
> ERROR in HtmlWebpackPlugin: Unable to read HTML template "html-minify!.\src\test.html"

[full config](https://gist.github.com/IvanProdaiko94/11de5685be831516b5851d5db780327e)

**Comment by jantimon** [comment]
did you take a look at the examples?
could you please post your loader configuration as well?

**Comment by IvanProdaiko94** [comment]
Yep, I've read an example.
Full config is [here](https://gist.github.com/IvanProdaiko94/11de5685be831516b5851d5db780327e)

**Comment by jantimon** [comment]
why do you use a html-minify loader?

**Comment by IvanProdaiko94** [comment]
My goal was to use
`html?interpolate`
to allow i18n in html. But us I understand when I use HtmlWebpackPlugin then common loader for html note invokes, I was going to bypass it using loader in template param of HtmlWebpackPlugin

**Comment by jantimon** [comment]
HtmlWebpackPlugin will use the loader from your loader configuration unless you don't specify any then it will fallback to an ejs loader.

**Comment by jantimon** [comment]
https://github.com/ampedandwired/html-webpack-plugin/blob/master/examples/html-loader/webpack.config.js

**Comment by IvanProdaiko94** [comment]
html-minify was used to detect is common loader invoked or not. It's present in loaders, and also turning off minification in HtmlWebpackPlugin I found that it's not invoked.

**Comment by jantimon** [comment]
Just use it like in the example and it will work. For minification you can use the html-loader or the webpack-html-plugin minification options..

```
ERROR in HtmlWebpackPlugin: Unable to read HTML template "html-minify!.\src\test.html"
```

says the the file path is wrong

**Comment by IvanProdaiko94** [comment]
Question was that I can't pass any loader in template param of HtmlWebpackPlugin, becouse it seems it reqests only direct path to file, but not common loader specification. Becouse it fails on any loader in template param :(

**Comment by jantimon** [comment]
Try `!!html/src/test.html`

**Comment by IvanProdaiko94** [comment]
fails

**Comment by jantimon** [comment]
Just tested a modified example:
```
var HtmlWebpackPlugin = require('../..');
var ExtractTextPlugin = require('extract-text-webpack-plugin');
var webpackMajorVersion = require('webpack/package.json').version.split('.')[0];
module.exports = {
  entry: './example.js',
  output: {
    path: __dirname + '/dist/webpack-' + webpackMajorVersion,
    publicPath: '',
    filename: 'bundle.js'
  },
  module: {
    loaders: [
      { test: /\.css$/, loader: ExtractTextPlugin.extract('style-loader', 'css-loader') },
      { test: /\.png$/, loader: 'file-loader' }
    ]
  },
  plugins: [
    new HtmlWebpackPlugin({
      filename: 'index.html',
      favicon: 'favicon.ico',
      template: 'html!template.html'
    }),
    new ExtractTextPlugin('styles.css')
  ]
};
```

and it works

**Comment by IvanProdaiko94** [comment]
Could it be problem in I18nPlugin?
All the difference in that I wrapped it into i18n, but now it's not accepting any loaders.
I post config without external html-minify for example, also I commented global loader for html (any way it's not invoked)

```
var webpack = require('webpack');

var ExtractTextPlugin = require("extract-text-webpack-plugin"),
    HtmlWebpackPlugin = require('html-webpack-plugin'),
    CleanWebpackPlugin = require('clean-webpack-plugin'),
    I18nPlugin = require("i18n-webpack-plugin");

var languages = {
    "en": null,
    "ru": require("./i18n/ru.json")
};


var rootDir = __dirname;
var srcDir = rootDir + "/src";
var distDir = rootDir + "/dist";

module.exports = Object.keys(languages).map(function (language) {

    return {
        context: rootDir, // a base directory to resolve the “entry”
        entry: {
            index: srcDir + '/index.js'
        },

        output: {
            path: distDir + '/' + language,
            filename: "[name].js", // [name] means we are going to use the "key" value of each entry as the bundle file name
            chunkFilename: "[id].js"
        },

        resolve: {
            extensions: ['', '.js', '.jsx'] // resolve file extentions so that we don't have to specify the extention for js and jsx files
        },

        // loaders for different types of resources. For jsx and es6, we uses babel loader.
        module: {
            loaders: [
                //{test: /\.html$/, exclude: /tmp/, loader: "html?interpolate"},
                {test: /\.js?$/, exclude: /(node_modules|tmp)/, loader: 'babel-loader'},
                {test: /\.css$/, loader: ExtractTextPlugin.extract("style-loader", "css-loader")},
                {test: /\.(png|jpg|woff|woff2|eot|ttf|otf)/, loader: 'url-loader'},
                {test: /\.svg/, loader: 'file?name=/img/[hash].[ext]?'},
                {
                    test: /\.scss$/,
                    loader: ExtractTextPlugin.extract("style-loader", "css-loader!postcss-loader!sass-loader")
                }
            ]
        },
        plugins: [
            new I18nPlugin(
                languages[language]
            ),
            new CleanWebpackPlugin(['dist', 'build'], {
                root: 'C:/webpack-101',
                verbose: true,
                dry: false
            }),
            new webpack.optimize.CommonsChunkPlugin({
                name: "commons",
                filename: "commons.js",
                chunks: ["index"]
            }),
            new ExtractTextPlugin("[name].css"),

            new HtmlWebpackPlugin({
                title: 'index',
                filename: '/index.html', // relative path from "output" directory
                //minify: {removeComments: true},
                template:  "!!" + srcDir + '/index.html' // source file
            })
        ]
    };
});
```

**Comment by jantimon** [comment]
you have to change it to `template:  "!!html!" + srcDir + '/index.html' // source file`

what is your error?

**Comment by IvanProdaiko94** [comment]
> ERROR in HtmlWebpackPlugin: Unable to read HTML template "!!C:\webpack-101\src\index.html"
but file is precent

**Comment by jantimon** [comment]
Why don't you change it to `"!!html!" + srcDir + '/index.html'` ?

**Comment by IvanProdaiko94** [comment]
>  ERROR in HtmlWebpackPlugin: Unable to read HTML template "!!html!C:\webpack-101\src\index.html"

No difference :(

**Comment by jantimon** [comment]
Hmm sry I have no idea why - try to start with my working example and add your parts part by part..

**Comment by IvanProdaiko94** [comment]
Sorry, but your example also fails. Mayby becouse I use windows?

**Comment by jantimon** [comment]
The unit tests are also run on windows so it should work.
The file loading and processing is done entirely by webpack not by this plugin.

**Comment by liuliangsir** [comment]
thx

**Comment by liuliangsir** [comment]
+1

**Comment by radut** [comment]
I have same error when adding  new AddAssetHtmlPlugin({}), my htm plugin fails when it tries to load filename specified within assetsHtmlPlugin
