### ISSUE TITLE
Possible to output to incomplete HTML page(?)

### ISSUE THREAD

**Issue by joneslloyd** [ampedandwired/html-webpack-plugin#360]
Hi there,

My context/usage is that I'm including the webpack-output "html" file via a PHP file (part of a content management system).

I already (at a higher level of abstraction) have a full HTML page, so want to be able to take my index.html file which only contains:

`<div id="app-go"></div>`

and run this:
```
new HtmlWebpackPlugin({
      template: 'app/index.html',
      minify: {
        removeComments: true,
        collapseWhitespace: true,
        removeRedundantAttributes: true,
        useShortDoctype: true,
        removeEmptyAttributes: true,
        removeStyleLinkTypeAttributes: true,
        keepClosingSlash: true,
        minifyJS: true,
        minifyCSS: true,
        minifyURLs: true,
      },
      inject: true,
    }),
```

and have the resultant index.html file just be: `<div id="app-go"></div>` plus the injected assets / CSS.

(So that I can, from my PHP file in the CMS, include() this index.html file in an already-rendered HTML page)

**Comment by jantimon** [comment]
Minify and inject won't work but everything else should be no problem

**Comment by jantimon** [comment]
If you disable inject you have to add the javascript files by yourself:
https://github.com/jaketrent/html-webpack-template/blob/86f285d5c790a6c15263f5cc50fd666d51f974fd/index.html

**Comment by joneslloyd** [comment]
Ah-ha! thanks

**Comment by joneslloyd** [comment]
For some reason, it's actually echoing the tags:

![screen shot 2016-06-24 at 15 28 01](https://cloud.githubusercontent.com/assets/997427/16338986/61802462-3a20-11e6-8f9b-213fd890362b.png)
