### ISSUE TITLE
Echoing tags

### ISSUE THREAD

**Issue by joneslloyd** [ampedandwired/html-webpack-plugin#361]
Hi there,

I originally created this issue: https://github.com/ampedandwired/html-webpack-plugin/issues/360

And was advised that I can output to a partial (non-complete HTML file) by using the template tags like here: https://github.com/jaketrent/html-webpack-template/blob/86f285d5c790a6c15263f5cc50fd666d51f974fd/index.html

However, the result is that when I `include();` the HTML file via PHP, the tags are actually echoed like so:
![61802462-3a20-11e6-8f9b-213fd890362b](https://cloud.githubusercontent.com/assets/997427/16340522/df19d60e-3a28-11e6-9212-a8293a6649c6.png)

Are you aware of how to prevent this?

**Comment by jantimon** [comment]
do you include your source file or your output file?

**Comment by joneslloyd** [comment]
They're both the same thing actually.

It takes a file called index.html (which just contains the div tag to mount
the app on to) and is meant to output that same tag along with JS/CSS into
the same file

**Comment by jantimon** [comment]
This plugin takes a template and generates a file so you can't have the same input and output file..

**Comment by joneslloyd** [comment]
I've changed it so now I have:
- `index-input.html`
- `index.html`

The file to write to is `index.html`, and it is an empty file

The `index-input.html` contains this:
```
<div>
	<% for (var css in htmlWebpackPlugin.files.css) { %>
		<link href="<%= htmlWebpackPlugin.files.css[css] %>" rel="stylesheet">
	<% } %>

	<% if (htmlWebpackPlugin.options.window) { %>
		<script>
		  <% for (var varName in htmlWebpackPlugin.options.window) { %>
		    window['<%=varName%>'] = <%= JSON.stringify(htmlWebpackPlugin.options.window[varName]) %>;
		  <% } %>
		</script>
	<% } %>

	<% for (var chunk in htmlWebpackPlugin.files.chunks) { %>
		<script src="<%= htmlWebpackPlugin.files.chunks[chunk].entry %>"></script>
	<% } %>

	<% if (htmlWebpackPlugin.options.devServer) { %>
		<script src="<%= htmlWebpackPlugin.options.devServer%>/webpack-dev-server.js"></script>
	<% } %>

	<div id="app-go"></div>
</div>
```

But the output is blank now

**Comment by jantimon** [comment]
whats your webpack configuration?

**Comment by joneslloyd** [comment]
This is it: https://gist.github.com/joneslloyd/fd3b6f5e88677d7034676677ce32e027

**Comment by jantimon** [comment]
You forgot to specify the output location and you should remove the minify feature for an incomplete html output

**Comment by joneslloyd** [comment]
Like this?
```
new HtmlWebpackPlugin({
      template: 'app/index-input.html',
      filename: 'app/index.html'
    }),
```

(That doesn't seem to do it actually)

**Comment by jantimon** [comment]
looks correct :)

**Comment by jantimon** [comment]
oh try:

```
new HtmlWebpackPlugin({
      template: 'app/index-input.html',
      filename: 'app/index.html',
      inject: false
    }),
```

**Comment by joneslloyd** [comment]
It's not working unfortunately (for some reason). Hmmm..

**Comment by joneslloyd** [comment]
Just as an update / clarification - There's actually zero output whatsoever.

I've got a (PHP generated) HTML page in the browser, and the output of webpack should be being echoed inside a div:
```
echo '<div class="app-sidebar instance-'.$post->ID.'">';
	include( plugin_dir_path( __FILE__ ).'js/react/app/index.html' );
echo '</div>';
```

But the output inside that div is blank (as index.html is before its meant to be populated via webpack)

**Comment by joneslloyd** [comment]
I've managed to fix an earlier issue (unrelated to html-webpack-plugin), but now the output is:
```
<% for="" (var="" css="" in="" htmlwebpackplugin.files.css)="" {="" %=""> <% }="" %=""> <% if="" (htmlwebpackplugin.options.window)="" {="" %=""> <% }="" %=""> <% for="" (var="" chunk="" in="" htmlwebpackplugin.files.chunks)="" {="" %=""> <% }="" %=""> <% if="" (htmlwebpackplugin.options.devserver)="" {="" %=""> <% }="" %="">
```
(So the template tags are being ignored)

**Comment by jantimon** [comment]
Sorry I have no idea what you are doing to there 😄

Just:

1. Write an input template
2. Use the html-webpack-plugin to generate the output
3. Use php to do whatever you want to do

**Comment by joneslloyd** [comment]
Ah, I think the issue is that i've also got (in development) the content being generated dynamically:
```
function templateContent() {
  const html = fs.readFileSync(
    path.resolve(process.cwd(), 'app/index-input.html')
  ).toString();

  if (!dllPlugin) { return html; }

  const doc = cheerio(html);
  const body = doc.find('body');
  const dllNames = !dllPlugin.dlls ? ['reactBoilerplateDeps'] : Object.keys(dllPlugin.dlls);

  dllNames.forEach(dllName => body.append(`<script data-dll='true' src='/${dllName}.dll.js'></script>`));

  return doc.toString();
}
```
And something here is going wrong..

Thanks for your help :)

**Comment by jantimon** [comment]
Cool that you found it 👍
