### ISSUE TITLE
minify always enabled?

### ISSUE THREAD

**Issue by guidorice** [ampedandwired/html-webpack-plugin#363]
I have been puzzling over this, it seems to be an issue. My index.html is always minified (whitespace removed) even though I set it to `minify : false`, and also I have tried

```
     new HtmlWebpackPlugin({
      template: 'src/index.html',
      cache: false,
      minify: {
        collapseWhitespace: true,
        preserveLineBreaks: true
      }
    })
```

version:
    "html-webpack-plugin": "^2.15.0", 

Any suggestions or workaround or could this be an issue with htmlwebpackplugin? Thanks

**Comment by guidorice** [comment]
Oops, here is what version I am actually using:
```
npm show html-webpack-plugin version
2.21.0
```

**Comment by jantimon** [comment]
Without knowing all details about your config my guess would be that you are using the `html-loader` for `.html` files and therefore it is also used for `src/index.html` and minifies it.

**Comment by guidorice** [comment]
Hi jantimon, thanks that is a good suggestion. I am actually not sure about html-loader, because I am just learning webpack. I am using the config shown here:

https://angular.io/docs/ts/latest/guide/webpack.html

See the webpack.common.js and the app.component.ts at the bottom of that page. It seems to me kind seems odd in that app.component.ts does

     template: require('./app.component.html')

instead of 

    templateUrl: './app.component.html'

So I suspect you might be right about it using html-loader. But I would love any additional  suggestions or pointers you can think of! But also you can go ahead and close this issue. Thanks so much.

**Comment by jantimon** [comment]
Webpack compiles anything to javascript. So if you want to use html in your javascript you need a loader which in this case turns the html file into a string.

In your webpack config just rename your template to index.ejs and the minfication will stop.

**Comment by guidorice** [comment]
Awesome! you nailed it. Thanks again

**Comment by buiduccuong30051989** [comment]
@guidorice thank you, it's work (bow)
