### ISSUE TITLE
Favicon with hash

### ISSUE THREAD

**Issue by victorwpbastos** [ampedandwired/html-webpack-plugin#364]
https://github.com/ampedandwired/html-webpack-plugin/blob/master/index.js#L410

Says that with option `hash: true`, It would add a hash to favicons. After several tests, I realized that javascript and css files contains a hash, but favicons don't. Maybe is this a bug?

My config:
```js
new HtmlWebpackPlugin({
    filename: 'index.html',
    template: 'index.html',
    favicon: 'favicon.ico',
    hash: true
})
```

**Comment by jantimon** [comment]
Hm don't know why but you could use the https://github.com/jantimon/favicons-webpack-plugin - it will generate a hashed filename if needed.

**Comment by victorwpbastos** [comment]
Why was this issue closed? The error still persists.

**Comment by MikeYermolayev** [comment]
Is there any update on this?

**Comment by olsonpm** [comment]
I thought it'd be important to note that even if the hash did work for favicon, it is a compilation hash and not a content hash.  The hash is also appended via query string as opposed to appending to the file name.  Neither of these qualities are ideal for caching, so I suggest users either create a PR fix or find an alterntative solution (that's what I'm doing).  This library has been great for generating the html and I'm going to leave its purpose at that.
