### ISSUE TITLE
issue when using with html-loader

### ISSUE THREAD

**Issue by jackyon** [ampedandwired/html-webpack-plugin#365]
hi, 

I am trying to use the this plugin with html-loader, but i found the generated html page title become to ''<%= htmlWebpackPlugin.options.title %>" after I using the html-loader.

is there any solution for this?

plz advise, thx!

**Comment by jantimon** [comment]
rename your template file to .ejs or exclude it from the loader

**Comment by jackyon** [comment]
hi @jantimon,

i have rename to ejs, but i can't use with the syntax: <img src="logo.png" /> any more.

only <img src="<%= require('../containers/App/loading-logo.png') %>" alt="">" worked.

plz help, thx.

**Comment by jantimon** [comment]
I believe you could use https://github.com/emaphp/underscore-template-loader
or just hardcode the page title and use the html loader
