### ISSUE TITLE
The plugin crushes encoding

### ISSUE THREAD

**Issue by progand** [ampedandwired/html-webpack-plugin#366]
Hi!
If you have some non-latin character in jsx, you have a problem with the plugin.

Example: 

```
<span>日本語</span>
```

becomes

```
<span> æ—¥æœ¬èªž</span>
```

**Comment by progand** [comment]
Fixed when I added into `index.html` following line of code

```
<meta charset="UTF-8">
```

Can you notice this in README.md?

**Comment by jantimon** [comment]
Which part of the code transforms the content?

**Comment by progand** [comment]
I think content is not transformed. Because changing page encoding in browser helped. 
Maybe its not issue with the plugin. I think we always  have to add charset meta tag to avoid issues with encoding. I'll close ticket.

**Comment by jantimon** [comment]
We have that in the default template:
https://github.com/ampedandwired/html-webpack-plugin/blob/master/default_index.ejs#L4
