### ISSUE TITLE
About path

### ISSUE THREAD

**Issue by Justinidlerz** [ampedandwired/html-webpack-plugin#368]
I hope that the path to the resource cdn server path, but if I set the parameter `config.output.publicPath` that static resource references in the path will be modified, there is no way I can just change the html resource path?

**Comment by Justinidlerz** [comment]
if i set `config.output.publicPath = '//xxx.xxx.com/'` and than the output css `background:url(//xxx.xxx.com/aa.jpg')`  ,but i just only want to change html `<link href=//xxx.xxx.com/aaa.css' />`

**Comment by jantimon** [comment]
The extract css plugin allows to overwrite the public path maybe we need something similar

**Comment by Justinidlerz** [comment]
Thank you!

**Comment by jantimon** [comment]
Would you like to create a pull request?

**Comment by Justinidlerz** [comment]
Have to try.
I'm use webpack and gulp to build my project, and i write a gulp plugin to resolve this question yesterday.
When i publish my project modal then run the gulp task to add url prefix. 
[gulp-html-url-prefix](https://github.com/Justinidlerz/gulp-html-url-prefix)

**Comment by jantimon** [comment]
Okay cool :)

**Comment by Justinidlerz** [comment]
Hi @jantimon , i'm write a plugins to add the url prefix [html-webpack-prefix-plugin](https://github.com/Justinidlerz/html-webpack-prefix-plugin)
