### ISSUE TITLE
Only parsing files in the root directory of the project

### ISSUE THREAD

**Issue by MarcosCosmos** [ampedandwired/html-webpack-plugin#369]
So, I've installed the plugin and it works perfectly if-and-only-if the target template is in the same directory as the webpack.config.js. As soon as the template is located in a sub-folder, the plugin runs without raising exceptions, but the contents of resulting output file contains nothing from the template, (it does still insert the script tags to load targeted chunks).

Here is the plugin's section of the webpack configuration for when the html file is in the root of the project:
		new HtmlWebpackPlugin({
			filename: 'credits.html',
			template: __dirname + '/credits.html',
			chunks: ['framedPage', 'jquery']
		}),
Here is the configuration for when it is in the sub-directory:
		new HtmlWebpackPlugin({
			filename: 'credits.html',
			template: __dirname + '/src/content/pages/credits.html',
			chunks: ['framedPage', 'jquery']
		}),

Changing the template's location is the only change I'm making between the working and non-working setups (including moving the file to the appropriate location).

I'm sure it's pointing to/sitting in the correct location as I have checked repeatedly.

This is what the credits.html output file looks like when the template is in a sub-directory:
<head><link href="app.css" rel="stylesheet"></head>credits.html<script type="text/javascript" src="jquery.js"></script><script type="text/javascript" src="framedPage.js"></script>

What could possibly be causing this?

**Comment by jantimon** [comment]
What every you write into `template` gets turned into webpack `require('....')`.
So if you set the correct `context` value in your webpack config you could also use './src/content/pages/credits.html'

However I have know idea why webpack require shouldn't work for your case and why there is no exception if it fails..

**Comment by MarcosCosmos** [comment]
Re-installing seems to have solved the problem. Thanks for the information though, I'll close the issue.

**Comment by leak** [comment]
I have the same problem. As soon as index.html is moved into a sub directory, the template variables are not replaced anymore. Neither reinstalling, nor prefixing the path with "./", nor setting the context properly did resolve the issue. The template itself is picked up, minification works and also the .js references are added but the template variables are not replaced.

**Comment by jantimon** [comment]
@leak did you read the faq?

**Comment by leak** [comment]
Yes, but it is still unclear to me what a sub directory has to do with this all.

**Comment by jantimon** [comment]
If I had to guess I would say it's a miss configuration of your html loader

**Comment by raphaklaus** [comment]
Same situation here

**Comment by NeXTs** [comment]
+1
