### ISSUE TITLE
Wrong <script> tags order or impossible to specify entry order 

### ISSUE THREAD

**Issue by schermannj** [ampedandwired/html-webpack-plugin#372]
Hi, I have two entries in my webpack config, it looks like this one:

`    config.entry = {
        app: './app/app.js',
        bootstrap: './app/app.bootstrap.js'
    };
`
Here is my plugin config:

`        new HtmlWebpackPlugin({
            template: './static/index.html',
            inject: 'body'
        }),`

I expect that output will be like this: 

`
...
<body>
       <script src='app.js'/>
       <script src='bootstrap.js'/>
</body>
`

But instead of it I'm getting next one

`
...
<body>
       <script src='bootstrap.js'/>
       <script src='app.js'/>
</body>
`

The main point is that bootstrap.js should be second.
I tried to change entry order and I renamed my js files, but It doesn't change anything. Any ideas how can I deal with it?

**Comment by jantimon** [comment]
Did you take a look at the sort options?

**Comment by schermannj** [comment]
I didn't see it, you're right, thx.
