### ISSUE TITLE
sasslint run twice with html webpack plugin

### ISSUE THREAD

**Issue by todd-richmond** [ampedandwired/html-webpack-plugin#373]
I got your plugin working to create index.html from your bone stock index.ejs and it correctly creates my assets/index.html in development mode. However, it now runs sasslint (via sasslint-webpack-plugin) twice on every startup (& possibly eslint). If I comment the plugin out, it definitely only runs once. 

Both runs happen immediately before packages are analyzed and emitted. I tried adding ''html-webpack-plugin' to sasslint-plugin's 'ignorePlugins', but that did not make any difference

**Comment by jantimon** [comment]
The html-webpack-plugin uses a child compiler like extract text plugin and some other loaders.
A child compilation starts another compile run.

If the lint plugins don't handle this correctly they run twice

**Comment by todd-richmond** [comment]
found the problem - sasslint allows you to ignore other plugins, but html-webpack-plugin uses a unique name for each compiler instance that includes the output filename.

It would be nice to add a new "compilerName" option to your plugin so that you can explicitly name each child process. That way each plugin instance can listed individually in sasslint's ignore list to support multiple output files without having to include the full path and quote marks.

For anyone who finds this - here is a workaround

```
new plugins.sasslint({
    ignorePlugins: [
        'extract-text-webpack-plugin',
        // html plugin name contains output filename
        'html-webpack-plugin for "index.html"'
    ]
})
```

**Comment by jantimon** [comment]
cool 👍
