### ISSUE TITLE
manifest路径只有文件名，没有输出publicPath

### ISSUE THREAD

**Issue by 1340641314** [ampedandwired/html-webpack-plugin#374]
![2](https://cloud.githubusercontent.com/assets/8424643/16607766/75803af0-4377-11e6-87ba-8a83722aed08.png)

![1](https://cloud.githubusercontent.com/assets/8424643/16607779/93f88780-4377-11e6-92ab-853fe24934d4.png)

![3](https://cloud.githubusercontent.com/assets/8424643/16607782/afd894c2-4377-11e6-8761-947edafd6879.png)

**Comment by jantimon** [comment]
Could you prepare a pull request?
