### ISSUE TITLE
Access the webpack bundle hash

### ISSUE THREAD

**Issue by andypandy** [ampedandwired/html-webpack-plugin#376]
How do I access the webpack bundle hash?

**Comment by jantimon** [comment]
See the stats option at the bottom of the https://github.com/ampedandwired/html-webpack-plugin#writing-your-own-templates section

**Comment by tomsun** [comment]
from a custom template: <%= webpack.hash %>

**Comment by glusa8** [comment]
@tomsun do you have the documentation for `webpack.hash` being used inside a template?

I couldn't find it anywhere that said, you can use `webpack.hash` in terms of official documentation.

**Comment by patricksmms** [comment]
@glusa8, if it's not working for you, try changing the file extension from .html to something else, like .ejs

**Comment by Jade66** [comment]
@glusa8 , I am also leery of using webpack.hash if it's not officially supported.  But it is exactly what I need.  Any word on the "official" status of this property?
