### ISSUE TITLE
needs to do not minify html with pug(jade)

### ISSUE THREAD

**Issue by dxcqcv** [ampedandwired/html-webpack-plugin#377]
I know setting a loader using the module.loaders syntax will cause html minification,

but I really needs pretty html files, because I compiled pug to jekyll html, if jekyll cannot recognize it, and I try to set `minify` to `false` or `preserveLineBreaks: true`, but no work.

so anyway to get pretty html files with the module.loaders syntax?

**Comment by evandertino** [comment]
This should work in the loader options for pug-html-loader itself

      loaders: [
        {
          test: /\.pug$/,
          exclude: /(node_modules)/,
          loader: "pug-html",
          query: {
            pretty: true
          }
        }
      ]

**Comment by dxcqcv** [comment]
@evandertino thx, it works

**Comment by phiphou** [comment]
This doesn't work for me, can you provide a complete example ? Thanks ;)
