### ISSUE TITLE
Using the "Handlebars" (or similar) instead of "Blueimp".

### ISSUE THREAD

**Issue by stas-webwork** [ampedandwired/html-webpack-plugin#38]
For example, I want to use "partials" in "index.html" — how can I do this?
Thanks.

**Comment by bebraw** [comment]
See

```
plugins: [
  new HtmlWebpackPlugin({
    templateContent: function(templateParams, webpackCompiler) {
      // Return your template content synchronously here 
    }
  })
]
```

You can perform the conversion there.

**Comment by SimenB** [comment]
@stas-webwork To use partials, you'll have to run `Handlebars.registerPartial` manually if you're currently relying on `handlebars-loader` to register them for you.

**Comment by stas-webwork** [comment]
It's ok. Thanks.
Next step in using Handlebars in index.html:
https://github.com/ampedandwired/html-webpack-plugin/issues/40
