### ISSUE TITLE
CSS injection always includes a head tag

### ISSUE THREAD

**Issue by antoligy** [ampedandwired/html-webpack-plugin#380]
I don't know if this is a bug so much as a feature.  Essentially this use-case is for one where webpack only generates a file containing paths to the various assets that have been created, and this file is included in the header.

Unfortunately the html-webpack-plugin _(incorrectly)_ [always assumes](https://github.com/ampedandwired/html-webpack-plugin/blob/master/index.js#L500) that I wish to inject these into the head, and so it _(correctly)_ [inserts another head tag](https://github.com/ampedandwired/html-webpack-plugin/blob/master/index.js#L536).

What would be sane options here - Would another configuration parameter, for example, make sense?

**Comment by jantimon** [comment]
for edge cases just turn inject off

**Comment by antoligy** [comment]
I have already tried that and a new `<head>` tag is still appended which is why I raised the issue.

This doesn't seem like an edge-case to me, as it's a pretty huge assumption to make that I'll always be creating my entire head tag within the template file, and given that for every other type of asset this can be disabled by setting `inject: false` it seems weird to enforce the creation of a new tag.

My question is "Does changing this behaviour make sense, and if so what is the recommended approach?" - I ask because based on the answer I would like to attempt to submit a PR resolving this issue.

**Comment by jantimon** [comment]
As you can see the tag is not created if inject is off:
https://github.com/ampedandwired/html-webpack-plugin/blob/master/index.js#L277-L281

**Comment by jantimon** [comment]
Why would you like to have a page without a head tag?

**Comment by antoligy** [comment]
My bad, inject had still been set to true outside of production builds-

This use-case is one where webpack handles all assets and generates a templates file to be used by Jekyll (or a CMS) as an include within its own head tag (where metadata and such is stowed)

**Comment by jantimon** [comment]
That's a perfect fit to disable injection - use this plugin with a template to have full control where your css and js goes - you could even generate a head and footer html file

**Comment by davidpelayo** [comment]
@jantimon In case you want to generate a static html asset to be then embedded or included server-side in a larger scope html.
