### ISSUE TITLE
crossorigin attribute on script tags

### ISSUE THREAD

**Issue by stocks29** [ampedandwired/html-webpack-plugin#382]
It would be great if there were a way to configurably add a `crossorigin` attribute on the injected script tags.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#attr-crossorigin

**Comment by jantimon** [comment]
https://www.npmjs.com/package/webpack-subresource-integrity does this for you

**Comment by dyw934854565** [comment]
use plugin to add custom attributes on inject tags
https://www.npmjs.com/package/html-webpack-inject-attributes-plugin
