### ISSUE TITLE
specify the location of the assets inject to?

### ISSUE THREAD

**Issue by mycoin** [ampedandwired/html-webpack-plugin#386]
In my opinion, the `template` decides the main layout for the .html documents that created. 

so,
 
if the `HtmlWebpackPlugin` providers an especial mark (e.g `<!-- webpack:javascript -->`) in the template, and then replace the `<script>` tags all here. Now, I think the development experience will be much better!

Therefore, I can code my templates like this:

```html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8" />
    <title>title</title>
    <!-- webpack:css -->
    <script type="text/javascript">
    var F = {
        // global config here.
    };
    </script>
</head>
<body>
    <div class="loading"></div>
    <div class="app"></div>
    <!-- webpack:javascript -->

    <script type="text/javascript">
    // post logic here
    </script>
</body>
</html>
```

**Comment by jantimon** [comment]
this won't solve all use cases so just turn off injection and add the assets by yourself using the template variables

**Comment by mycoin** [comment]
Er! I got it, I agree with u. Maybe template engine would work well.

**Comment by escapedcat** [comment]
Just to help others who find this.   
Use this to specify the place of the output in your template:
```
<% for (var chunk in htmlWebpackPlugin.files.chunks) { %>
<script src="<%= htmlWebpackPlugin.files.chunks[chunk].entry %>"></script>
<% } %>
```
From https://github.com/jaketrent/html-webpack-template/blob/86f285d5c790a6c15263f5cc50fd666d51f974fd/index.html
