### ISSUE TITLE
when the input template is not a full html with no </body>,inject not work, should support more flexible

### ISSUE THREAD

**Issue by cnweibo** [ampedandwired/html-webpack-plugin#388]
Hi, sir,
In my project, i will use webpack to build frontend assets for partial html, NOT for a complete html file with head, body tag.
In such case, i have no way to make it work to inject the compiled js or css to final output.
Can you implement gulp-inject like pattern: for where to inject the compiled js, support regex pattern.
For example, in a html partial input with  xxxxHere is injected js file script tag xxx .
the  and  can be a parameter transfered to html-webpack-plugin.

That will give pretty power for it.
Or, can you give some clue so that i can implement that to fit my requirement.

Thanks~!

**Comment by jantimon** [comment]
turn inject off and use the template variables:

https://github.com/jaketrent/html-webpack-template/blob/86f285d5c790a6c15263f5cc50fd666d51f974fd/index.html

**Comment by cnweibo** [comment]
@jantimon , thanks for your feedback. That solution does not fit my requirement well.
Because the template itself is a backend (laravel blade) partial. I will build for frontend with webpack, build for backend(injecting some backend assets) with gulp. They both use and write back the same blade partial. 
That partial will be both used by laravel (for server side rendering) and webpack for front end development. I will give the partial to webpack for integrating front end vuejs application. So i must figure out a mechanism to inject some js/css file developed by front end team, meanwhile, i must remains some assets backend team developed. 
The best way for me is: **let html-webpack-plugin can inject compiled assets into any place(regex defined place) in any file(**Here is the laravel template blade file). 
So, if i customized webpack-plugin to fit my requirement, which function should i do coding?

Thanks a lot~!

**Comment by jantimon** [comment]
Sorry the inject is complicated enough and the template system is really mighty - you can use any language and I guess there is one which will work well together with your backend template language

**Comment by cnweibo** [comment]
@jantimon , thanks, i have customized it for my requirement: supporting gulp-inject manner injecting css/js assets. If you'd like, please consider give another option value for 'inject: gulp-inject', this will let html-webpack-plugin to inject any place for any kind of file at place  for js assets and for css assets. Hope it is helpful to other guy seeking similar solution

```
HtmlWebpackPlugin.prototype.injectAssetsIntoHtml = function (html, assets, assetTags) {

  var htmlRegExp = /(<html[^>]*>)/i;
  var headRegExp = /(<\/head>)/i;
  var bodyRegExp = /(<\/body>)/i;
  var gulpinjectRegJS = /(<!-- inject:js -->)([\s\S]*?)(<!-- endinject -->)/;
  var gulpinjectRegCSS = /(<!-- inject:css -->)([\s\S]*?)(<!-- endinject -->)/;
  var body = assetTags.body.map(this.createHtmlTag);
  var head = assetTags.head.map(this.createHtmlTag);

  if (body.length) {
    html = html.replace(gulpinjectRegJS,function (match,injecthead,content,injectend) {
        return injecthead+body+injectend;
    })
  }
  if (head.length) {
    html = html.replace(gulpinjectRegCSS,function (match,injecthead,content,injectend) {
        return injecthead+head+injectend;
    })
  }
  return html;
};
```

**Comment by TaekSoonJang** [comment]
This thread was very helpful to me! Thanks you guys!! :)
