### ISSUE TITLE
How to inject scripts without touching the ejs/lodash/underscore templating?

### ISSUE THREAD

**Issue by morgs32** [ampedandwired/html-webpack-plugin#391]
I'd like to go isomorphic with your starter. This means using ejs (or any other templating language I presume). However, again htmlwebpackplugin gets in the way. It wants to compile the template (with lodash/underscore) as part of the webpack. I need it to leave the ejs templating language alone, so I can have it in the build.

Any thoughts?

Here's a screenshot:
![image](https://cloud.githubusercontent.com/assets/1364795/17085490/59502d20-51a7-11e6-82b9-adbc11b084cf.png)

And here's the place in my commit where I isomorphically get the html.
https://github.com/morgs32/morgans-tt/blob/master/server/main.js#L116

Thanks!

**Comment by jantimon** [comment]
Did you try the raw loader?
