### ISSUE TITLE
CSS Modules (html-loader + interpolate incompatibility issue?)

### ISSUE THREAD

**Issue by xanderlu** [ampedandwired/html-webpack-plugin#392]
Is there a way to get CSS Modules working with this plugin?

I have the following `html-webpack-plugin` config:
```javascript
new HtmlWebpackPlugin({
  template: join(__dirname, 'src', 'index.html'),
  minify: {
    removeComments: true,
    keepClosingSlash: true
  },
  inject: true
})
```

and this `html-loader` config:
```javascript
}, {
  test: /\.html$/,
  loader: 'html?interpolate',
}, {
```

The HTML itself looks like this:
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title></title>
  </head>
  <body>
    <div class="${require('./styles.css').test}"></div>
  </body>
</html>
```

and the CSS has something like:
```css
.test {
  background-color: gray;
}
```

But I end up with the following error:
```
Html Webpack Plugin:
  ReferenceError: window is not defined
```

**Comment by xanderlu** [comment]
looks like this has to do with style-loader needing the window object available.
https://github.com/webpack/style-loader/pull/115

**Comment by jantimon** [comment]
you could try `!!css!my-style.css`

**Comment by OlzhasAlexandrov** [comment]
@xhyp0 @jantimon 
Why is this issue closed?
The `!!css!my-style.css` doesn't work, while unfortunately there is still no described way of using CSS modules with html-webpack-plugin

**Comment by OlzhasAlexandrov** [comment]
Using `!!css-loader/locals!./styles.css` instead of `!style-loader!css-loader!./styles.css` fixes the issue when working with CSS modules
