### ISSUE TITLE
Problem using with replace loaders

### ISSUE THREAD

**Issue by voyti** [ampedandwired/html-webpack-plugin#394]
Hello,

So I have a seemingly easy case - I want to replace a string in a html file, which is later processed by the HtmlWebpackPlugin. The problem is, after replacing, the plugin throws:

`ERROR in ./~/html-webpack-plugin/lib/loader.js!./src/index.html
    Module parse failed (...)  Unexpected token (1:0)
    You may need an appropriate loader to handle this file type.`

I have even opened a stackoverflow question describing that issue:
https://stackoverflow.com/questions/38359842/use-html-webpack-plugin-with-string-replace-loader-in-webpack

I tried multiple loaders for that but all acted the same way. I started to dive into the source of this plugin, but I figured you guys may be able to help me with that. 

Best

**Comment by ala85** [comment]
+1

**Comment by kostyatam** [comment]
Hi, it's not a problem with HtmlWebpackPlugin directly. For more details you can check my [answer](https://stackoverflow.com/questions/38359842/use-html-webpack-plugin-with-string-replace-loader-in-webpack/38936363#38936363)  on stackoverflow.

**Comment by jantimon** [comment]
Nice one - do you think we could improve the html-webpack-plugin somehow to improve the error message - so that people can find this easier?
