### ISSUE TITLE
Inject json object via the plugin

### ISSUE THREAD

**Issue by ala85** [ampedandwired/html-webpack-plugin#396]
I have an index.html file containing a javascript global object as the follow:

```
<html>
    ...
<body>
        <script>
            var CONFIG =
                {
                    key1: "value1",
                    key2: "value2",
                    key3: "value3"
                };
        </script>
        <section class="main-section">
....
</body>
</html>
```

In my webpack file I have setup  the plugin as it follows:

```
new HtmlWebpackPlugin({
            inject: false,
            filename: "myfile.html",
            template: "./src/myfile.html",
            title: "Page Title",
            configuration: configurations.getConfiguration(TARGET, webpackCommon.buildVersion)
        })
```

My attempt was to set the configuration in the html file as the following, but obviously it does not work

```
<html>
    ...
<body>
        <script>
            var CONFIG = <%= htmlWebpackPlugin.options.configuration %>
                
        </script>
        <section class="main-section">
....
</body>
</html>
```

Is a possible use case to handle? I also tried with another plugin ( https://github.com/jamesandersen/string-replace-webpack-plugin) but it seems as it conflicts with the html-webpack-plugin.

Any help appreciated, thanks

**Comment by jantimon** [comment]
This should work - did you read the faq?

**Comment by ala85** [comment]
Yes Ichevked them. Does it matter that the file is an html one and not an ejs one?

**Comment by jantimon** [comment]
Depends on your configuration - did you try?

**Comment by ala85** [comment]
Hi, sorry for delay. Yes I tried and what I get in the output is

```
<script>
            var CONFIG = [object Object]
 </script>
```

What I need is the actual JSON object. As far as I understand, <%= %> will print a string of the configuration. I also tried <%- %> but getting the same result.

**Comment by jantimon** [comment]
`<%= JSON.stringify( htmlWebpackPlugin.options.configuration ) %>`

**Comment by ala85** [comment]
Thanks Jan, that did the trick!

**Comment by jantimon** [comment]
You should probably use the define plugin for this ;)

**Comment by borm** [comment]
Same problem, but i have using handlebars,
need help, i have created `helper`
```js
module.exports = function(object) {
  return JSON.parse(JSON.stringify(object, null, 2));
};
```
then 
```{{jsonStringify htmlWebpackPlugin.options. configuration}}```

but in output i see `&quot;`
