### ISSUE TITLE
Html file is output with "[hash]" instead of the actual hash

### ISSUE THREAD

**Issue by noahmonster** [ampedandwired/html-webpack-plugin#399]
Hi,

I have Webpack set up to output to a folder in `dist` with the hash of my application (`output.path: "/dist/[hash]"`).  Typically it will be something like `dist/e976ab2b800ec3216da8`.  I want my `index.html` to live outside of this folder (in `dist`) and reference the `app.js` and `app.css` that are inside of the folder.

It looks something like this
```
app/
  dist/
    index.html
    e976ab2b800ec3216da8/
      app.js
      app.css
      ...
```

Below is the output in `dist/index.html`.  Notice the **[hash]** in both of the includes.  This is almost exactly what I want.  I just need the **[hash]** to be replaced with the actual hash that was created by Webpack.
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>MyApp</title>
  <link href="[hash]/app.css" rel="stylesheet"></head>
  <body>
  <script type="text/javascript" src="[hash]/app.js"></script></body>
</html>
```

Here are the relevant sections of my `webpack.config.js`
```
module.exports = {
  entry: {
    app: "./index/app.js",
  },

  output: {
    filename: "[name].js",
    chunkFilename: "[name].js",
    path: __dirname + "/dist/[hash]"
  },

  plugins: [
    ...
    new HtmlWebpackPlugin({title: 'MyApp', filename: __dirname + "/dist/index.html"})
  ],

...
}
```

Do I have the config wrong or is this a bug?

**Comment by kellycampbell** [comment]
I'm seeing a similar problem, but only for a favicon file which I specified in the HtmlWebpackPlugin options. My other files are included in the index.html correctly with the appropriate hash.

```javascript
  output: {
    path: path.join(__dirname, 'dist/release/' + VERSION +'-[hash]/'),
    publicPath: VERSION + '-[hash]/',
    filename: '[name].' + VERSION + '-[hash].js'
  },
```

```javascript
    new HtmlWebpackPlugin({
      'title': 'My App Title',
      'favicon': 'client/img/favicon-32x32.png'
    })
```

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>My App Title</title>
  <link rel="shortcut icon" href="2.0.0-[hash]/favicon-32x32.png"></head>
  <body>
  <script type="text/javascript" src="2.0.0-1af3ef89ddc3dd8e0ebb/main.2.0.0-1af3ef89ddc3dd8e0ebb.js"></script></body>
</html>
```

**Comment by chrillo** [comment]
@kellycampbell just submitted a pull request that solves this issue for me https://github.com/ampedandwired/html-webpack-plugin/pull/441 its only a one liner until it gets merged

**Comment by jantimon** [comment]
Moved to #441

**Comment by noahmonster** [comment]
@jantimon This does not fix the original issue.  I pulled the latest and tried the example above and got the same result.  The index.html still has the "[hash]" as part of the path.

The fix above appears to only be for the "public path", where I was using the "path".
