### ISSUE TITLE
"templateContent" & Handlebars — Blueimp works simultaneously and parses {% %}

### ISSUE THREAD

**Issue by stas-webwork** [ampedandwired/html-webpack-plugin#40]
webpack.config.js [plugins]:
```javascript
new HtmlWebpackPlugin({
	templateContent: function(templateParams, webpackCompiler) {
		var hbs = require(path.resolve('./app/src/index.hbs'));
		return hbs(templateParams);
	}
})
```

**Comment by jantimon** [comment]
The webpack.config.js code is not executed in webpack context but in node context.
Because of that it's not possible to use webpack loaders for now.

There is work in progress for one of the future releases.

**Comment by stas-webwork** [comment]
jantimon, I'm afraid that you misunderstood me. 
I would like to draw your attention to the fact that the Blueimp **works in parallel** with Handlebars in the "templateContent". Blueimp parses `{% %}` anyway.
I mean that Blueimp should not work when I use "templateContent" with another template engine.
The context is not to blame.
Thanks.

**Comment by jantimon** [comment]
I know - sorry I thought it was because handlebars didn't parse it correctly.  
If you provided a templateContent string it might also be a template therefore it is also compiled with the blue imp template. #41 adds the new option `compile` which allows you turn of the blueImp compilation.
