### ISSUE TITLE
Fallback template engine documentation error.

### ISSUE THREAD

**Issue by romulof** [ampedandwired/html-webpack-plugin#400]
In the docs you say that the library has a _"fallback ejs loader"_, but when I tries to use EJS' "new line slup" features it failed.

Internally it uses `lodash.template`. The syntax is almost the same, but lacks several features.

Edit: Or I might be mistaken and EJS is a standard with several implementations. The one I was mentioning is this one: https://github.com/mde/ejs

**Comment by jantimon** [comment]
Hm we could change it to `ejs/lodash` loader or sth.. you can use this plugin with the https://github.com/bazilio91/ejs-compiled-loader if you need the line slurp feature.

**Comment by romulof** [comment]
I've read about it. Very cool this plugin supporting other loaders, but for me it's not worth adding a new dependency just to clean some whitespace.

Thanks.

**Comment by jantimon** [comment]
Cool 👍
