### ISSUE TITLE
data-attribute string is being transformed (Fontastic)

### ISSUE THREAD

**Issue by TaeKimJR** [ampedandwired/html-webpack-plugin#402]
**Issue**
When sending my code through the html-webpack-plugin, I'm seeing my data-icon's attribute value being transformed.

**Example**
_In code..._
`<span data-icon="&#xe019;" />`

_Output_
<img width="527" alt="screen shot 2016-08-14 at 12 46 30 pm" src="https://cloud.githubusercontent.com/assets/6180804/17651132/268d05b2-621d-11e6-9597-775d0df1ae7a.png">

The string in my code is set to "&#xe019;" but is outputted as "î€š".

**Webpack Configuration**
```
new HtmlWebpackPlugin({
  template: 'index.ejs'
})
```

**Do I need to set some configuration to not transform my data attributes?**

**Comment by jantimon** [comment]
Hi could you find out why this is happening?
