### ISSUE TITLE
Is the execution asychronous?

### ISSUE THREAD

**Issue by fuckingdigital** [ampedandwired/html-webpack-plugin#405]
Hey,
thanks for developing such a great plugin!

ISSUE:
I have html-webpack-plugin and copy-webpack-plugin installed.
I was aiming to copy static files to distribution folder in production mode.
It does....but the header.php and folder.php are most of the time empty files.
Is there a timing problem?
Can I make sure that those files are written before copy-webpack-plugin is executed?

Thanks for your help!

```js
plugins: [
        new ExtractTextPlugin('css/[name].css?[hash]'),
        new webpack.ProvidePlugin({
            $: "jquery"
        }),
        new HtmlWebpackPlugin({
            chunks: ['atf'],
            template: path.resolve(__dirname, sourcePath + '/includes/header.ejs'),
            filename: path.resolve(__dirname, sourcePath + '/includes/header.php'),
            inject: false
        }),
        new HtmlWebpackPlugin({
            chunks: ['main'],
            template: path.resolve(__dirname, sourcePath + '/includes/footer.ejs'),
            filename: path.resolve(__dirname, sourcePath + '/includes/footer.php'),
            inject: false
        }),
        (PRODUCTION ?
            new CopyWebpackPlugin([{
                from: path.resolve(__dirname, sourcePath),
                to: path.resolve(__dirname, distPath)
            }], {
                ignore: [
                    {
                        glob: ".tmp/**/*",
                        dot: true
                    },
                    "*.ejs",
                    {
                        glob: "assets/**/*",
                        dot: true
                    }
                ]
            }) :
            function () {}),
    ],
```

**Comment by fuckingdigital** [comment]
Don’t know why the old header.php and footer.php in the distribution folder did not update (although the last altered time said different)?
My solution was to empty the distribution folder before webpack execution — then it worked.

Like so:
```
rm -r app/dist/*

NODE_ENV=production ./node_modules/.bin/webpack -p --progress || exit
```

**Comment by fuckingdigital** [comment]
That was not the solution...
Sometimes the files are still empty.

What can be the reason...any ideas?

**Comment by jantimon** [comment]
Sorry I don't have the time right now to investigate your setup and the copy-webpack-plugin.
Are you using the Webpack-Dev-Server? Because it writes to memory and not to file system.

**Comment by fuckingdigital** [comment]
Hey @jantimon ,
thanks for your quick reply.
I am using the php build-in server.
In development mode everything is fine. But when I start to build the project for production the error occurs — so maybe it’s the combination of html-webpack-plugin and copy-webpack-plugin.
I will dig deeper and keep you informed :)

**Comment by jantimon** [comment]
Can I close this?

**Comment by fuckingdigital** [comment]
Hm...it’s still an issue, but I did not find out where it comes from.
Your decision.

**Comment by danchristian** [comment]
This is still an issue for me. I clear out the `dist` folder and `npm run dev` and it errors with `ERROR in [copy-webpack-plugin] unable to locate '/dist/app.html'. If I `npm run dev` again, then it works, as obviously the files are in the `dist` folder at that point.

The plug-ins are in correct order in the `webpack.config` file

```
const HtmlWebpackPlugin = require('html-webpack-plugin');
const CopyWebpackPlugin = require('copy-webpack-plugin');
```

I am not running `Webpack-Dev-Server`.

Is there a way to specify to run one plug-in specially after another has finished?
