### ISSUE TITLE
Choose where to inject

### ISSUE THREAD

**Issue by cecilphillip** [ampedandwired/html-webpack-plugin#407]
I'm using the inject option to place scripts  at the bttom of my custom template. Now my template also has some server side templating included which allows child pages to inject their own scripts into the page.

Is it possible to indicate exactly where in the template to inject the bundled scripts ?

**Comment by jantimon** [comment]
No but you could use your custom template and inject the scripts yourself:

https://github.com/jaketrent/html-webpack-template/blob/master/index.ejs#L56-L58

**Comment by evanjmg** [comment]
Can I do this with just .html? I just want my bundle just after my view in my body - not at the end.

**Comment by IronSean** [comment]
I also am confused how this works, and that link no longer appears to point to the relevant code, nor does the code in tag v4.1.0 (which is the closest version to the date of this I can find) seem to explain it.
