### ISSUE TITLE
return a javascript template instead of html

### ISSUE THREAD

**Issue by salzhrani** [ampedandwired/html-webpack-plugin#408]
The goal is to return a javascipt function that uses template strings that can be used serverside to generate the html. currently my template is like
```js
module.exports = function (compilationResult) {
	return `
	module.exports = (title, url, body) =>
	\`<!doctype html>
	<html lang="en">
		<head><title>\${title || 'Website'}</title>
			    <script src="\${url}">
		</head>
		<body>\${body}</body>
		</html>`
```
which returns the desired javascript template but with an `html` file extension. When I change the `filename` to have a `.js` extension gives the following error:
```html
Html Webpack Plugin:
<pre>
  Error: Child compilation failed:
  template.js from UglifyJs
  Unexpected character '`' [template.js:64,8]
  template.js from UglifyJs
  Unexpected character '`' [template.js:64,8]
  
  - compiler.js:76 
    [droplet-react2]/[html-webpack-plugin]/lib/compiler.js:76:16
  
  - Compiler.js:248 Compiler.<anonymous>
    [droplet-react2]/[webpack]/lib/Compiler.js:248:10
  
  - Compiler.js:437 
    [droplet-react2]/[webpack]/lib/Compiler.js:437:12
  
  - Tapable.js:81 next
    [droplet-react2]/[webpack]/[tapable]/lib/Tapable.js:81:11
 ...
```
not sure how to fix it.

**Comment by jantimon** [comment]
If you name a template javascript it expects you to provide a valid javascript render function and it seems like it doesn't understand ES6 template strings in your case

**Comment by jantimon** [comment]
You should rather set the output filename to `.js` instead of the input filename

**Comment by salzhrani** [comment]
currently this works fine but returns `index.html`
```js
new HtmlWebpackPlugin({
			template: 'app/template.js',
			minify: false,
			production: true,
			inject: false,
		}),
```
but when I change it to 
```js 
new HtmlWebpackPlugin({
			template: 'app/template.js',
			filename: 'template.js',
			minify: false,
			production: true,
			inject: false,
		}),
```
I get the mentioned error

**Comment by jantimon** [comment]
@salzhrani Could you find a solution?

**Comment by jonathanasquier** [comment]
If this can help anyone:
I use babel-register and named my webpack config `webpack.config.babel.js` to enable JSX in my template

I have a template
```
import React, { PropTypes } from 'react';

const Html = ({
  favicon = './favicon.ico',
  title,
  body,
  stylesheet,
  bundle,
}) => (
  <html lang='en'>
    <head>
      <meta charSet='utf-8' />
      <meta httpEquiv='X-UA-Compatible' content='IE=edge' />
      <meta name='viewport' content='width=device-width, initial-scale=1' />
      <title>{title}</title>
      {favicon ? <link rel='shortcut icon' href={favicon} /> : null}
      {stylesheet ? <link rel='stylesheet' href={stylesheet} /> : null}
    </head>
    <body>
      <div id='root' dangerouslySetInnerHTML={{ __html: body }} />
      {bundle ? <script src={bundle} /> : null}
    </body>
  </html>
);

Html.propTypes = {
  title: PropTypes.string,
  bundle: PropTypes.string,
  body: PropTypes.string,
  favicon: PropTypes.string,
  stylesheet: PropTypes.string,
};

export default Html;
```

and a template renderer
```
const React = require('react');

import { renderToStaticMarkup } from 'react-dom/server';
import Html from './template.js';

const renderDocumentToString = props =>
  '<!doctype html>' + renderToStaticMarkup(<Html {...props} />);

module.exports = function(props) {
 // if there is a better way feel free to mention me
  return renderDocumentToString(props.htmlWebpackPlugin.options);
};
```

then I use html webpack plugin this way
```
  plugins: [
    new HtmlWebpackPlugin({
      filename: 'index.html',
      template: './templateRenderer.js',
      title : 'Webpack is hard'
    }),
  ],
```

output
```
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Webpack is hard</title>
  <link href="/f3732d5888fd108d1dc9.style.css" rel="stylesheet">
</head>

<body>
  <div id="root"></div>
 <script type="text/javascript" src="/f3732d5888fd108d1dc9.app.js"></script>
</body>

</html>
```

**Comment by calumjames** [comment]
@jonathanasquier, do you remember how your Webpack config looked for the stylesheet when you did that React server-side rendering example? I'm doing pretty much the same thing and I'm seeing errors.

When I try to use a simple config for bundling CSS using ExtractTextPlugin, I see the following error:
> [...] loader is used without the corresponding plugin

And when I try to use a simple config that just uses style-loader and css-loader without ExtractTextPlugin, I see the following error:
> ReferenceError: window is not defined

That error seems to be coming from my template renderer file/the internals of HtmlWebpackPlugin.

I've included the path to the template renderer in my babel-loader config, and my css-loader config is simply as follows:
> ```
{
    test: /\.css$/,
    include: [testingPath],
    use: ['style-loader', 'css-loader']
}
```
`testingPath` is simply the full path to a CSS file I'm trying to have bundled in my resulting index.html just to get this working.

**Comment by calumjames** [comment]
@jonathanasquier, @jantimon, I've created [this StackOverflow question](https://stackoverflow.com/questions/48547833/error-when-importing-scss-in-a-react-component-rendered-using-htmlwebpackplugin), linking to an example repo I created that exhibits the problem. That seemed best, after a further investigation today.

**Comment by jonathanasquier** [comment]
:/ personally I moved on to next.js to get these kind of issues handled for me... But I remember having window is not defined issues when my webpack target wasn't well defined. I think my implem used webpack@1 so you probably have completely different issues on your side. I haven't touched this code in a while and might not be of any help sorry!
