### ISSUE TITLE
Uncaught Error: only one instance of babel-polyfill is allowed

### ISSUE THREAD

**Issue by meleyal** [ampedandwired/html-webpack-plugin#409]
Upgrading from `1.7.0` to `2.22.0` I now see the following error when loading index.html:

```log
Uncaught Error: only one instance of babel-polyfill is allowed
```

**Comment by jantimon** [comment]
Could you please try to reproduce it with an as minimalistic webpack configuration as possible an post that configuration to this issue?

**Comment by meleyal** [comment]
Apologies, I think this was down to not setting `inject: false` as my template already included the script tags, so the scripts were being loaded twice.
