### ISSUE TITLE
Can't use other preLoaders with the built in fallback lodash loader

### ISSUE THREAD

**Issue by timmfin** [ampedandwired/html-webpack-plugin#411]
I was playing around with a custom loader that does some persistent caching for webpack, and I ran into some trouble with [this code in html-webpack-plugin](https://github.com/ampedandwired/html-webpack-plugin/blob/8b79742f6f944720cb63822551508bf48173d971/lib/loader.js#L15-L18):

```js
  // This loader shouldn't kick in if there is any other loader
  if (allLoadersButThisOne.length > 0) {
    return source;
  }
```

The problem is that I did have another loader, but it was only a preloader and is _not_ a HTML -> JS transformation (my preloader would return HTML source still). But as currently written, I cannot have any other loaders when using html-webpack-plugins fallback loader (and I don't see any way this loader can know if another loader in the list is a preloader or not).

Do you think it is reasonable to make the `allLoadersButThisOne` check configurable? It would be nice to still be able to use the fallback loader alongside my preloader. (I looked at using other loaders that do lodash/underscore template compilation, but I was suspicious they wouldn't work with webpack 2 [due to `with` not being "unwrapped"](https://github.com/ampedandwired/html-webpack-plugin/blob/8b79742f6f944720cb63822551508bf48173d971/lib/loader.js#L28-L32)). Even if I need to have explicit loader configuration in my `webpack.config.js` with a `?allowOtherLoaders=true` query param set, that would be 👍  in my book (as opposed to copying and making my own version of `loader.js` that works with webpack 2).

ps: This only came up in my initial testing, so isn't very urgent for me. But it is possible I'll need to find some way to address it in the future (in other words, if the maintainers think this is something useful I likely would be able to take a stab at a PR eventually).

**Comment by jantimon** [comment]
Well we could add a force option to the loader but I guess it would be even better if the lodash ejs and underscore loaders work for webpack 2
