### ISSUE TITLE
Unable to escape output for HTML attributes

### ISSUE THREAD

**Issue by brianchirls** [ampedandwired/html-webpack-plugin#413]
I'm trying to escape output for use inside HTML attributes, where the value may include a quote, ampersand, etc. like so:

```ejs
<meta property="og:title" content="<%= htmlWebpackPlugin.options.title %>" />
```

According to the EJS documentation (and an old [issue](https://github.com/ampedandwired/html-webpack-plugin/issues/117) here), the `<%= '...' %>` delimiter should escape the output, but it does not do that here. According to the [lodash template documentation](https://lodash.com/docs#template), I can escape the output by using a `<%-` delimiter, but if I do that in my template, I get the following error:

```
ERROR in Template execution failed: ReferenceError: _ is not defined
ERROR in   ReferenceError: _ is not defined
```

Is there a way to get this to work here? Or is this a bug that needs fixing? Thanks.

**Comment by jantimon** [comment]
Hey the template is generated here:

https://github.com/ampedandwired/html-webpack-plugin/blob/master/lib/loader.js#L35-L50

Maybe we could extend it with `var _ = require("lodash");` - would that fix your problem?

**Comment by brianchirls** [comment]
Why is this closed? I feel like if use of a documented feature results in a crash with a cryptic error message, that's a bug worth investigating.

My code does not make explicit reference to `_`. I'm guessing that the missing reference is a result of some code generated by this plugin or one of its dependencies. I'd offer to dig deeper, but I'm not familiar enough with the code in question.

I have managed a workaround to explicitly require `lodash.escape` and run my variables through that function. But it kind of defeats the purpose of a template. And it won't prevent others from running into the same problem. So I'd hope this could be solved, or at least have the documentation updated to reflect that this plugin does not support that syntax.

Thanks

**Comment by jantimon** [comment]
It was closed because of inactivity and no responds to my question..

**Comment by brianchirls** [comment]
I'm sorry I wasn't able to get to it right away. Can we re-open now please?

**Comment by jantimon** [comment]
Sure - could you please debug a little bit why this is happening?

**Comment by jantimon** [comment]
Maybe you could log the result here to see what's happening behind the scenes:

https://github.com/ampedandwired/html-webpack-plugin/blob/master/lib/compiler.js#L98

and as mentioned before here (where the templating happens):

https://github.com/ampedandwired/html-webpack-plugin/blob/master/lib/loader.js#L35-L50

**Comment by jantimon** [comment]
Closed because of inactivity
