### ISSUE TITLE
Ability to run in a /vdir out of the box.

### ISSUE THREAD

**Issue by lnaie** [ampedandwired/html-webpack-plugin#414]
Out of the box, webpack.common.js misses the ability to run in a virtual dir. This will do the trick for IIS:
```
  /*
   * Options affecting the output of the compilation.
   *
   * See: http://webpack.github.io/docs/configuration.html#output
   */
  output: {
    publicPath: METADATA.baseUrl
  },
```
I have't checked it on Apache or related.

It will prefix properly the scripts (via HtmlElementsPlugin) in index.html. Also it will work fine with the default structure of METADATA constants:
```
/*
 * Webpack Constants
 */
const METADATA = {
  title: 'Angular2 Webpack Starter by @gdi2290 from @AngularClass',
  baseUrl: '/vdir/',
  isDevServer: helpers.isWebpackDevServer()
};
```

Thanks

**Comment by jantimon** [comment]
👍
