### ISSUE TITLE
Getting contents of the resulting html file

### ISSUE THREAD

**Issue by le0nik** [ampedandwired/html-webpack-plugin#416]
In my `bundle` I create an `iframe` dynamically and set it's contents to the source of the `html` file(which has links to the resulting `css` and `js` files from another entry file.

To do this I replace an identifier with the source of html file

```js
{
  entries: {
    bundle: {
    },
    iframe: {
    }
  },
  plugins: [
    new HtmlPlugin({
      template: join(PATHS.iframe, 'views/iframe.ejs'),
      filename: join(PATHS.dist, 'iframe.html'),
      inject: false,
      chunkSortMode: 'dependency',
      chunks: ['iframe'],
    }),
  ]
```

In the `bundle`:
```js
// create iframe
const doc = iframe.contentDocument;
doc.open();
doc.write(process.env.IFRAME_HTML);
```

then i replace this string with the source of `iframe.html`.

Right now I do it with this plugin:

```js
    {
      /**
       * @param {Compiler} compiler
       */
      apply(compiler) {
        compiler.plugin('done', () => {
          const iframeHtml = fs.readFileSync(join(PATHS.dist, 'iframe.html')).toString('utf-8');

          replaceInFile.sync({
            files: [join(PATHS.dist, '/**/*.js')],
            replace: /process\.env\.IFRAME_HTML/g,
            with() {
              return `"${iframeHtml}"`;
            },
          });
        });
      },
    },
```

It works for production build, but doesn't work with `webpack-dev-server`, obviously. I think I should perform the replacement on an earlier stage of the compilation, but it's not clear on which one, because `html-webpack-plugin` uses a child compiler.

At what point can I do this? When does `html-webpack-plugin` emit the html file?

Or is there another way to achieve it, besides creating a separate build step for the iframe?

Thank you!

**Comment by jantimon** [comment]
You can use a html-webpack-plugin event

**Comment by le0nik** [comment]
This is exactly what I needed. Completely forgot about this section in the README. Thank you!

**Comment by le0nik** [comment]
I wrote a plugin based on `html-webpack-plugin-after-emit` event, but this event isn't emitted, when i use it with `webpack-dev-server`, because there is this check https://github.com/ampedandwired/html-webpack-plugin/blob/8b79742f6f944720cb63822551508bf48173d971/index.js#L84.

**Comment by jantimon** [comment]
You would have to disable the cache

**Comment by le0nik** [comment]
Thank you, again. And sorry for the trouble. Again. :)
