### ISSUE TITLE
Feature: Eval comment blocks of js. 10x-20x speed perf.

### ISSUE THREAD

**Issue by TheLarkInn** [ampedandwired/html-webpack-plugin#417]
This is really here for me to track as I think it can be something html-webpack-plugin can be leveraged for. https://twitter.com/samccone/status/771838938843484161

**Comment by TheLarkInn** [comment]
@jantimon it's worth an RFC/Proposal

**Comment by NekR** [comment]
It probably can be done with `<script type="script/lazy">${ code }</script>` which shouldn't parse the code with JS engine.

**Comment by TheLarkInn** [comment]
Really? 

We should definitely spike this out.

**Comment by TheLarkInn** [comment]
@samccone would that work?

**Comment by jantimon** [comment]
That would work. However it would not allow to cache the JavaScript

**Comment by TheLarkInn** [comment]
Hmm. Interesting, so app code is usually not cacheable, that typically hits first, or is critical render. Maybe that's the use-case?

**Comment by NekR** [comment]
Well, if you cache in SW/AppCache you (mostly, but in thus case completely) don't care if it's cached in HTTP Cache or not.

**Comment by samccone** [comment]
@jantimon you can ship the code via the network  just wrap your JS in a comment block. then when you want to eval it strip the /* and eval() :)

**Comment by NekR** [comment]
@samccone hmm.. what is the point then? If by "over network" you assume XHR, then script could be simply loaded as a string and evaled when needed. In this case, this isn't related to html-plugin, but rather to bundle/module loader.

**Comment by TheLarkInn** [comment]
I was taking the articles example, where the tags are wrapped in the content and not how @samccone just described it.

Get Outlook for iOS<https://aka.ms/o0ukef>




On Sat, Sep 3, 2016 at 3:07 PM -0500, "Arthur Stolyar" <notifications@github.com<mailto:notifications@github.com>> wrote:


@samccone<https://github.com/samccone> hmm.. what is the point then? If by "over network" you assume XHR, then script could be simply loaded as a string and evaled when needed. In this case, this isn't related to html-plugin, but rather to bundle/module loader.

-

**Comment by jantimon** [comment]
I guess it would be best to move this into a new plugin.

**Comment by TheLarkInn** [comment]
Alright, I'll get something whipped up and do so. Feel free to close.

**Comment by jantimon** [comment]
I guess the `html-webpack-plugin-alter-asset-tags` event would be perfect for that.
