### ISSUE TITLE
output as ejs

### ISSUE THREAD

**Issue by andyfenelon** [ampedandwired/html-webpack-plugin#422]
is there anyway to output as ejs ? for a universal app, would be great to output and ejs file with the hashed filenames. i see you can use custom templates but they all seem to render as .html

**Comment by jantimon** [comment]
This module uses a `ejs` loader as fallback - so you would have to load your template with another loader e.g. a raw loader:

```
{
   template: '!!raw!template.ejs',
```

**Comment by andyfenelon** [comment]
thanks.

**Comment by aarshaw** [comment]
Trying to do the same thing but this isn't working for me:
```
new HtmlWebpackPlugin({
  template: '!!raw-loader!index.ejs'
})
```
This is still just outputting the a .html file in the output directory, any thoughts?
