### ISSUE TITLE
[question] How to use html-webpack-plugin with express jade view engine?

### ISSUE THREAD

**Issue by es6Test** [ampedandwired/html-webpack-plugin#430]
How to use html-webpack-plugin with existing express templates?

I've installed the express-generetor npm module and like how the project is structured with the jade files used as views using the express view engine. However I also like to use the HTML-webpack-plugin which generates its own files, what is the best way to go about integrating both approaches?

**Comment by jantimon** [comment]
Please move this question to stackoverflow :)

**Comment by HarrisRobin** [comment]
@jantimon , sorry to re-open this but that question is on stackoverflow with no response:
http://stackoverflow.com/questions/39501555/how-to-use-html-webpack-plugin-with-existing-express-templates

After a lot of searching, I can't find a definitive answer on whether this is even possible. Any chance we could get a hint or a definitive no? Been trying to get this work for a few hours now and I can't get this to work at all with express view engine 😅 It works perfectly if you just need to inject in a public index.html file. 

Right now my only workaround is to go back to using gulp just for this specific part :(

**Comment by jantimon** [comment]
I don't have the time right now to dive into the express generator so I can't help you on that. Sorry :(
