### ISSUE TITLE
Window is not defined VERSION 2.22.0

### ISSUE THREAD

**Issue by kevincaradant** [ampedandwired/html-webpack-plugin#432]
Since i upgraded in the version 2.22.0. I get this error. 
I get this:

```
Html Webpack Plugin:
  ReferenceError: window is not defined
  
  - index.html:551 Object.
    C:/Users/kevin/Documents/Projets/web-template-webpack/lib/index.html:551:2
  
  - index.html:519 __webpack_require__
    C:/Users/kevin/Documents/Projets/web-template-webpack/lib/index.html:519:30
  
  - index.html:542 
    C:/Users/kevin/Documents/Projets/web-template-webpack/lib/index.html:542:37
  
  - index.html:545 
    C:/Users/kevin/Documents/Projets/web-template-webpack/lib/index.html:545:10
  
  - index.js:225 HtmlWebpackPlugin.evaluateCompilationResult
    [web-template-webpack]/[html-webpack-plugin]/index.js:225:26
  
  - index.js:115 
    [web-template-webpack]/[html-webpack-plugin]/index.js:115:21
  
  - From previous event:
  
  - index.js:108 Compiler.
    [web-template-webpack]/[html-webpack-plugin]/index.js:108:8
  
  - Tapable.js:71 Compiler.applyPluginsAsync
    [web-template-webpack]/[tapable]/lib/Tapable.js:71:13
```

I don't know if it's the same issue but if I apply the fix here
[https://github.com/ampedandwired/html-webpack-plugin/issues/212](212)
The last comment in the issue 212 is mine .

I get this error:
```
ERROR in ./lib/index.ejs
Module parse failed: C:\Users\template\lib\index.ejs Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:0)
```

Thank you in advance

**Comment by jantimon** [comment]
This issue was always caused by a misconfigured webpack configuration..
It says that for some reason (prelaoder, loader or postloader configuration) the fallback handler doesn't take over and you have to specify a custom loader for the template.

**Comment by kevincaradant** [comment]
ok thank you, so what's wrong with this configuration ? It's the same with the version 1.7.0. I don't understand why there is a misconfigured webpack configuration.:

```
var path = require('path'),
webpack = require('webpack'),
libPath = path.join(__dirname, 'lib'),
nodeModulesPath = path.join(__dirname, 'node_modules'),
HtmlWebpackPlugin = require('html-webpack-plugin'),
ProgressBarPlugin = require('progress-bar-webpack-plugin'), // To be delete when webpack will accept the flag --progress in the devserver and not only in CMD
WatchIgnorePlugin = require('watch-ignore-webpack-plugin'),
SassLintPlugin = require('sasslint-webpack-plugin');

var cf = {
	entry: path.join(libPath, 'index.js'),

	devtool: 'source-map',

	resolve: {
		root: [path.resolve(__dirname, 'lib'), path.resolve(__dirname, 'node_modules')],
		extensions: ['', '.js', '.json', '.scss']
	},

	debug: true,

	cache: false,

	module: {
		loaders: [{
			test: /\.json$/,
			exclude: /node_modules/,
			loaders: ["raw-loader"]
		},{
			test: /\.html$/,
			exclude: /node_modules/,
			loader: 'ngtemplate!html'
		},{
			test: /\.(jpe?g|gif|png|svg|woff|woff2|ttf|eot|wav|mp3)$/,
			loader: 'file' // inline base64 URLs for <=10kb images, direct URLs for the rest
		},{
			test: /\.less$/,
			exclude: /node_modules/,
			loaders: ['style', 'css', 'less?sourceMap', 'resolve-url']
		},{
			test: /\.scss$|\.css$/,
			exclude: /node_modules/,
			loaders: ['style', 'css-loader', 'resolve-url', 'sass?sourceMap']
		},{
			test: /\.js$/,
			exclude: /node_modules/,
			loaders: ['ng-annotate?add=true&map=true', 'babel', 'eslint-loader']
		}]
	},

	eslint: {
		configFile: './.eslintrc'
	},

	devServer: {
		port: 3001,
		https: false,
		inline: true,
		compress: true,
		hot: true,
		open: true,
		noInfo: true
	},

	plugins: [
		new HtmlWebpackPlugin({
			inject: true,
			filename: 'index.html',
			title: 'MY_CUSTOM_APP',
			template: path.join(libPath, 'index.html')
		}),

		new webpack.optimize.OccurenceOrderPlugin(),

		new webpack.optimize.DedupePlugin(),

		new webpack.HotModuleReplacementPlugin(),

		new WatchIgnorePlugin([
			path.resolve( __dirname, './examples/'),
			path.resolve(__dirname, './node_modules/'),
		]),

		new SassLintPlugin({
			glob: 'lib/**/*.s?(a|c)ss',
			ignorePlugins: [
				'extract-text-webpack-plugin'
			],
			configFile: '.sass-lint.yml'
		}),

		new ProgressBarPlugin({format: '  build [:bar] ' + (':percent') + ' (:elapsed seconds)'})
	]
};

module.exports = cf;
```

**Comment by jantimon** [comment]
https://github.com/ampedandwired/html-webpack-plugin/blob/master/docs/template-option.md

**Comment by kevincaradant** [comment]
So if I understand, when i write` loader:html,` it's refered to this point -> 3) Setting a loader using the module.loaders syntax and more explicitly to -> This will cause html minification and it will also disable the ejs fallback loader. So i can't use html loader ?

**Comment by jantimon** [comment]
It's just an example - in your case it is even worse you are using the ngTemplate loader which needs the `window` object. Just rename the template extension to `.ejs` or exclude it from the loader.

**Comment by kevincaradant** [comment]
You say: " rename the template extension to .ejs or exclude it"  but it's already that i tried to do with index.html ?? I have to do for every files .html which are the templates for my directives etc ? .ejs it's only for the back-end as you say me in the first post no ?

**Comment by jantimon** [comment]
Only change it for the html-webpack-plugin not for the angular code

**Comment by kevincaradant** [comment]
OK I'm very sorry but to finish with this error, write some code please. Take a time when you be able to to look and say me what have I to change. I'm totally lost with your comments :/
My repository: [My repo](https://github.com/kevincaradant/web-template-webpack)
`git checkout dev`
Notice webpack.dev.js and index.html and index.config.html which import index.html to load it because my index page is a component. It's here where I'm lost .

thank you, sorry for the inconveniance ;)

**Comment by kevincaradant** [comment]
Do you have the time since the last month to look my repo, even quickly ? Because, really, I tried but nothing work ... Your library is the only one that I can't update directly with the `ncu -u`, I would like find a solution :). Thanks
