### ISSUE TITLE
Passing loader query parameters in template

### ISSUE THREAD

**Issue by freshprinze** [ampedandwired/html-webpack-plugin#436]
Hi

I am using pug-loader in my webpack config. When I try to do the following in the config it fails.

			new HtmlWebpackPlugin({
				title: METADATA.title,
				template: '!!pug-loader?pretty!./src/index.pug'
			})

But if I simply use the pug-loader without any query parameter all is working fine.

It seems it cannot parse '!!pug-loader?pretty!./src/index.pug', past ?.

The above still fails with the following template string

			'!!pug-loader?pretty=true!./src/index.pug'

I have attached the error log. 

[error.txt](https://github.com/ampedandwired/html-webpack-plugin/files/478739/error.txt)

**Comment by jantimon** [comment]
Looks like a pug loader issue - please ask them for advice
