### ISSUE TITLE
Help Wanted : Can not finish "npm run build"

### ISSUE THREAD

**Issue by blackcater** [ampedandwired/html-webpack-plugin#439]
node@6.6.0  npm@3.10.3
```
    "webpack": "^1.13.2"
    "pug-loader": "^2.3.0"
    "html-webpack-plugin": "^2.22.0"
    "extract-text-webpack-plugin": "^1.0.1"
```

I use it as usual. 

Part of the code as follow

![image](https://cloud.githubusercontent.com/assets/9465551/18758145/6bf55e6c-8129-11e6-888a-e8cf4c2c8a29.png)

```
    "build": "cross-env NODE_ENV=production webpack --progress --color"
```

But after I run the script and wait for a seconds, it hadn't been finished.

![image](https://cloud.githubusercontent.com/assets/9465551/18757985/b3247ea4-8128-11e6-9d8d-8f0ea74e1bd8.png)

What's wrong ?

**Comment by mesutyigit** [comment]
I got  Same issue. Did you resolve it ?

**Comment by leonardovillela** [comment]
I have the same issue...
