### ISSUE TITLE
Optmize "html-webpack-(before|after)-html-processing" handler

### ISSUE THREAD

**Issue by ascariandrea** [ampedandwired/html-webpack-plugin#440]
Hi guys,
I was developing my own plugin build on top of `html-webpack-plugin` following your documentation and I faced a problem and I would like to suggest a change.

When you have something like
```js
compilation.plugin('html-webpack-plugin-after-html-processing', (htmlPluginData, callback) => {
 htmlPluginData.html += 'My magic footer';
 callback(null, htmlPluginData);
});
```

I thought the used object was the one passed to `callback` and writing `htmlPluginData.html += 'My magic footer'` was just a shorthand, instead plugin is actually using the mutated object (which is bad) and then force the user to pass it to the callback in order to make it available to other plugins.

My simple suggestion is to avoid mutation in place, but returning a new instance of the object.
This could permit to write the above function like this

```js
compilation.plugin('html-webpack-plugin-after-html-processing', (htmlPluginData, callback) => {
 const html = htmlPluginData.html + 'My magic footer';
 callback(null, { ...htmlPluginData, html });
});

```

I could help you in this if you agree,

let me know :)

**Comment by jantimon** [comment]
Hi @ascariandrea 
thanks for your feedback.
Unfortunately there are reasons why we can't change it easily (maybe you got a solution):

1) the event is triggered using [webpack/tapable](https://github.com/webpack/tapable#applypluginsasync) so we can't change much about how return values are handled
2) a change would break backwards compatibility
3) I understand immutables but don't see the big win for this scenario

**Comment by ascariandrea** [comment]
Hi @jantimon 
I have a solution that don't break backwards compatibility and is compatible with `tapable`.

> 3) I understand immutables but don't see the big win for this scenario

Suppose you have an async function that modify your html in place:
```
htmlPlugin.html = addHtmlAsync(htmlPlugin.html);
```

and you define your `html-webpack-plugin-before-html-processing` callback as

```
compilation.plugin('html-webpack-plugin-after-html-processing', (htmlPluginData, callback) => {
 htmlPlugin.html = addHtmlAsync(htmlPlugin.html);
 callback(null);
});
```

what would happen?

I wouldn't let the user the possibility to mistake and I will give a strict, understandable and easy way to accomplish what they need.

**Comment by jantimon** [comment]
I don't understand your example - this would not be solved by your pull request.

Could you please also update the docs and readme and add an inline comment?

**Comment by jantimon** [comment]
Moved to #442
