### ISSUE TITLE
nesting templates using ejs

### ISSUE THREAD

**Issue by lonelydatum** [ampedandwired/html-webpack-plugin#443]
**Here is my code:**

webpack.config.js
`new htmlWebpackPlugin({
    template: 'template.ejs'
})`

template.ejs
`<html lang="en">
<% include head %>
<body></body>
</html>`

**This is the error I'm getting. Do I need to do something with lodash?**

> 
Html Webpack Plugin:
  Error: Child compilation failed:
  Module build failed: SyntaxError: Unexpected identifier
  
  - index.js:10809 
    [banner-boiler]/[ejs-loader]/[lodash]/index.js:10809:16
  
  - index.js:11082 
    [banner-boiler]/[ejs-loader]/[lodash]/index.js:11082:21
  
  - index.js:8152 
    [banner-boiler]/[ejs-loader]/[lodash]/index.js:8152:31
  
  - index.js:10808 Function.template
    [banner-boiler]/[ejs-loader]/[lodash]/index.js:10808:

**Comment by jantimon** [comment]
The fallback loader does not support include - please use a custom loader e.g. 

```js
new htmlWebpackPlugin({ template: '!!ejs-compiled-loader!template.ejs' })
```

https://github.com/bazilio91/ejs-compiled-loader

(don't know how well ejs-compiled-loader works but I hope you get the idea)

**Comment by lonelydatum** [comment]
works like a charm :) Thank you so much!
