### ISSUE TITLE
Template path resolution concept

### ISSUE THREAD

**Issue by daltones** [ampedandwired/html-webpack-plugin#445]
README says:
> `template`: Webpack require path to the template. Please see the docs for details.

Maybe that description is not very clear, or even not true.

I mean, you actually _can_ use loaders for the template (as webpack `require`s), but the current implementation resolves the template path to absolute path just relative to `context` option.

So when you say “Webpack require path to the template” I suppose it will actually use webpack's resolver and it will support root directories, aliases, extensions etc. from `resolve` option.

**Comment by jantimon** [comment]
That's true - it was necessary because of backwards compatibility

**Comment by jantimon** [comment]
Moved to #444
