### ISSUE TITLE
Partials To Load Partials Issue/Feature Request

### ISSUE THREAD

**Issue by mikeglowacki** [ampedandwired/html-webpack-plugin#448]
Hi guys, great job on this plugin. 
While playing with it I noticed that partial html snippets cant load other partials(or, am I missing something?). 

It would be great if this was supported since it would provide greater flexibility. 

Right now, and as far as I can say, only main template can load other html snippets via:
`<%= require('html!./partial.html') %>` 
However, if a partial.html tried to load another html snippet it does not work. 

Is there a way to make this work?

**Comment by jantimon** [comment]
See #443
