### ISSUE TITLE
Change path of assets

### ISSUE THREAD

**Issue by MatthewKosloski** [ampedandwired/html-webpack-plugin#449]
I'm using `webpack-dev-middleware` to serve my files in memory while I develop—with the `publicPath` property set to `static`.  When I compile a build, I send the minified CSS and JS to a `public` folder for production.  

_Here is an excerpt from config in the root of my project folder:_

    // ...
    output: {
        path: path.join(__dirname, 'public'),
        filename: 'js/[name].min.js',
        publicPath: '/static'
    },
    plugins: [
        new ExtractTextPlugin('css/[name].min.css', {allChunks: true}),
        new HtmlWebpackPlugin({minify: {collapseWhitespace: true}})
    ]
    // ...

_This gives me the following:_

	root-folder
		public
			css
				bundle.min.css
			js
				bundle.min.js
			index.html

_These are the asset paths in the outputted HTML:_

	<link href="/static/css/bundle.min.css" rel="stylesheet">
	<script type="text/javascript" src="/static/js/bundle.min.js">

_I want it to be:_

	<link href="./css/bundle.min.css" rel="stylesheet">
	<script type="text/javascript" src="./js/bundle.min.js">

This looks like a _very_ powerful Webpack plugin; thank you for making it and look forward to hearing back!

**Comment by jantimon** [comment]
Just set the publicPath to './'

**Comment by SevenOutman** [comment]
Here's a similar problem.

I want the directories to be:

    abc(root)
        static
            css
                bundle.min.css
            js
                bundle.min.js
        index.html

but the urls injected into the HTML file to be:

    <link href="/abc/static/css/bundle.min.css" rel="stylesheet">

I mean, how can I customize the urls?
This may be a common scenario when creating Github Pages _for a project_.

**Comment by gabrielmicko** [comment]
Example:
`
var buildPath = path.resolve(__dirname, 'public');
output: {
		path: buildPath, //Path where the bundle should be exported
		filename: 'js/bundle.[hash].js', //Filename
		publicPath: '/' //Where the js gets loaded from
	},
`
