### ISSUE TITLE
if templating blocks

### ISSUE THREAD

**Issue by andykais** [ampedandwired/html-webpack-plugin#451]
It would be helpful to be able to hide a `script` tag if the given templating variable is undefined.
```
<script src="<%= htmlWebpackPlugin.options.livereload %>"></script>
<!-- if livereload is empty, this yields -->
<script src=""></script>
```
my current workaround is to leave ambiguous blocks like this in my index.html template, and put a full tag `<script src="<%= htmlWebpackPlugin.options.livereload %>"></script>` in my htmlWebpackPlugin options.
```
<%= htmlWebpackPlugin.options.livereload %>
```

**Comment by jantimon** [comment]
Questions on the template engine is not related to this plugin - sorry.
The default underscore template engine supports `if` expressions already.
