### ISSUE TITLE
Unexpected behaviour when using multi key value pair entry points, chunks array and chunksSortMode

### ISSUE THREAD

**Issue by derekdon** [ampedandwired/html-webpack-plugin#453]
Webpack 2, and Plugin Version 2.22.0

If you have an entry point object with key value pairs:

```
const ENTRY = {
    b: './src/b.js'
    common: './common/src',
    vendor: './some/vendor.js',    
    app: './src/app/app.js',
    a: './src/a.js'
}
```
I would expect the chunks  array in the plugin to define the insertion order in the template, but that isn't the case. The order of the chunk names in the plugin's chunks array has no effect when chunksSortMode none is used.

```
new HtmlWebpackPlugin({
            template: 'src/index.html',
            filename: 'index.html',
            chunksSortMode: 'none',
            chunks: ['vendor', 'common', 'app']
        }),
```

This to me seems counterintuitive. I expect the chunk names to define insertion order in this case.

**Comment by jantimon** [comment]
The chunks array is only for exclusive filtering.
Why should sortMode `none` sort?

**Comment by derekdon** [comment]
@jantimon Thanks for your response.

 "The chunks array is only for exclusive filtering" - This wasn't clear to me from reading the docs. I wrongly assumed that chunks array and chunksSortMode were related. So with 'none', I didn't expect any sorting...

I expected:

```
chunksSortMode: 'none',
chunks: ['vendor', 'common', 'app']
```

...to result in

```
<script type="text/javascript" src="/vendor.bundle.js"></script>
<script type="text/javascript" src="/common.bundle.js"></script
<script type="text/javascript" src="/app.bundle.js"></script>
```
...because that's the order of the chunks names in the chunks array, combined with 'none'.

In my webpack output, these chunks are in a different order, and that's what it's actually working off.

```
...
chunk    {1} common.bundle.js (common) 219 kB {10} [initial] [rendered]
...
chunk    {4} app.bundle.js (app) 143 kB {7} [initial] [rendered]
...
chunk   {13} vendor.bundle.js (vendor) 7.6 MB [entry] [rendered]
```

So the chunks listed in the plugin's chunks array are just used the filter the above, but the order of those chunks remains the same as how they were outputted. I my case the entry object is dynamic and key value based. On each new HtmlWebpackPlugin object I'd hoped to be able to control the insertion of a select set of chunks in the order I had them listed in the chunks array.

I've written a very simply custom sort function to get the output I require.

```
    let chunks = ['vendor', 'common', 'app'],
        htmlPlugin = new HtmlWebpackPlugin({
           ...
            chunksSortMode: (a, b) => {
                let aIndex = chunks.indexOf(a.names[0]),
                    bIndex = chunks.indexOf(b.names[0]);
                return aIndex - bIndex;
            },
            chunks
        });
```

Cheers.
