### ISSUE TITLE
Compile included templates as HTML?

### ISSUE THREAD

**Issue by hidace** [ampedandwired/html-webpack-plugin#456]
Is this possible to compile included templates as HTML?

I have a project that uses Twig for templating. All the data in it is static, but I have separated out parts of the page within other twig files for clarity sake (otherwise there would be hundreds of lines of markup in one file). However, I can't figure out how to build my html and have the twig templates appear compiled as markup in the body of that file, rather, the html page still shows all of the includes.

Thanks!

**Comment by jantimon** [comment]
Sorry I don't really understand the question - but yes it is probably possible. Could you please move your question to stackoverflow and add a link to this thread?

**Comment by hidace** [comment]
Hi @jantimon , I've updated and hopefully clarified the question here: [http://stackoverflow.com/questions/39961020/how-to-handle-templating-with-webpack-and-html-webpack-text-plugin](http://stackoverflow.com/questions/39961020/how-to-handle-templating-with-webpack-and-html-webpack-text-plugin)

Thanks!

**Comment by deju** [comment]
@hidace  you can use [esj-render-loader](https://github.com/tracker1/ejs-render-loader).
