### ISSUE TITLE
xhtml option has no effect

### ISSUE THREAD

**Issue by simonedavico** [ampedandwired/html-webpack-plugin#458]
Configuring the plugin with the `xhtml` option set to `true` does not generate valid `xhtml` (`link` tags are still not closed) using the latest version published on npm (`2.22.0`).

**Comment by jantimon** [comment]
Actually it should work:
https://github.com/ampedandwired/html-webpack-plugin/blob/master/index.js#L497
https://github.com/ampedandwired/html-webpack-plugin/blob/master/index.js#L585

Can you try to debug it with some console log messages?

**Comment by simonedavico** [comment]
I agree, it should work. I checked the module downloaded by `npm` in my `node_modules` directory and the code is the same. 
I will try to add logs around, let's see if I can figure out what is happening.

Just to be 100% sure, is this the correct way to configure the plugin?

```javascript
  new HtmlWebpackPlugin({
    template: paths.client('index.html'),
    hash: false,
    favicon: paths.client('static/favicon.ico'),
    filename: 'index.html',
    inject: 'body',
    minify: {
      collapseWhitespace: false
    },
    xhtml: true
  })
```

**Comment by jantimon** [comment]
yes looks good 👍

**Comment by jantimon** [comment]
can I close this?

**Comment by Busata** [comment]
It doesn't work though, since voidTag & selfclosing tag options are missing from the link definition, the xhtml value ends up being ignored for <link>, so it won't close regardless of xhtml being true or false.

**Comment by helenadamsRA** [comment]
Hi, I'm still having this issue with version 2.30.1. Is there any work around available or plans to fix this? I'm attempting to run my application using Thymeleaf which requires files to be xml compliant.
