### ISSUE TITLE
High cpu usage

### ISSUE THREAD

**Issue by neves** [ampedandwired/html-webpack-plugin#459]
webpack-dev-server is consuming 20% cpu if HtmlWebpackPlugin is enabled.
Drops to 0.4% when disabled.
MacOS 10.11.6
Node 6.8.1

Test sample: https://gist.github.com/neves/60365da2c537f0c69bdae5113d421df3

**Comment by jantimon** [comment]
Does it stay at 20% or is that just during compilation?

**Comment by neves** [comment]
Stay all time

**Comment by jantimon** [comment]
Sorry I can't reproduce it with node 4.4 and node 6.5 using webpack@1.13.2 and webpack-dev-server@1.16.2
