### ISSUE TITLE
(bug): o variable is not working in template

### ISSUE THREAD

**Issue by kuldeepkeshwar** [ampedandwired/html-webpack-plugin#460]
I'm using `2.22.0` version.

index.html
```
<html>
<head>
  <title> {%=o.htmlWebpackPlugin.options.title%}</title>
</head>
</html>
```

webpack.config.js
```
plugins: [
    new HtmlWebpackPlugin({
      title:"my app",
      filename:"index.html",
      template: "src/index.html",
    })
  ]
```

after running the build , index.html still have  `{%=o.htmlWebpackPlugin.options.title%}` instead of `my app`

**Comment by jantimon** [comment]
2.22.0 doens't have `o`

**Comment by kuldeepkeshwar** [comment]
@jantimon I updated to `2.22.0` and use `<%= htmlWebpackPlugin.options.title %>`

output is still same. I'm using webpack `2.1.0-beta.22`
