### ISSUE TITLE
Indentation is off when script tag is inserted

### ISSUE THREAD

**Issue by kkslider** [ampedandwired/html-webpack-plugin#461]
Hey guys, 

Great work on this plugin. I added it to my project dependencies today and it works perfectly. The only issue I am having is that when the plugin inserts the `script` tag line into my EJS generated html file, it ends up looking like this:

`index.template.ejs`:
```
<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv="Content-type" content="text/html; charset=utf-8"/>
		<title>React App</title>
	</head>
	<body>
		<div id="root"></div>
	</body>
</html>
```

Generated `index.html` file:
```
<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv="Content-type" content="text/html; charset=utf-8"/>
		<title>React App</title>
	</head>
	<body>
		<div id="root"></div>
	<script type="text/javascript" src="/bundle.bd31465d.js"></script></body>
</html>
```

I use tab spacing but get the same result if I uses spaces. Help would be appreciated!

**Comment by jantimon** [comment]
Thats intended to save network traffic.

**Comment by kkslider** [comment]
@jantimon Can you elaborate?

**Comment by jantimon** [comment]
Sure - spaces are not needed to display the html page - so we skip them ;)

**Comment by kkslider** [comment]
@jantimon I see. I noticed the indentation was correct in some examples I saw so was wondering if I had some configuration wrong. Thanks for clarifying.

**Comment by Jorjon** [comment]
Is there a chance we can have a `followIndent` option for the plugin to respect the indentation when replacing the ending `</head>` and `</body>` tags?

**Comment by jantimon** [comment]
@Jorjon you could easily indent the result using the `html-webpack-plugin-after-html-processing` hook
