### ISSUE TITLE
what is the correct way to strip a certain script

### ISSUE THREAD

**Issue by maxisam** [ampedandwired/html-webpack-plugin#463]
Let's say I would like to generate a common CSS file. I use an entry script to import all less/css files I want and use extract-text-webpack-plugin to generate the css file. 

However, when I use html-webpack-plugin, it will insert both entry file and the css file into the index.html, which is not exactly I want because that entry script file is useless.

So my question is what is the best way to prevent the script file got insert into index.html ?

My current solution is creating a plug-in to strip that from htmlPluginData.body, but I feel like it is not an ideal solution.

Thanks !

**Comment by jantimon** [comment]
You can disable the inject feature.

**Comment by maxisam** [comment]
Well, but I have other entries need to be injected. How to inject part of entries ?

**Comment by jantimon** [comment]
From the readme:

If the `inject` feature doesn't fit your needs and you want full control over the asset placement use the [default template](https://github.com/jaketrent/html-webpack-template/blob/86f285d5c790a6c15263f5cc50fd666d51f974fd/index.html) of the [html-webpack-template project](https://github.com/jaketrent/html-webpack-template) as a starting point for writing your own.
