### ISSUE TITLE
Support charset for script injection

### ISSUE THREAD

**Issue by rmannibucau** [ampedandwired/html-webpack-plugin#465]
Hi

Would it be possible to add to the config options an entry "charset" - likely a string or function taking as parameter the chunk name - and map it in the script attributes (https://github.com/ampedandwired/html-webpack-plugin/blob/master/index.js#L470 I think)?

It would allow to inject the scripts specifying the charset (UTF-8 most of the time).

**Comment by jantimon** [comment]
Could you please add some browser specs to illustrate which cases would need that?

**Comment by rmannibucau** [comment]
is http://www.w3schools.com/tags/att_script_charset.asp enough?

**Comment by jantimon** [comment]
I would like to understand why javascript would not be loaded as UTF-8.
If it is just a rare case I would prefer to move this into a plugin.

**Comment by rmannibucau** [comment]
If page encoding is the default one and your OS - let's say windows - doesn't use UTF-8 as default then scripts will be loaded using the page encoding. Typically iso-8859-1 for windows. Workaround is to change the page encoding but think it doesn't hurt to enable this configuration.

**Comment by jantimon** [comment]
In this case I would prefer to use a `meta` tag.
Feel free to develop a small plugin which also adds the utf8 charset.

Take https://github.com/jantimon/html-webpack-harddisk-plugin/blob/master/index.js as a start point and use the `html-webpack-plugin-alter-asset-tags` event to change it :)

**Comment by rmannibucau** [comment]
Note that this doesn't solve the issue at all since meta provides a global value for index.html + scripts where the requested feature is to be able to set the charset per script (function (chunk){}).

**Comment by jantimon** [comment]
Yes and for that really edge case you can write a small plugin (like 20 lines of code) which would add the charcode attribute

**Comment by rmannibucau** [comment]
@jantimon not sure I follow what prevents to add the 2 lines making html-webpack-plugin supporting it?

**Comment by jantimon** [comment]
From the readme: 

> You can use the lodash syntax out of the box. If the inject feature doesn't fit your needs and you want full control over the asset placement use the default template of the html-webpack-template project as a starting point for writing your own.

I guess you agree that the html-webpack-plugin configuration is already overloaded and your change is rather an edge case and can be implemented with a custom template or with a subplugin.

**Comment by rmannibucau** [comment]
not sure I agree with that ;). Concretely html plugin should from my point of view be a passthrough for the template of script so attributes should be fully supported. If writing another plugin is the solution I'm not sure I see the point of that plugin anymore to be honest. Concretely a scriptAttribute function returning an object and merged with script attribute is not much and would also allow to refactor current code to be more generic. Not seeing it bad or overloading ;)

**Comment by jantimon** [comment]
This would work only if all script / link tags should get the same attribute.

**Comment by jantimon** [comment]
What is the problem with a custom template? The inject feature is just a feature which is turned on by default. Just do it on the template level: 

https://github.com/jaketrent/html-webpack-template/blob/86f285d5c790a6c15263f5cc50fd666d51f974fd/index.html

**Comment by rmannibucau** [comment]
Custom template is a bit verbose compared to setting an attribute. The usage of a function allows to not have the same attributes for all scripts/link so I think it would work

**Comment by jantimon** [comment]
This is what can already be done using a plugin.. Please check on that topic.

**Comment by jantimon** [comment]
```js
plugins: [
  new HtmlWebpackPlugin({ /* .... */ }),
  {
      apply: function (compiler) {
        compiler.plugin('compilation', function (compilation) {
          compilation.plugin('html-webpack-plugin-alter-asset-tags', function (object, callback) {
            // Modify the asset here
            callback(object);
          });
        });
      }
]
```

**Comment by rmannibucau** [comment]
what i proposed was:

    new HtmlWebpackPlugin({
        attributes: function (chunk) {return {charset: 'UTF-8'}}
    })

for instance

avoids to require to depend on the plugins which is a big win IMO. That said your solution works too but is a more a hack or workaround for me

**Comment by jantimon** [comment]
Sorry for disappointing you but I really don't want to extend the html-webpack-options if it is not a really common use case.

Your way would break backwards compatibility (because someone might use the attributes variable in the template).

There two valid solutions (I would go with a custom template) to your problem.

**Comment by rmannibucau** [comment]
Ok, fair enough
