### ISSUE TITLE
Conditional codes in html template

### ISSUE THREAD

**Issue by KhoaSydney** [ampedandwired/html-webpack-plugin#47]
Hi @ampedandwired,

Is it possible to have conditional codes, something like below:

```javascript
if (o.webpackconfig.Production)
{
 <script type="text/javascript" src="{%=o.webpackconfig.UrlInProduction %}"></script>
}
else{
 <script type="text/javascript" src="{%=o.webpackconfig.urlInDevelopment%}"></script>
}
```
thanks

**Comment by KhoaSydney** [comment]
I think I found the solution. It is just normal Javscript as long as you enclose them by `{%}`.

```javascript
{% if (o.webpackconfig.Production) { %}
 <script type="text/javascript" src="{%=o.webpackconfig.UrlInProduction %}"></script>
{% } %}
{% else { %}
<script type="text/javascript" src="{%=o.webpackconfig.urlInDevelopment%}"></script>
{% } %}

```

**Comment by eventhough** [comment]
@KhoaSydney How did you set the `o.webpackconfig.Production` flag? Could you share your HtmlWebpackPlugin configuration?

**Comment by shairez** [comment]
@eventhough They've changed it in 2.X
Now it's the ejs style -   `<% if (htmlWebpackPlugin.options.environment.production){ %>`

Hope it helps, I've spent 2 hours finding this info out for myself after seeing no answer in this issue

**Comment by Restuta** [comment]
@shairez can you share your config? I can't seem to get `options.environment` working for me

**Comment by Restuta** [comment]
@shairez nvm, got it working =)

**Comment by export-mike** [comment]
@Restuta what did you do to get this working?

**Comment by jantimon** [comment]
In most cases `inject:true` will solve this for you

**Comment by export-mike** [comment]
@jantimon I have inject: 'body'

**Comment by export-mike** [comment]
so does that only allow templating in body?

**Comment by jantimon** [comment]
Inject:true and inject:body is the same (and also the default) it will inject all link and script tags for you so that you can use the same template for dev and production

**Comment by Restuta** [comment]
@export-mike just this:
https://github.com/Restuta/rcn.io/blob/master/webpack.config.prod.js
