### ISSUE TITLE
html-webpack-plugin crashes when using with stylelint-webpack-plugin

### ISSUE THREAD

**Issue by dangler** [ampedandwired/html-webpack-plugin#472]
I'm having the same issue listed previously, but the previous issued didn't get resolved. 

Previous issue: https://github.com/ampedandwired/html-webpack-plugin/issues/367

My plugin configurations:

```
           htmlWebpack: new HtmlWebpackPlugin({
                title: 'WebPack Test',
                template: '!!html!./client.app/assets/index.html'
            })

            styleLint: new StyleLintPlugin({
                configFile: './config/stylelint.config.json',
                context: 'inherits from webpack',
                files: '../**/*.s?(a|c)ss',
                failOnError: false,
                quiet: true
            }),
```

Some errors I'm seeing:

> WARNING in undefined
> 
> WARNING in undefined
> 
> WARNING in undefined
> 
> WARNING in undefined
> 
> WARNING in undefined
> 
> WARNING in undefined
> 
> WARNING in undefined
> 
> WARNING in undefined
> 
> WARNING in undefined
> 
> WARNING in undefined
> 
> ERROR in /Users/jeremiahd/code/service-health/client/client.app/app/app.scss
> 
> ERROR in /Users/jeremiahd/code/service-health/client/client.serviceHealth/components/allSites/allSites.scss
> 
> ERROR in /Users/jeremiahd/code/service-health/client/client.serviceHealth/components/allSites/allUsage/allUsage.scss
> 
> ERROR in /Users/jeremiahd/code/service-health/client/client.serviceHealth/components/allSites/availability/availability.scss
> 
> ERROR in /Users/jeremiahd/code/service-health/client/client.serviceHealth/components/allSites/usageChart/usageChart.scss
> 
> ERROR in /Users/jeremiahd/code/service-health/client/client.serviceHealth/components/header/header.scss
> 
> ERROR in /Users/jeremiahd/code/service-health/client/client.serviceHealth/components/serviceHealth/serviceHealth.scss
> 
> ERROR in /Users/jeremiahd/code/service-health/client/client.shared/components/menu/menu.scss
> 
> ERROR in /Users/jeremiahd/code/service-health/client/client.shared/components/notification/notification.scss
> 
> ERROR in /Users/jeremiahd/code/service-health/client/client.shared/components/timeRangeSelector/timeRangeSelector.scss
> 
> ERROR in   Error: Child compilation failed:
>   undefined
>   undefined
>   undefined
>   undefined
>   undefined
>   undefined
>   undefined
>   undefined
>   undefined
>   undefined
>   
>   - compiler.js:76 
>     [client]/[html-webpack-plugin]/lib/compiler.js:76:16
>   
>   - Compiler.js:214 Compiler.<anonymous>
>     [client]/[webpack]/lib/Compiler.js:214:10
>   
>   - Compiler.js:403 
>     [client]/[webpack]/lib/Compiler.js:403:12
>   
>   - Tapable.js:67 Compiler.next
>     [client]/[webpack]/[tapable]/lib/Tapable.js:67:11
>   
>   - CachePlugin.js:40 Compiler.<anonymous>
>     [client]/[webpack]/lib/CachePlugin.js:40:4
>   
>   - Tapable.js:71 Compiler.applyPluginsAsync
>     [client]/[webpack]/[tapable]/lib/Tapable.js:71:13
>   
>   - Compiler.js:400 Compiler.<anonymous>
>     [client]/[webpack]/lib/Compiler.js:400:9
>   
>   - Compilation.js:577 Compilation.<anonymous>
>     [client]/[webpack]/lib/Compilation.js:577:13
>   
>   - Tapable.js:60 Compilation.applyPluginsAsync
>     [client]/[webpack]/[tapable]/lib/Tapable.js:60:69
>   
>   - Compilation.js:572 Compilation.<anonymous>
>     [client]/[webpack]/lib/Compilation.js:572:10
>   
>   - Tapable.js:60 Compilation.applyPluginsAsync
>     [client]/[webpack]/[tapable]/lib/Tapable.js:60:69
>   
>   - Compilation.js:567 Compilation.<anonymous>
>     [client]/[webpack]/lib/Compilation.js:567:9
>   
>   - Tapable.js:60 Compilation.applyPluginsAsync
>     [client]/[webpack]/[tapable]/lib/Tapable.js:60:69
>   
>   - Compilation.js:563 Compilation.<anonymous>
>     [client]/[webpack]/lib/Compilation.js:563:8
>   
>   - Tapable.js:60 Compilation.applyPluginsAsync
>     [client]/[webpack]/[tapable]/lib/Tapable.js:60:69
>   
>   - Compilation.js:525 Compilation.seal
>     [client]/[webpack]/lib/Compilation.js:525:7
>   
>   - Compiler.js:397 Compiler.<anonymous>
>     [client]/[webpack]/lib/Compiler.js:397:15
>   
>   - Tapable.js:103 
>     [client]/[webpack]/[tapable]/lib/Tapable.js:103:11
>   
>   - Compilation.js:445 Compilation.<anonymous>
>     [client]/[webpack]/lib/Compilation.js:445:10
>   
>   - Compilation.js:417 
>     [client]/[webpack]/lib/Compilation.js:417:12
>   
>   - Compilation.js:332 
>     [client]/[webpack]/lib/Compilation.js:332:10
>   
>   - async.js:52 
>     [client]/[async]/lib/async.js:52:16
>   
>   - async.js:236 Object.async.forEachOf.async.eachOf
>     [client]/[async]/lib/async.js:236:30
>   
>   - async.js:209 Object.async.forEach.async.each
>     [client]/[async]/lib/async.js:209:22
>   
>   - Compilation.js:185 Compilation.addModuleDependencies
>     [client]/[webpack]/lib/Compilation.js:185:8
>   
>   - Compilation.js:170 Compilation.processModuleDependencies
>     [client]/[webpack]/lib/Compilation.js:170:7
>   
>   - Compilation.js:412 Compilation.moduleReady
>     [client]/[webpack]/lib/Compilation.js:412:9
>   
>   - Compilation.js:408 Compilation.<anonymous>
>     [client]/[webpack]/lib/Compilation.js:408:16
>   
>   - Compilation.js:123 
>     [client]/[webpack]/lib/Compilation.js:123:4
>   
>   - Array.forEach
>   
> 
> Child html-webpack-plugin for "index.html":
>         + 1 hidden modules
>     
>     WARNING in undefined
>     
>     WARNING in undefined
>     
>     WARNING in undefined
>     
>     WARNING in undefined
>     
>     WARNING in undefined
>     
>     WARNING in undefined
>     
>     WARNING in undefined
>     
>     WARNING in undefined
>     
>     WARNING in undefined
>     
>     WARNING in undefined
>     
>     ERROR in /Users/jeremiahd/code/service-health/client/client.app/app/app.scss
>     
>     ERROR in /Users/jeremiahd/code/service-health/client/client.serviceHealth/components/allSites/allSites.scss
>     
>     ERROR in /Users/jeremiahd/code/service-health/client/client.serviceHealth/components/allSites/allUsage/allUsage.scss
>     
>     ERROR in /Users/jeremiahd/code/service-health/client/client.serviceHealth/components/allSites/availability/availability.scss
>     
>     ERROR in /Users/jeremiahd/code/service-health/client/client.serviceHealth/components/allSites/usageChart/usageChart.scss
>     
>     ERROR in /Users/jeremiahd/code/service-health/client/client.serviceHealth/components/header/header.scss
>     
>     ERROR in /Users/jeremiahd/code/service-health/client/client.serviceHealth/components/serviceHealth/serviceHealth.scss
>     
>     ERROR in /Users/jeremiahd/code/service-health/client/client.shared/components/menu/menu.scss
>     
>     ERROR in /Users/jeremiahd/code/service-health/client/client.shared/components/notification/notification.scss
>     
>     ERROR in /Users/jeremiahd/code/service-health/client/client.shared/components/timeRangeSelector/timeRangeSelector.scss
> 
>

**Comment by dangler** [comment]
Also note that the above errors end up in my index.html file

**Comment by jantimon** [comment]
Sorry can't do much here did you ask the Stylelint Plugin developer for help?

**Comment by jantimon** [comment]
The error is thrown here:

https://github.com/ampedandwired/html-webpack-plugin/blob/1a2e2b3e94bc62569ee7b748da88b1b85f2f79c2/lib/compiler.js#L71

Maybe you could add some `console.log` or `console.trace` debug statements and find out what's the reason for the crash.

**Comment by dangler** [comment]
I'll work on that and return with more info. Will probable be later today thought.  Thank you!

**Comment by dangler** [comment]
Switching the config to emit a warning fixed some of the issues. I think I've narrowed it down to the fact that stylelint is running it over files that are not SASS. I'll close this issue. Thank you!

**Comment by jantimon** [comment]
Thanks for your feedback :)

**Comment by cescoferraro** [comment]
@jantimon this still happens, removing the errors if they are from scss/sass files works. I am not a javascripter, first time using webpack at all on version 
```
    "webpack": "2.2.0-rc.1",
    "html-webpack-plugin": "2.24.1",
    "stylelint-webpack-plugin": "0.4.0",
```
 What should be the best approach here?
```
_.map( childCompilation.errors , ( n ) => {
	if ( n.endsWith( ".scss" ) || n.endsWith( ".sass" ) ) {
		childCompilation.errors = childCompilation.errors.splice( childCompilation.errors.indexOf( n ) , -1 )
	}
})
```
@dangler what do you mean by emit warnings? This plugin, style-lint-plugin or dev-server-warnings?
