### ISSUE TITLE
Generate html file per entry in webpack.config

### ISSUE THREAD

**Issue by ido-ran** [ampedandwired/html-webpack-plugin#477]
I have a React application with two entries define in webpack.config file.
Currently I have two static html files each of which use the scrtip generated by each of the entries.
As far as I can see html-webpack-plugin generate one HTML with both entries which is not what I need.

I'll be happy to help implement this change to generate one HTML file per entry - I want to know why you choose to generate only one HTML file when multiple entries are defined.

**Comment by jantimon** [comment]
Please use two HtmlWebpackPlugin isntances and the chunks option

**Comment by priyanshuchauhan** [comment]
Use multiple instances of the HtmlWebpackPlugin. You will need to configure each instance. 
```
module.exports = {
  entry: {
    'page1': './apps/page1/scripts/main.js',
    'page2': './apps/page2/src/main.js'
  },
  output: {
    path: __dirname,
    filename: "apps/[name]/build/bundle.js"
  },
  plugins: [
    new HtmlWebpackPlugin({
      inject: true,
      chunks: ['page1'],
      filename: 'apps/page1/build/index.html'
    }),
    new HtmlWebpackPlugin({
      inject: true,
      chunks: ['page2'],
      filename: 'apps/page2/build/index.html'
    })
  ]
};
```
Source: https://github.com/jantimon/html-webpack-plugin/issues/218

**Comment by maoshuai** [comment]
# Four steps to add multiple entries to create-react-app 
(say we add an admin.html):

# 1. Eject the project
```
npm run eject  
```
# 2. Add multiple entry to webpack.config.dev.js
```
entry: {
    index: [
      require.resolve('react-dev-utils/webpackHotDevClient'),
      require.resolve('./polyfills'),
      require.resolve('react-error-overlay'),
      paths.appIndexJs,
    ],
    admin:[
      require.resolve('react-dev-utils/webpackHotDevClient'),
      require.resolve('./polyfills'),
      require.resolve('react-error-overlay'),
      paths.appSrc + "/admin.js",
      ]
  },
  output: {
    path: paths.appBuild,
    pathinfo: true,
    filename: 'static/js/[name].bundle.js',
    chunkFilename: 'static/js/[name].chunk.js',
    publicPath: publicPath,
    devtoolModuleFilenameTemplate: info =>
      path.resolve(info.absoluteResourcePath),
  },
```
# 3. Modify HtmlWebpackPlugin
add a new plugin node:
```
    new HtmlWebpackPlugin({
      inject: true,
      chunks: ["index"],
      template: paths.appHtml,
    }),
    new HtmlWebpackPlugin({
      inject: true,
      chunks: ["admin"],
      template: paths.appHtml,
      filename: 'build/admin.html',
    }),
```

# 4. webpack Dev Server
rewrite urls
/config/webpackDevServer.config.js:
```
    historyApiFallback: {
      disableDotRule: true,
      // 指明哪些路径映射到哪个html
      rewrites: [
        { from: /^\/admin.html/, to: '/build/admin.html' },
      ]
    }
```

Details in Chinese: http://imshuai.com/create-react-multiple-enties/
