### ISSUE TITLE
Webpacks roots/aliasses for resolving template and partials/included subtemplates

### ISSUE THREAD

**Issue by jeroentradecast** [ampedandwired/html-webpack-plugin#480]
Hi Jantimon, 

I have a usecase where deps/modules are resolved (with Webpacks multiple roots and aliasses) in a specific order (e.g. first resolving 'custom' folder, then 'src' folder, then node_modules) for multiple targets (web and others). 

For the template option (and included partial with whatever loader), I can't seem to let the deps/templates resolve the way webpack does. I'd like to do something like the following for the htmlWebpackPlugin template option

`template: '__someAlias__/templates/index.html'`

and when including subtemplates/partials, pretty much the same. Ultimately, it should look for templates in the 'custom' folder, 'src' folder, than 'node_modules' and fail when none are found.

Any idea how I could set this up?

**Comment by jantimon** [comment]
Hey :)

I guess right now that's not supported (mainly for backwards compatibility)
However it would be easy to add that feature similar to the sass-loader.

All we would have to do is to ignore the preprocessing if the request starts with a `~` so you could specify it as `template: '~__someAlias__/templates/index.html'`

Would you be up to create a pull request?

**Comment by jeroentradecast** [comment]
Yeah, I'll look into it this weekend.

I've got a semi-solution for the moment based on the [advanced-javascript example](https://github.com/ampedandwired/html-webpack-plugin/tree/master/examples/javascript-advanced), it's not the prettiest but it works for now. 

The template options is pointed to a small piece of javascript like this (psuedo): 

```
module.exports = `
  <!DOCTYPE html>
  <html>
     ${ require('__someAlias__/someTarget/partials/head.html }
     ${ require('__someAlias__/someTarget/partials/body.html }
  </html>
`;
```

I'll close this issue for now.
