### ISSUE TITLE
How can i inject the chunks into body, at  the same time inject a script into head

### ISSUE THREAD

**Issue by HULIANGA** [ampedandwired/html-webpack-plugin#484]
I set the option 'inject' to 'body'，but i need to add a script into head。Can the event 'html-webpack-plugin-before-html-processing' be used to resolve my problem，if it does，how？thanks

**Comment by raphaklaus** [comment]
:+1:

**Comment by jantimon** [comment]
As written in the readme you can turn off the inject feature to gain full control over the asset placement.

**Comment by HULIANGA** [comment]
got it,thanks a lot

**Comment by th3fallen** [comment]
@HULIANGA could you share how you did it? im attempting the same thing but running into issues, epecially since my outputs have hashes in them
