### ISSUE TITLE
Encoding of index.html file in UTF-8

### ISSUE THREAD

**Issue by krunal2450** [ampedandwired/html-webpack-plugin#485]
I am packaging an application using html-webpack-plugin. Everything is going fine but index.html is getting generated in ANSI format. This is causing the extra junk characters (like Â) in my html page UI.
I resolved this issue using the help from below post:
**_http://stackoverflow.com/a/11325511/1606668_**

But I don't want to follow these steps manually. Is there anything in the parameter below template in below code?
 **new HtmlWebpackPlugin({
        template: 'src/index.html'
});**

I have tried using **encoding: 'utf-8'**, but it is not working for me. Please let me know if anybody has any idea for this.

**Comment by jantimon** [comment]
Sorry only utf8 is supported by now

**Comment by krunal2450** [comment]
@jantimon Yes, you are right. But my question is:
_**Index.html file generated by html-webpack-plugin is in ANSI format by default. I want it to be generated in UTF-8 format with the configuration.**_

**Comment by jantimon** [comment]
Well the file generation is done by webpack - not by this plugin.
It happens here:

https://github.com/ampedandwired/html-webpack-plugin/blob/master/index.js#L179-L185

**Comment by krunal2450** [comment]
Let me check that. Thanks for your important input @jantimon :)
