### ISSUE TITLE
Some wrong notes with html-webpack-plugin

### ISSUE THREAD

**Issue by humorHan** [ampedandwired/html-webpack-plugin#486]
Html-webpack-plugin

The plugin has a index.js file, there are about 65 lines of comments errors, give me trouble, I do not know whether the next version will be changed.

`compiler.plugin('emit', function (compilation, callback) { `
    `var applyPluginsAsyncWaterfall = self.applyPluginsAsyncWaterfall(compilation);`
   ` // Get all chunks`
    `var chunks = self.filterChunks(compilation.getStats().toJson(), self.options.chunks, self.options.excludeChunks);`
 
And this chunks should be the need to get through the parameters attached to the JS file on the HTML, not all chunks files

**Comment by jantimon** [comment]
Sorry I don't understand what you mean

**Comment by humorHan** [comment]
I'm sorry I can't describe the description,
I was trying to say that some of the comments in this plugin may be wrong, about 65 lines in index.js.

**Comment by humorHan** [comment]
Of course the above problem is a small problem, I hope that the relevant personnel to answer another question I put forward, I have raised the issue #483

**Comment by jantimon** [comment]
What should the comment say instead?

**Comment by humorHan** [comment]
In my opinion, this should be all chunks to remove the self.options.excludeChunks to match the rest of the chunks self.options.chunks bar. If that's the case, then it's not too good to comment for chunks all, right?

**Comment by humorHan** [comment]
Of course the above problem is a small problem, I hope that the relevant personnel to answer another question I put forward, I have raised the issue #483.
Thanks for offering help.

**Comment by jantimon** [comment]
You are right - I guess the code was changed without updating the comment.
I will do that soon 👍

**Comment by humorHan** [comment]
Yeah, thank you very much, so that the plugin better serve more people！
