### ISSUE TITLE
Inject options for supporting inline source

### ISSUE THREAD

**Issue by DustinJackson** [ampedandwired/html-webpack-plugin#490]
Perhaps it would be nice to extend the inject options to allow inline source?  Similar to [this](https://www.npmjs.com/package/gulp-inline-source) gulp plugin result.  Specifying filters for which sources get injected inline would be ideal.

I am working on a fork and would appreciate any comments/advice for how I could get this to work!

**Comment by DustinJackson** [comment]
So this is definitely possible.  The [createHtmlTag function](https://github.com/ampedandwired/html-webpack-plugin/blob/master/index.js#L586) is already checking for innerHTML in the tag definitions.  As a test I updated the [generateAssetTags function](https://github.com/ampedandwired/html-webpack-plugin/blob/master/index.js#L464) which is responsible for creating the tag definitions:

```javascript

// add compilation as param
HtmlWebpackPlugin.prototype.generateAssetTags = function (compilation, assets) {
  // Turn script files into script tags
  var scripts = assets.js.map(function (scriptPath) {
    return {
      tagName: 'script',
      closeTag: true,
      attributes: {
        type: 'text/javascript',
        // src: scriptPath -- ignore for test
      },
      innerHTML: compilation.assets[scriptPath.split("/").pop()].source()
    };
  });
 
// ...
};
```

I pass in **compilation** as a parameter and then used it to get set the innerHTML of the tag definitions to the file's source.  This ends up embedding the source inline in the resulting html file.  

Thoughts?  It seems like this could be a nice feature.  The tag definitions just need to be updated do either set innerHTML or src depending on the build configuration.  I can do my best to put together a pull request, however I am new to webpack and this repo.

**Comment by jantimon** [comment]
You could implement this as an additional plugin if you like :)
Similar to the https://github.com/jantimon/html-webpack-harddisk-plugin

**Comment by DustinJackson** [comment]
@jantimon I took a stab at implementing this as a [plugin](https://github.com/DustinJackson/html-webpack-inline-source-plugin).  It hooks into the alter assets event to modify the tag definitions.

One question...  I got a deprecation warning because I didn't return a result from the plugin, however when I [return a result](https://github.com/DustinJackson/html-webpack-inline-source-plugin/blob/master/index.js#L22) I get an error.

Any idea what is going on here?

callback(null) gives warning:
![screenshot_39](https://cloud.githubusercontent.com/assets/3475338/20249569/040b1a2a-a9ca-11e6-8f8e-fc128591904b.png)

callback(result) gives empty error:
![screenshot_40](https://cloud.githubusercontent.com/assets/3475338/20249576/1b65c968-a9ca-11e6-877a-76f1678efaf5.png)

**Comment by jantimon** [comment]
wow looks nice :)
try to return the first argument you get - I guess it's the htmlPluginData in your case

**Comment by DustinJackson** [comment]
thanks for you help

I've tried returning htmlPluginData data which also throws an error.  It is hard to debug... It seems if I return anything other than null it crashes.  I added a [gist ](https://gist.github.com/DustinJackson/b1013f8e6f84e48d73cb824e3b4395e6) to demonstrate.

As far as I can tell when something other than callback(null) is returned the [result ](https://github.com/ampedandwired/html-webpack-plugin/blob/master/index.js#L153) ends up being undefined... 

Any ideas?

**Comment by jantimon** [comment]
Well it's the default node callback logic, first argument is the error the second one is the value so your code would be:

`callback(null, htmlPluginData)`

**Comment by DustinJackson** [comment]
Wow silly mistake... thank you.  I updated the plugin and all is well.

**Comment by callumacrae** [comment]
The plugin is working great for me :)

**Comment by jantimon** [comment]
cool I'll add it to the readme

**Comment by jantimon** [comment]
What is the name of the plugin?
