### ISSUE TITLE
which event can i use, i want to implement  injecting by my custom tags

### ISSUE THREAD

**Issue by 8427003** [ampedandwired/html-webpack-plugin#495]
which event can i use, i want to implement  injecting by my custom tags ?

background:
i use layout in template. there is no boy or head tag, and the template be used by backend.  i know, i can implement it  instead of the custom template in diff grammar prefix. it's not the best, like this: 

![1](https://cloud.githubusercontent.com/assets/5475231/20291047/e3a98a22-ab1e-11e6-8330-a03d82194471.png)

**Comment by jantimon** [comment]
Injecting requires a body and a head - so your solution looks quite okay
