### ISSUE TITLE
Is ejs template 'include' command not supported?

### ISSUE THREAD

**Issue by zacard-orc** [ampedandwired/html-webpack-plugin#499]
webpack.config.js:
   new HtmlWebpackPlugin({  // Also generate a test.html
          favicon:'src/assets/icons/page_bird1.ico',
          filename: 'linly.html',
          title: 'Trioly template',
          xfile:{
            js: [publicPath+'assets/js/jquery.min.js']
          },
          template: 'src/pages/page1/page1.ejs',
          inject: 'body'
      })

page1.ejs:
......
<%- include hello.ejs %>

hello.ejs
<div>hello world</div>

then ,it report "unexpected string "

if i replace some configuration With ejs-render-loader or ejs-compile-loader
template: '!!ejs-render-loader!src/pages/page1/page1.ejs',

then ,it report "htmlWebpackPlugin is undefined".....

how to fill these two requirements..?? ^_^

**Comment by jantimon** [comment]
The built in fallback loader does not support include but you can use another loader :)
