### ISSUE TITLE
Template change doesn't trigger recompilation in watch mode

### ISSUE THREAD

**Issue by Kagami** [ampedandwired/html-webpack-plugin#5]
Hi. Thanks for the great plugin.
There is one minor issue though I'm not sure is it the right place to address it.

When I run webpack-dev-server and change some javascript file in dependency graph, webpack notices it and recompiles the bundle. But it doesn't work for html-webpack-plugin templates. Could this be fixed? Thanks.

**Comment by kurtharriger** [comment]
Adding the following tells webpack to recompile when file has changed. Hot reloading doesn't seem to work, but at least I can reload the page to see changes rather than killing and restarting webpack.


compiler.fileDependencies.push(templateFile);

**Comment by tomchentw** [comment]
Thanks @kurtharriger for the improvement. Sadly hot reload won't work in this case.

**Comment by lukescott** [comment]
I'm not able to get this to work with either `webpack -w` or `webpack-dev-server`. If I edit the template the html file is not rebuilt or reloaded.

Config:
```
var HtmlWebpackPlugin = require("html-webpack-plugin");

module.exports = {
	entry: "./app/index.js",
	devtool: "source-map",
	output: {
		path: "./build",
		filename: "bundle.js",
		sourceMapFilename: "[file].map"
	},
	plugins: [
		new HtmlWebpackPlugin({
			filename: "index.html",
			template: "./app/index.html"
		})
	],
	module: {
		loaders: [
			{
				test: /\.js$/,
				exclude: /node_modules/,
				loader: "babel-loader"
			}
		]
	}
};
```
