### ISSUE TITLE
getting ERROR in undefined

### ISSUE THREAD

**Issue by deezahyn** [ampedandwired/html-webpack-plugin#50]
I've created a sample repo to show the error:
https://github.com/deezahyn/webpack-htmlplugin-test/
`npm install && webpack`

**Comment by jantimon** [comment]
Actually 1.4. should be backwards compatible. 
The error was a missing new Error() and was fixed by #45.
We should release a 1.4.1 version and roll this fix out.

**Comment by jantimon** [comment]
The fix for now is to use the `inject` option or to use the `files` object instead of the `assets` object in your template: https://github.com/ampedandwired/html-webpack-plugin/blob/master/default_index.html#L15

**Comment by bsr203** [comment]
uh! I been struggling with this, and finally glad to see this is not caused by my code :-)
http://stackoverflow.com/questions/30423710/webpack-verbose-error-message

**Comment by nmccready** [comment]
It is related to this! https://github.com/webpack/webpack/pull/1146

**Comment by jantimon** [comment]
Will be fixed as soon as @ampedandwired released 1.5.

**Comment by deezahyn** [comment]
thanks for the update @jantimon

**Comment by bebraw** [comment]
@deezahyn FYI, 1.5 is out now.
