### ISSUE TITLE
Including just CSS files

### ISSUE THREAD

**Issue by matt-paul** [ampedandwired/html-webpack-plugin#503]
I am hoping to simply include the link to my styles.css file (created via ExtractTextPlugin)for one of my outputted html files, without including any of the bundled javascript files.  I notice an option to exclude chunks, but not whole files...Any thoughts on this would be greatly appreciated.

**Comment by mattdistefano** [comment]
Not sure if you figured this out already but a custom template would probably do it.

**Comment by jantimon** [comment]
Correct :)
