### ISSUE TITLE
can template support multiple  loader ? 

### ISSUE THREAD

**Issue by 8427003** [ampedandwired/html-webpack-plugin#504]
can template support multiple loader ?  like this:
!!html!ejs!src/views/page/tempate.html

**Comment by jantimon** [comment]
yes

**Comment by ryym** [comment]
It seems not to work correctly.
With a following webpack configuration,

```js
const HtmlWebpackPlugin = require('html-webpack-plugin')

module.exports = {
  output: {
    path: 'dist',
    filename: '[name].js'
  },

  plugins: [
    new HtmlWebpackPlugin({
      template: 'ejs!html!index.html',
    })
  ]
}
```

HtmlWebpackPlugin outputs this JS code to dist/index.html.

```js
module.exports = "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n</head>\n<body>\n  <div>hello</div>\n</body>\n</html>\n";
```

The original index.html is here.

```html
<!DOCTYPE html>
<html lang="en">
<head>
</head>
<body>
  <div>hello</div>
</body>
</html>
```

----

- webpack: 1.13.3
- html-webpack-plugin: 2.24.1
- ejs-loader: 0.3.0
- html-loader: 0.4.4

**Comment by jantimon** [comment]
It is important to understand what a loader does.

In your example the ejs-loader does the following transformation:

`<h1><%= title %></h1>` --> ejs-loader --> `module.exports=function(data) { return "<h1>" + title + "</h1>"; };`

If you now use the output of the ejs-loader for the html-loader the html-loader will try to execute its code on the javascript code and will fail.

**Comment by ryym** [comment]
I understand. Both of the html-loader and ejs-loader take HTML but return JavaScript code
so we can't pipe them, correct?
Thank you for the explanation 🙇
