### ISSUE TITLE
How to pass variables to required html?

### ISSUE THREAD

**Issue by wangcansunking** [ampedandwired/html-webpack-plugin#507]
Hello everyone, now I use webpack to build a static website but run into some problems.
## First of all how to pass parameter to required 

demo.html 
```
  <%= require('html!./partial.html') %>
```

partial.html
```
<%= htmlWebpackPlugin.options.someKey %>
```

webpack.config.js 
```
new HtmlWebpackPlugin({
            filename: 'demo.html',
            template: './src/demo.html'
            someKey:123
        }),
```

and if it is in the `""` how to deal with it?

example: 
partial.html
```
<img src="<%= htmlWebpackPlugin.options.someKey %>"/>
```

**Comment by jantimon** [comment]
Please ask this question on stackoverflow and add the link here :)

**Comment by wangcansunking** [comment]
if it is not the http-webpack-plugin that makes the decision?
