### ISSUE TITLE
Include bundle from multi (config) build.

### ISSUE THREAD

**Issue by whitecolor** [ampedandwired/html-webpack-plugin#508]
To optimize build perfomance i'm building app using two separate configs:
First bundle is more frequently changed, and thus second big-bundle content do not mess with the process of its rebuilding (because it they are in one config though they are different bundles, process of rebuilding only of the first still slows down).

```js
configs = [
{ 
   entry: {app: './app'},
   output: ...
   plugins: [
     new HtmlWebpackPlugin({..})
  ]
},
  // this is second rarely changed bundle
{
  entry: {big-bundle: './some/big'}.
  output: ...
}
]
```
As there only one index.html, it is plugged in one of the configs, the  question is how to include reference to `big-bundle` in resulting HTML, using HtmlWebpackPlugin if its name may be variable depending on hash?

**Comment by jantimon** [comment]
Please ask those questions on stackoverflow and add a link here :)

**Comment by whitecolor** [comment]
Here it is: http://stackoverflow.com/questions/40936563/include-bundle-from-multi-config-build
