### ISSUE TITLE
Ability to disable css injection

### ISSUE THREAD

**Issue by Yona-Appletree** [ampedandwired/html-webpack-plugin#515]
My app has multiple themes, and this is implemented with multiple top-level css files. As it currently stands, html-webpack-plugin includes them all, and there doesn't appear to be a way to disable this. There should be an option to simply disable auto detection of css assets.

**Comment by jantimon** [comment]
https://github.com/jamesjieye/html-webpack-exclude-assets-plugin

**Comment by Yona-Appletree** [comment]
Fair enough, but that plugin doesn't support css assets, because it only filters on the src `property`, not `href`, but I'll make a bug there.

**Comment by jantimon** [comment]
Cool ty @Yona-Appletree :)
