### ISSUE TITLE
Not work when using multiple loaders

### ISSUE THREAD

**Issue by kenchan0130** [ampedandwired/html-webpack-plugin#517]
Hi,

As I looked at https://github.com/ampedandwired/html-webpack-plugin/blob/master/docs/template-option.md, I tried to set it as some other loaders can be set like

```js
module.exports = [
  plugins: [
    new HtmlWebpackPlugin({ template: 'src/index.ejs', inject: false }),
  ],
  module: {
    loaders: [
      {
        test: /\.ejs$/,
        loader: 'html?minimize!underscore-template-loader'
      }
    ]
]
```

However, the generated file has become such a file like:

```js
module.exports = module.exports = function(obj) {
obj || (obj = {});
var __t, __p = '';
with (obj) {
__p += '<!DOCTYPE html>\n<html lang="jp">\n<body>\n</body>\n</html>\n';
}
return __p
};
```

I expect that the text extracted files will be generated.

**Comment by jantimon** [comment]
Sorry that's just how webpack loaders work.

The underscore template loader returns javascript and the html-loader expects html.

**Comment by GeekaholicLin** [comment]
I have found out the solution to this problem using another loader named [extract-loader](https://github.com/peerigon/extract-loader).

> The extract-loader evaluates the given source code on the fly and returns the result as string.

Therefore,there are mainly two ways to `template` option .And maybe the difference between the two is the loader order.(But I don't know why the second can works...)

I can use both `${require()}` and EJS template syntax in the `.html` (or `.ejs`) files with the config.However,I just have the simple cases tested.Maybe some advantaged usages cannot work well.

``` javascript
template: "!!ejs-compiled-loader!!extract-loader!!html-loader?attrs[]=img:src&attrs[]=img:data-src&interpolate=require!"+path.resolve(src,"templates",page),
 // template: "!!extract-loader!!html-loader?attrs[]=img:src&attrs[]=img:data-src&interpolate=require!!ejs-compiled-loader!"+path.resolve(src,"templates",page),
```
