### ISSUE TITLE
files.main is not working like assets.main

### ISSUE THREAD

**Issue by nmccready** [ampedandwired/html-webpack-plugin#52]
Deprecated still works with the famous `Error undefined` ..
`<script type="application/javascript" src="{%=o.htmlWebpackPlugin.assets.main%}"></script>`

However the real problem is :
`<script type="application/javascript" src="{%=o.htmlWebpackPlugin.files.main%}"></script>`
Now results in 
`<script type="application/javascript" src=""></script>` on the build. What am I missing and if I am is there better docs for the transition? The only thing that works for me is 
`<script type="application/javascript" src="{%=o.htmlWebpackPlugin.files.js%}"></script>`

**Comment by jantimon** [comment]
The easiest way is to use the `inject:true` option - it will add all scripts for you without any template code.
See https://github.com/ampedandwired/html-webpack-plugin/blob/master/default_inject_index.html for example.
