### ISSUE TITLE
No need to specify type="text/javascript" inside script tag

### ISSUE THREAD

**Issue by tkrotoff** [ampedandwired/html-webpack-plugin#521]
I've noticed that HTML Webpack Plugin uses [`<script type="text/javascript">` everywhere](https://github.com/ampedandwired/html-webpack-plugin/search?utf8=%E2%9C%93&q=type%3D%22text%2Fjavascript%22). 

See https://www.w3.org/TR/html5/scripting-1.html#attr-script-type *“The default, which is used if the attribute is absent, is "text/javascript””*

Thus:
`<script type="text/javascript" src="..."></script>` simply becomes `<script src="..."></script>`.

FYI In HTML 4, `type` is needed

**Comment by tkrotoff** [comment]
See PR #522

**Comment by Daniel-Khodabakhsh** [comment]
This should be re-opened. Issue still occurs in 3.0.6.
