### ISSUE TITLE
what am i doing wrong?: Cannot resolve module 'index.js'

### ISSUE THREAD

**Issue by tony-kerz** [ampedandwired/html-webpack-plugin#53]
hi, 

i'm kind of a webpack noob, so prolly doing something stupid, but when i run `webpack` with the following configuration:

```
var HtmlWebpackPlugin = require('html-webpack-plugin')

module.exports = {
  entry: 'index.js',
  output: {
    path: 'dist',
    filename: 'index_bundle.js'
  },
  module: {
    loaders: [
      { test: /\.scss$/, loader: 'style!css!sass' },
      { test: /\.js$/, loader: 'babel', query: {stage: 1} }
    ]
  },
  devtool: 'cheap-module-eval-source-map',
  debug: true,
  plugins: [new HtmlWebpackPlugin()]
}
```
i get:

```
~/g/webpack-scratch (tk/html-plugin) $ webpack
Hash: 96ac1f7bada92e7c9381
Version: webpack 1.9.10
Time: 24ms
     Asset       Size  Chunks             Chunk Names
index.html  142 bytes          [emitted]  

ERROR in Entry module not found: Error: Cannot resolve module 'index.js' in /Users/tony/git/webpack-scratch
```

here is [a link to the entire project](https://github.com/tony-kerz/webpack-scratch/tree/tk/html-plugin) for reference...

any guidance appreciated!

best,
tony.

**Comment by jantimon** [comment]
Should prolly be  `entry: 'app/app.js'`?

**Comment by tony-kerz** [comment]
true, i was having issues so, in my confusion, i thought i was supposed to reference a specific `index.js` provided by the plugin.

for starters, i wanted to provide my own `index.html` file, and i was able to accomplish that with this config:

```
var HtmlWebpackPlugin = require('html-webpack-plugin')

module.exports = {
  entry: './app/app.js',
  output: {
    path: 'dist',
    filename: 'index_bundle.js'
  },
  resolve: {
    extensions: ['', '.js']
  },
  module: {
    loaders: [
      { test: /\.scss$/, loader: 'style!css!sass' },
      { test: /\.js$/, loader: 'babel', query: {stage: 1} }
    ]
  },
  devtool: 'cheap-module-eval-source-map',
  debug: true,
  plugins: [
    new HtmlWebpackPlugin({template: 'index.html', inject: 'body'})
  ]
}
```

i did encounter one nuance, when using this for a template: 
```
<html>
  <head>
    <meta charset="utf-8">
  </head>
  <body>
    <div id='myId'/>
  </body>
</html>
```

when i generate using `webpack`  my html file looks like this (which seems expected):
```
<html>
  <head>
    <meta charset="utf-8">
  </head>
  <body>
    <div id='myId'/>
  <script src="index_bundle.js"></script></body>
</html>
```

but if i use `webpack-dev-server`, it does something like this (which is unexpected: note that the script tag is nested inside the `myId` div tag):

![screen shot 2015-06-08 at 3 26 20 pm](https://cloud.githubusercontent.com/assets/1223231/8043261/d64fc3ca-0df2-11e5-8a44-ae0936291472.png)

it's probably benign, but i thought i would mention it while i spotted it.

in the future, i will probably try [@sokra's advice](https://github.com/webpack/webpack/issues/536#issuecomment-59530883) and render server-side

appreciate the assist,
tony.

**Comment by jantimon** [comment]
Just open localhost:8080 instead of localhost:8080/webpack-dev-server

**Comment by tony-kerz** [comment]
oh, nvm, when i adjust the syntax of the template to this (note explicit `</div>`):
```
<html>
  <head>
    <meta charset="utf-8">
  </head>
  <body>
    <div id='myId'></div>
  </body>
</html>
```

i get the expected:

![screen shot 2015-06-08 at 3 36 57 pm](https://cloud.githubusercontent.com/assets/1223231/8043465/62defe54-0df4-11e5-9a7c-996742642b25.png)

cheers!

**Comment by tony-kerz** [comment]
oh nice, and using `http://localhost:8080/` v `http://localhost:8080/webpack-dev-server/` skips the iframe fanci-ness, good tip as well, thx!
