### ISSUE TITLE
Inject files with preload and prefetch into head

### ISSUE THREAD

**Issue by matthiasg** [ampedandwired/html-webpack-plugin#532]
It would be nice if html-webpack-plugin could also generate <link rel="preload" … > and <link rel="prefetch" … > into head. Is this already possible or something that might be of interest ?

**Comment by jantimon** [comment]
You can already just add them to the template - Do you see any potential for auto generating them?

**Comment by szimek** [comment]
@jantimon Could you maybe show a sample code how to inject e.g. fonts using `<link rel="preload" as="font" href="..." crossorigin>`? I'm not really sure how to get urls to them (e.g. `https://mycdn.com/fonts/myfont-8879aba1192079fb82e409474682cef1.woff2`) after they are modified by webpack.

**Comment by matthiasg** [comment]
@jamesjieye not sure what you mean by that. right now my webpack setup automatically adds script tags to the generated scripts right before the </body> and the files have auto generated hashes in the names. it would be helpful if they are also added as preload entries before </head>. Is that what you are talking about ?

**Comment by jantimon** [comment]
@szimek I guess we don't have those information on the plugin level - it would require an additional loader-plugin combination
@matthiasg the browser is smart enough to preload/prefetch all css and javascript files linked in the code - so I don't see what we can do on the plugin level

**Comment by matthiasg** [comment]
@jantimon the case for preload is argued well over here https://hackernoon.com/10-things-i-learned-making-the-fastest-site-in-the-world-18a0e1cdf4a7#.qkgtuk71c. this is an extreme case of course, i was just wondering how easy it might be, to emit the extra lines into head from this plugin. i thought it would be a quite straight forward optional thing to do.

basically the preload goes into the <head>, the scripts go at the bottom (also preload can potentially be used to trigger downloading dynamically added files). scripts at the top block the render, scripts at the bottom start loading late.

**Comment by jantimon** [comment]
@matthiasg wow that's interesting - the html-webpack-plugin offers a hook which would allow exactly that but you would have to write a plugin to use the hook

**Comment by numical** [comment]
Hmm.. I'm trying to decide whether adding a 'resource hint' option to [script-ext-html-webpack-plugin](https://github.com/numical/script-ext-html-webpack-plugin) would be useful.
The functionality would be straight-forward enough - add a matching `<link rel="prefetch\preload" href="/library.js" as="script">` for selected `<script>` elements.
The question is whether this actually has any benefit. 
@jantimon states _the browser is smart enough to preload/prefetch all css and javascript files linked in the code_ but the clearest definition I can find is at [w3c](https://www.w3.org/TR/preload/#early-fetch-of-critical-resources) which indicates this is not quite so clear-cut.
Any opinions? 
On a related but separate issue would a separate plugin that dealt with all [resource hint options](https://www.w3.org/TR/resource-hints/) and all types of resources (not just scripts) have any real advantage over just putting them in a template?

**Comment by matthiasg** [comment]
When I posed the question I did not know about the templating mechanism inside which allows inserting this into head

```
<% for (var index in htmlWebpackPlugin.files.js) { %>
<link rel="preload" href="<%= htmlWebpackPlugin.files.js[index] %>" as="script">
<% } %>
``` 

but generally speaking, I would say that a plugin would be easier to approach and remove some potential errors. just like the html plugin emits script tags before body end by default and does not rely on templating for this either,

**Comment by jantimon** [comment]
@numical a new plugin would be nice and might be a great addition for https://github.com/facebookincubator/create-react-app

**Comment by jantimon** [comment]
@matthiasg https://github.com/jantimon/html-ressource-hints-plugin

**Comment by matthiasg** [comment]
@jantimon sure. https://github.com/jantimon/html-resource-hints-plugin/issues/1

Great work !

**Comment by jantimon** [comment]
Thanks 👍
