### ISSUE TITLE
it doesnot work when i use it with  the backend reader template ejs.

### ISSUE THREAD

**Issue by bryonliu** [ampedandwired/html-webpack-plugin#537]
whether there is a method that only append the <script> <link> in the file ,not as  a template.

**Comment by jantimon** [comment]
This should be possible - please move this question to stackoverflow and add a link here.

**Comment by bryonliu** [comment]
@jantimon  http://stackoverflow.com/questions/41454894/how-let-html-webpack-plugin-works-with-backend-render-ejs
