### ISSUE TITLE
Adding custom attributes to injected scripts tags

### ISSUE THREAD

**Issue by ellipticaldoor** [ampedandwired/html-webpack-plugin#538]
Hi,

Now webpack is injecting this in my index.html after **npm run build**

``` js
<script type="text/javascript" src="./static/js/manifest.0298f1f656f4d6c242e0.js"></script>
```

I want to add a **class** and  also change the attribute **src** to **data-src**, how I can do that?

**Comment by jantimon** [comment]
Set `inject:false` and use the template options

**Comment by ellipticaldoor** [comment]
Please, can you give me a hint in how to do it?

I'm searching and searching but I can't find an example.

If I put inject:false the css and scripts doesn't appear in the final index.html

What should I put in my index.html?

**Comment by jantimon** [comment]
See the readme:
https://github.com/ampedandwired/html-webpack-plugin#writing-your-own-templates

It also links to:
https://github.com/jaketrent/html-webpack-template/blob/master/index.ejs

**Comment by ellipticaldoor** [comment]
Thanks! It worked. A you said I leaved **inject: false**, renamed my template from **index.html** to **index.ejs**

and then where I want my scripts to load with custom attributes I did this

``` ejs
<% for (key in htmlWebpackPlugin.files.js) { %>
	<script type="text/javascript" data-src="<%= htmlWebpackPlugin.files.js[key] %>"></script>
<% } %>
```

**Comment by jantimon** [comment]
Cool 👍
