### ISSUE TITLE
Use with chunk-manifest-webpack-plugin

### ISSUE THREAD

**Issue by chiplay** [ampedandwired/html-webpack-plugin#54]
Has anyone been able to get https://github.com/diurnalist/chunk-manifest-webpack-plugin working with html-webpack?  

I'm trying to get longterm caching working with chunkNames, but my webpack bootstrap and chunk mapping is getting stored in my common chunk file (which doesn't work with hashed filenames).  

I'd love to have this plugin inject the window.webpackManifest variable into my index.html template, but I'm not quite sure how to go about it.  Any pointers?  Thanks!

**Comment by jantimon** [comment]
Do you have an example project with this plugin?

It works with https://github.com/lettertwo/appcache-webpack-plugin/ out of the box

**Comment by chiplay** [comment]
@jantimon I'm working on trying to integrate both right now and stumbling through it.  From what I can tell, chunk-manifest-webpack inserts a manifest.json file (not appcache) into the compilation.assets object, then its my job to insert that json into a `window.webpackManifest` variable (which I'd love to do dynamically using html-webpack).  It seems like I have access to a subset of the compilation.assets via `htmlWebpackPlugin.files` - but not all of them - eg. `htmlWebpackPlugin.files.all = compilation.assets` - which would probably do the trick, so that I could use `htmlWebpackPlugin.files.all['manifest.json']` in my template.  Thoughts?  

Is there another plugin that solves the same problem of extracting the module mapping out of the common chunk bundle so that I can do longterm chuckHash file caching?

**Comment by jantimon** [comment]
Actually it should be part of `o.webpack`.

**Comment by chiplay** [comment]
@jantimon it looks like `o.webpack` is [`webpack: webpackStatsJson`](https://github.com/ampedandwired/html-webpack-plugin/blob/master/index.js#L28) which is from [`var webpackStatsJson = compilation.getStats().toJson();`](https://github.com/ampedandwired/html-webpack-plugin/blob/master/index.js#L28).  From that object, I found it rather difficult to get to the manifest.json `source` content.  But, after some hacking, I was able to solve it with this quick fix:

```
templateContent: function(templateParams, compilation) {
  var fn = jade.compileFile(path.resolve('./app/index.jade'));
  templateParams.manifest = compilation.assets['manifest.json']._value;
  return fn(templateParams);
}
```

Hope this helps someone else!

**Comment by jantimon** [comment]
Cool looks nice :)  
Please note that we might deprecate `templateContent` for 2.0.

**Comment by chiplay** [comment]
@jantimon what would be the replacement for `templateContent`?  I'd love to go ahead and set it up correctly now while I'm at it.

**Comment by chiplay** [comment]
@jantimon I saw your progress on the 2.0 branch/PR - awesome work! Are you going to implement a replacement for templateContent? I saw chatter about a pre/postProcess step, but wasn't sure if that made the cut.  Thanks!

**Comment by jantimon** [comment]
Actually I would like to trigger an event but haven't looked into that.
This would allow to integrate other plugins more easily.
