### ISSUE TITLE
Webpack 2 error - Unexpected token   (1:0)   You may need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by faceleg** [ampedandwired/html-webpack-plugin#547]
I'm trying to update my project to webpack 2, and am getting the following error?

```
ERROR in   Error: Child compilation failed:
  Module parse failed: <PATH>web-frontend-wp2/node_modules/html-webpack-plugin/lib/loader.js!<PATH>/web-frontend-wp2/typescript/index.html Unexpected token   (1:0)
  You may need an appropriate loader to handle this file type.
  | <!DOCTYPE html>
  | <!--[if lt IE 7 ]> <html lang="en" class="ie6" <% if(htmlWebpackPlugin.files.manifest) { %> manifest="<%= htmlWebpackPlugin.files.manifest %>"<% } %>> <![endif]-->
  | <!--[if IE 7 ]>    <html lang="en" class="ie7" <% if(htmlWebpackPlugin.files.manifest) { %> manifest="<%= htmlWebpackPlugin.files.manifest %>"<% } %>> <![endif]-->:
```

```
html-webpack-plugin@beta:
  version "2.6.5"
webpack@beta:
  version "2.2.0-rc.7"
```

**Comment by jantimon** [comment]
Hm this looks familiar did you please check the FAQ?

**Comment by faceleg** [comment]
Yes sorry, fixed by prepending the correct loader to my template option

**Comment by eddiemonge** [comment]
How? According to faq and other docs, to use the default ejs loader, nothing is needed

**Comment by mpseidel** [comment]
mh, getting the same error with

**Comment by mpseidel** [comment]
mh, getting the same error with `ejs-html-loader`.
Tried 

`template: path/to/index.ejs`

plus the loader config

```
      {
        test: /\.ejs$/,
        loader: require.resolve('ejs-html-loader'),
      },
```

and also tried

`template: `!!ejs-html-loader!./path/to/index.js`

In both cases the ejs-html-loader gets used and returns the compiled html but html-webpack-plugin fails in the compilation after that. 

Surely I'm doing something wrong here (still new to how webpack works).
Apprecheate any pointers.

**Comment by mariotrucco** [comment]
As @eddiemonge points out, nothing should be needed for the default loader. 
In my case the error was caused by the template being located in the `src` dir.
Moving that out of  `src`  fixed the issue.
