### ISSUE TITLE
`favicon` key doesn't support data URIs

### ISSUE THREAD

**Issue by brandonb927** [ampedandwired/html-webpack-plugin#549]
webpack `2.2.0`
html-webpack-plugin `2.26.0`

I get this error when trying to use a data URI for a blank favicon:
```
ERROR in   Error: HtmlWebpackPlugin: could not load file /project/path/data:image/x-icon;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQEAYAAABPYyMiAAAABmJLR0T/8JWPfcAAAACXBIWXMAAABIAAAASABGyWs+AAAAF0lEQVRIx2NgGAWjYBSMglEwCkbBSAcACBAAAeaR9cIAAAAASUVORK5CYII=
```

It looks like the plugin is trying to load the data URI as if it were a local file in the filesystem. I might look into submitting a PR to fix this if nobody picks it up, it's not a deal breaker by any means but a nicety.

**Comment by jantimon** [comment]
Actually we planed to remove favicon from the HtmlWebpackPlugin because of https://github.com/jantimon/favicons-webpack-plugin

**Comment by brandonb927** [comment]
Ah ok I will use that plugin instead and close this Issue.

**Comment by morewry** [comment]
For anyone else wanting to do this, check out the linked issue. Apparently the favicon plugin doesn't support this either.
