### ISSUE TITLE
question: do i need <script src="http://localhost:8080/webpack-dev-server.js"></script> in my template for refresh/reload?

### ISSUE THREAD

**Issue by tony-kerz** [ampedandwired/html-webpack-plugin#55]
i've found that my template needs to look like (with the script tag):
```
<html>
  <head>
    <meta charset="utf-8">
  </head>
  <body>
    <div id='myId'></div>
    <script src="http://localhost:8080/webpack-dev-server.js"></script>
  </body>
</html>
```
to get either refresh or hot reload working with config similar to:
```
var HtmlWebpackPlugin = require('html-webpack-plugin')

module.exports = {
  entry: {
    app: [
      'webpack/hot/dev-server',
      './app/app.js'
    ]
  },
  output: {
    path: './build',
    filename: "bundle.js"
  },
  resolve: {
    extensions: ['', '.js'],
  },
  module: {
    loaders: [
      { test: /\.scss$/, loader: 'style!css!sass' },
      { test: /\.js$/, loader: 'babel', query: {stage: 1} }
    ]
  },
  devtool: 'cheap-module-eval-source-map',
  debug: true,
  plugins: [
    new HtmlWebpackPlugin({template: 'index.html', inject: 'body'})
  ]
};
```
is that expected, or is there any way to get the plugin to manage that script tag...?

on a related note, would it be accurate to say that, generally, the plugin only works against `http://localhost:8080/` and doesn't work against `http://localhost:8080/webpack-dev-server/bundle` as the latter hijacks `index.html`?

**Comment by jantimon** [comment]
Right now the plugin doesn't allow to inject the livereload script but it should be easy to add.
I would definitely merge a pull request.

**Comment by tony-kerz** [comment]
@jantimon here ya go: https://github.com/ampedandwired/html-webpack-plugin/pull/58

**Comment by jantimon** [comment]
Cool thanks - I will look into it soon :)

**Comment by roughcoder** [comment]
+1, having to bodge this in atm - the PR solution seems sound

**Comment by jantimon** [comment]
I would like to turn this rather in a boolean flag - also the webpack documentation asks not to do that (and I would like to clarify why):

http://stackoverflow.com/questions/31448534/inject-webpack-dev-server-js

**Comment by tony-kerz** [comment]
kk, i considered a boolean, but i think i went with an url based option because i wasn't sure if that url would ever change, but if you are comfortable with a boolean activating a hardcoded url, i am as well. 

also, valid question about stipulating an absolute path.

**Comment by jantimon** [comment]
I have also asked on the official webpack tracker: https://github.com/webpack/webpack/issues/1285

**Comment by jantimon** [comment]
Looks like this conflicts with `webpack --inline`. See http://stackoverflow.com/questions/31448534/inject-webpack-dev-server-js
