### ISSUE TITLE
is it possible for html-webpack-plugin to output an ejs file?

### ISSUE THREAD

**Issue by seanyu4296** [ampedandwired/html-webpack-plugin#551]

**Comment by jantimon** [comment]
Yes

**Comment by MichaelJC91** [comment]
Could you elaborate on how?

**Comment by jantimon** [comment]
Just use a loader like the raw loader which doesn't interfere with ejs

**Comment by donpinkus** [comment]
@jantimon - it seems that the default loader won't work with an EJS template.

Webpack tries to interpret all the EJS template variables. 

This example has a variable that is meant to be substituted by EJS, but webpack is interpreting it.

**Starting "template":**

```
<!DOCTYPE html>
<html>
  <head>
  	<meta charset="UTF-8">
  	<title>Monitor</title>
    <script>
      window.config = {
        API_URL: "<%= API_URL %>"
      }
    </script>
  </head>
  <body>
    <div class="container"></div>
  </body>
</html>
```
When you try to run webpack,

`ERROR in Template execution failed: ReferenceError: FOOBAR is not defined`

**Comment by jantimon** [comment]
@donpinkus as written before you can use the raw-loader: https://github.com/webpack-contrib/raw-loader

e.g. `raw-loader!index.ejs`

**Comment by seanyu4296** [comment]
what i actually did is have my simple nodejs server rename the normal html file to ejs then render that

`var express = require('express');
var path = require('path');
var compression = require('compression');
var ejs = require('ejs');
var fs = require('fs');

fs.rename(__dirname + '/dist/index.html', __dirname + '/dist/index.ejs', function (err) {
	if (err) {
		fs.stat(__dirname + '/dist/index.ejs', function (err) {
			if (err) return console.warn('ERROR:' + err);
		})
	}
	console.log("html to ejs success");
})
var app = express();

app.use(compression());
app.use(express.static('dist'));
app.set('view engine', 'ejs');
app.set('views', './dist');`

**Comment by aseem2625** [comment]
@seanyu4296 
What you told would work. But in your case, you must have hard coded  in your index.ejs like
```<script src="/js/bundle.js"></script>```

But he is asking what if this is dynamically getting build using webpack. For this you need to use html webpack plugin. 
Check [this](https://github.com/jantimon/html-webpack-plugin/issues/664)

**Comment by seanyu4296** [comment]
Oh i don't use raw-loader and i don't hard code my bundle.js. 
Here is my code to my index.ejs and webpack.config.prod.js

```
new HtmlWebpackPlugin({
			template: 'src/index.ejs',
			minify: {
				removeComments: true,
				collapseWhitespace: true,
				removeRedundantAttributes: true,
				useShortDoctype: true,
				removeEmptyAttributes: true,
				removeStyleLinkTypeAttributes: true,
				keepClosingSlash: true,
				minifyJS: true,
				minifyCSS: true,
				minifyURLs: true
			},
			inject: true,
			// Note that you can add custom options here if you need to handle other custom logic in index.html
			// To track JavaScript errors via TrackJS, sign up for a free trial at TrackJS.com and enter your token below.

			trackJSToken: trackJsToken,
			applicationName: 'pluggy',
			ejsVarInject: {
				api: '<%= api %>'
			}
		})

```

```
<script type="text/javascript">
  		var api;
  	<% if (htmlWebpackPlugin.options.ejsVarInject) { %>
  		api = "<%= htmlWebpackPlugin.options.ejsVarInject["api"] %>"
		<% } %>
		var globalConfig = {api: api }
  </script>
```

**Comment by aseem2625** [comment]
@seanyu4296 

lol.. This seems to be a hack for me.
```
ejsVarInject: {
	api: '<%= api %>'
}
```

But what's your output extension of .ejs file? Mine `index.ejs` become `index.html` which I don't want 😭
