### ISSUE TITLE
Use CSS Modules in Jade cause an Error: window is not defined

### ISSUE THREAD

**Issue by lltt-always** [ampedandwired/html-webpack-plugin#554]
Hi, I have a problem in using html-webpack-plugin, Could you help me to fix it?

Recently. When I tried to use CSS Modules in Jade, it throw an error like this:

```//ERROR
ERROR in Template execution failed: ReferenceError: window is not defined

ERROR in   ReferenceError: window is not defined

  - style.jade:450
    D:/repo/css-modules-jade-demo/src/style.jade:450:31

  - style.jade:445
    D:/repo/css-modules-jade-demo/src/style.jade:445:48

  - style.jade:467 module.exports
    D:/repo/css-modules-jade-demo/src/style.jade:467:69

  - style.jade:328 Object.<anonymous>
    D:/repo/css-modules-jade-demo/src/style.jade:328:37

  - style.jade:21 __webpack_require__
    D:/repo/css-modules-jade-demo/src/style.jade:21:30

  - style.jade:56
    D:/repo/css-modules-jade-demo/src/style.jade:56:11

  - style.jade:57 template
    D:/repo/css-modules-jade-demo/src/style.jade:57:138

  - index.js:262
    [css-modules-jade-demo]/[.npminstall]/html-webpack-plugin/2.26.0/html-webpac    k-plugin/index.js:262:16

  - util.js:16 tryCatcher
    [css-modules-jade-demo]/[.npminstall]/bluebird/3.4.7/bluebird/js/release/uti    l.js:16:23

  - promise.js:510 Promise._settlePromiseFromHandler
    [css-modules-jade-demo]/[.npminstall]/bluebird/3.4.7/bluebird/js/release/pro    mise.js:510:31

```

jade file and webpack configuration is just as follows.

```//style.jade
doctype html
- styles = require("!style!css?modules!./styles.css");
html(lang="en")
  body
    h1.global(class=styles.title) CSS Modules & Jade
```

```//webpack.config.js
var HtmlWebpackPlugin = require('html-webpack-plugin');
module.exports = {
    entry: "./entry.js",
    output: {
        path: __dirname,
        filename: "bundle.js"
    },
    module: {
        loaders: [
            { test: /\.jade$/, loader: "jade-loader" }
        ]
    },
    plugins: [
    new HtmlWebpackPlugin({
      filename: 'index.html',
      template: './src/style.jade',
      title: 'Jade demo',
      minify: false //不压缩html文件
    })]
};
```

If I delete plugins in webpack configuration, CSS Modules could work. And if I do not use CSS Modules, there is no error, but I really want use CSS Modules, please help me find this problem. Thank you very much!

**Comment by jantimon** [comment]
Looks like your css loader configuration requires a global window object which does not exist during build time

**Comment by lltt-always** [comment]
I've checked [css-loader](https://github.com/webpack/css-loader) but still did not find where need a global window object. And if it need a global window object, why could it build success without html webpack plugin?? I'm really confused.

**Comment by jantimon** [comment]
Okay so webpack prepares your jade file for the browser where they run in runtime.
The html-webpack-plugin however runs before anything is sent to the browser during build time to generate the html.

You are probably using a style loader which tries to add the css to the dom. 
And during build time there is no dom so the plugin will show error messages.

**Comment by lltt-always** [comment]
Thank you for your answer. Finally if I change 'template' to 'jade' will fix my error.
