### ISSUE TITLE
assets.manifest causes "ERROR in undefined is not a function"

### ISSUE THREAD

**Issue by chiplay** [ampedandwired/html-webpack-plugin#56]
On https://github.com/ampedandwired/html-webpack-plugin/blob/master/index.js#L305 there is a `.test` method called on the match, but it should be the other way around, with `.test` called on the regex:

```
if (/\smanifest\s*=/.test(match)) {
  return match;
}
```

**Comment by jantimon** [comment]
Oh.. Good point - looks like this has never been tested. 
Do you have time to write a pull request?

**Comment by chiplay** [comment]
I didn't have time to write a full test case, but its a pretty simple fix and I've verified its working correctly for our build.
