### ISSUE TITLE
How to ignore/pass-through template syntax?

### ISSUE THREAD

**Issue by jaredreich** [ampedandwired/html-webpack-plugin#566]
First of all thanks for this plugin.

My question is how do I ignore template syntax that I want to pass straight through?

Example index.html:

```html
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>

    <script>
      var env = '<%= env %>'
    </script>

  </head>
  <body>
    <div id="app"></div>
    <!-- built files will be auto injected -->
  </body>
</html>
```

I want the output to look like this:
```html
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <script>
      var env = '<%= env %>'
    </script>
    <link href="/app/css/app.5b2c9663a8f1949b441ccc3466c3b749.css" rel="stylesheet">
  </head>
  <body>
    <div id="app"></div>
    <script src="/app/js/manifest.7cfc7e6189125b769cb5.js" type="text/javascript">
    </script>
    <script src="/app/js/vendor.4b0a094e38b204393c9e.js" type="text/javascript">
    </script>
    <script src="/app/js/app.05271f8e097ca50453c7.js" type="text/javascript">
    </script>
  </body>
</html>
```
But it throws an error and gets hung on on the EJS template syntax I want to pass through:
`Template execution failed: ReferenceError: env is not defined`

Thanks very much for your help!

**Comment by jantimon** [comment]
Just use another loader for your template e.g. handlebars.

**Comment by jaredreich** [comment]
Ok thanks that does work. BUT now I have an unnecessarily installed loader in my project that is unused except for the purpose to avoid this issue.

**Comment by jantimon** [comment]
https://github.com/webpack-contrib/raw-loader/blob/master/index.js

**Comment by jantimon** [comment]
4 lines of code overhead is quite okay I guess ;)
