### ISSUE TITLE
Cannot read property 'options' of undefined with Jade template

### ISSUE THREAD

**Issue by nishyadav** [ampedandwired/html-webpack-plugin#567]
First of all thanks for this plugin.

I need help to understand what I am doing wrong with inline example.

Webpack configuration is 

```
new HtmlWebpackPlugin({
      inject: false,
      cache: false,
      template: './../server/views/index.jade',
      title: 'Jade demo',
    }),
```

In my Jade template

```
head
    meta(http-equiv="Content-type" content="text/html; charset=utf-8")
    title #{htmlWebpackPlugin.options.title}
    link(href='http://fonts.googleapis.com/css?family=Montserrat:400,600', rel='stylesheet')
body
    block content
```

I am unable to access htmlWebpackPlugin and getting this error.

```
Cannot read property 'options' of undefined
```

**Comment by jantimon** [comment]
Did you specify a jade loader somewhere?

**Comment by nishyadav** [comment]
Yes I specified that in webpack config as

`
{
        test: /\.jade$/,
        loader: 'jade-loader'
      }
`

**Comment by jantimon** [comment]
Please take a look at this example:
https://github.com/ampedandwired/html-webpack-plugin/blob/master/examples/jade-loader/

**Comment by giacomoalonzi** [comment]
@nishyadav did you solved this? I have the same problem with pug file

**Comment by weingartz** [comment]
@giacomoalonzi Same problem here. Did you solve it?

**Comment by mastilver** [comment]
@weingartz see #747 , it should help

**Comment by weingartz** [comment]
@mastilver Perfect, thanks.

**Comment by weingartz** [comment]
@mastilver 
The passing of the Option Vars like **title** works perfect - thank you. I load the files now with pug-loader and want to import the other vars via json - like the app of ciacomoalonzi.


     loader: 'pug-loader',
     query: {
        root: path.resolve(__dirname, 'src/views'),
      }

    ...

    plugins: [

        new HtmlWebpackPlugin({
            title: 'Home',
            chunks: ['index'],
            filename: 'index.html',
            template: './src/views/index.pug',
            data: require(`./src/content/home.json`)
        }),



But my file cannot read the property of my .json file. The loading of templates, includes and views works perfect. Do you have any idea?

**Comment by mastilver** [comment]
@weingartz It `should` be available under `htmlWebpackPlugin.options.data.<propName>`

**Comment by weingartz** [comment]
@mastilver Now it works - perfect. I wrote the wrong syntax. Thank you so much - made my day!
