### ISSUE TITLE
How to add styles

### ISSUE THREAD

**Issue by bitplanets** [ampedandwired/html-webpack-plugin#6]
module: {
        loaders: [
            {
                test: /\.scss$/,
                loader: ExtractTextPlugin.extract("style", "css!sass")
            },

    plugins: [
        new ExtractTextPlugin("style.[hash].css", {
            allChunks: true
        }),
        new HtmlWebpackPlugin({
            template: 'src/client/index.html',
            "assets": {
                "client" : "client.[hash].js",
                "style"  : "style.[hash].css",
            }
        })
    ]

template:

    <!DOCTYPE html>
    <html>
      <head>
        <meta http-equiv="Content-type" content="text/html; charset=utf-8"/>
        <title>My App</title>
      </head>
      <body>
        <link href="{%=o.htmlWebpackPlugin.assets.style%}" media="all" rel="stylesheet" type="text/css">
        <script src="{%=o.htmlWebpackPlugin.assets.client%}"></script>
      </body>
    </html>

**Comment by mateatslc** [comment]
try:
```html
<link rel="stylesheet" href="[prepend_your_public_path/]{%=o.webpack.assetsByChunkName.client[1]%}">
```
more details here: https://github.com/ampedandwired/html-webpack-plugin/issues/1

**Comment by ampedandwired** [comment]
Thanks @bitplanets, some good ideas there, and apologies for not getting back to you sooner. I'm going to put a bit of work into making this a bit easier, as well as addressing the script ordering problem.

**Comment by jantimon** [comment]
The pull-request #14 supports the ExtractTextPlugin

**Comment by ampedandwired** [comment]
@jantimon's PR #14 allows for styles to be included, so closing this for now. Let me know if this doesn't meet your needs.

**Comment by IronSean** [comment]
I think this could use some more explicit documentation. Especially in the use case of multiple chunks going to the the head and/or body.
