### ISSUE TITLE
gzip/compression support

### ISSUE THREAD

**Issue by nevir** [ampedandwired/html-webpack-plugin#61]
It doesn't appear like the generated source gets piped through the rest of the webpack plugins (compression, for example). It'd be neat to support that

**Comment by jantimon** [comment]
sounds good - what has to be changed to achieve that?

**Comment by sunyang713** [comment]
hi, was this issue resolved, or is it being disregarded?

**Comment by jantimon** [comment]
I don't use the plugin and it probably has to be fixed in the gzip module.
Maybe you could jump in and implement it.

**Comment by sunyang713** [comment]
I see... okay. do you have any pointers on how to do this? my guess is `html-webpack-plugin` must inject the script tags after compilation, but `compression-webpack-plugin` happens after that, which is why the script tags don't point to the right files.

**Comment by mastilver** [comment]
Looks like this is being resolved by: https://github.com/webpack-contrib/compression-webpack-plugin/pull/45
