### ISSUE TITLE
How to pass template parameters

### ISSUE THREAD

**Issue by jonira** [ampedandwired/html-webpack-plugin#63]
side story: Just starting to integrating webpack to replace requirejs.

How to pass template parameters to custom template?

**Comment by jantimon** [comment]
The example on [write your own templates](https://github.com/ampedandwired/html-webpack-plugin#writing-your-own-templates) shows how to pass the `title` parameter to a custom template.

Please let me know if this what you were looking for :)

**Comment by borNfreee** [comment]
What is I need to pass custom variable (not from this list https://github.com/ampedandwired/html-webpack-plugin#configuration)?

**Comment by jantimon** [comment]
It will pass all variables to the templates so you can define your own. E.g. `longTitle`

**Comment by koko236** [comment]
I was looking for the same thing. So it seems like to access plugin options from the template I need to reference them as `htmlWebpackPlugin.options`. That's quite verbose. Is there any way to define a 'variables' object in plugin options that could serve as 'root' for the template variables?

***

Eg. say I'm using Mustache. Using JS I'd render like this:

`Mustache.render(template, {title: 'Hello', lang: 'en'}, {partial1: 'partial'});`

Then I can simply use the variables like:

`<h1>{{ title }}</h1>
<img src="speechbubble_{{lang}}.png"/>`

and so on. Is something similar possible with html-webpack-plugin?

**Comment by jantimon** [comment]
nope because of legacy reasons - but I really like the idea

**Comment by StalkAlex** [comment]
it's not working anymore or I'm doing something wrong, cause it's injecting custom variable only if I set `inject: false`, but it's not what I want because in this case it's not injecting my bundles.

**Comment by StalkAlex** [comment]
it works with 
```js
  new HtmlWebpackPlugin({
    template: '../html/index-template.html',
    env: {
      Prod: !prodFlag,
    },
  }),
```
and read then as `htmlWebpackPlugin.options.env.Prod` but according to documentation it suppose to work with
```js
 new HtmlWebpackPlugin({
    template: '../html/index-template.html',
    prod: true
  }),
```
and `htmlWebpackPlugin.options.prod`

**Comment by mqklin** [comment]
What's the case for `templateParameters` then?
