### ISSUE TITLE
Specify absolute URL of emitted resources?

### ISSUE THREAD

**Issue by billyjanitsch** [ampedandwired/html-webpack-plugin#67]
I want to serve my `index.html` at a variety of routes: `/`, `/a`, `/a/b`. (This is a Backbone app that does internal routing on a single page.)

Currently, the generated html links to relative resources, assuming that it will only be served from the directory where it's generated. When you instead serve it from `/a/b`, it looks for resources like `bundle.js` in `/a/bundle.js`, which doesn't exist.

Would you consider adding a config option to link to "absolute" URLs (relative to the output path, e.g. `/bundle.js`) instead of relative ones?

**Comment by jantimon** [comment]
Hi billy this is already possible:
https://github.com/ampedandwired/html-webpack-plugin/blob/master/index.js#L177

All you have to do is to specify a public path in your configuration.

**Comment by billyjanitsch** [comment]
Sorry, I missed that in the webpack docs. Thank you!
