### ISSUE TITLE
blueimp template typo on npm page

### ISSUE THREAD

**Issue by chevin99** [ampedandwired/html-webpack-plugin#68]
Not sure if this is where I should report this, but, there's a missing % sign in an example on the [npm page](https://www.npmjs.com/package/html-webpack-plugin).  I copied/pasted the example but I kept getting an error like this "ERROR in HtmlWebpackPlugin: template error Syntax Error: Unexpected token =", but finally realized it was because of the missing % sign.

<img width="606" alt="screen shot 2015-07-07 at 2 49 38 pm" src="https://cloud.githubusercontent.com/assets/7562346/8557041/04557842-24b8-11e5-98d0-6583f7c23046.png">

By the way, this plugin is a huge help!

**Comment by jantimon** [comment]
Thanks will publish a new version soon :+1:

**Comment by jantimon** [comment]
fixed :)
