### ISSUE TITLE
`entry` configuration option undocumented

### ISSUE THREAD

**Issue by mark-rushakoff** [ampedandwired/html-webpack-plugin#72]
In the Configuration section of the README, `entry` is not in the list of documented options, but it is used in the example.

**Comment by jantimon** [comment]
What do you mean exactly?

**Comment by mark-rushakoff** [comment]
The bullet points under Configuration, for the allowed keys for the options for this plugin, include `title`, `filename`, etc. Those bullet points do not include `entry`, which is used in the example immediately following those bullet points.

**Comment by jantimon** [comment]
Do you mean the webpack configuration?

This is just the html plugin for webpack

**Comment by mark-rushakoff** [comment]
*facepalm*

Apparently I lost all my reading comprehension skills for a while there. Nevermind, closing the issue.
