### ISSUE TITLE
Separate css and js directories lead to incorrect paths in html

### ISSUE THREAD

**Issue by ericmatthys** [ampedandwired/html-webpack-plugin#78]
```js
{
  output: {
    path: path.resolve('build/js'),
    publicPath: '',
    filename: '[name].js'
  },

  plugins: [
    new ExtractTextPlugin('../css/[name].css'),

    new HtmlPlugin({
      template: 'example.html',
      filename: '../index.html'
    })
  ],

  ...
}
```

The structure ends up looking like:

```
build/
    index.html
    js/
        main.js
    css/
        main.css
```

Using `o.htmlWebpackPlugin.files` in the template, the link and script tags end up looking like:

`<link href="../css/main.css" rel="stylesheet">`
`<script src="main.js"></script>`

Expected:

`<link href="css/main.css" rel="stylesheet">`
`<script src="js/main.js"></script>`

**Comment by jantimon** [comment]
Hm could you create a pull request?

**Comment by ericmatthys** [comment]
This issue is resolved if the `js/` segment is included in the `filename` / `chunkFilename` and kept out of the `path`. This way, the `filename` provided to `HtmlPlugin` does not need the `../`.

**Comment by idolize** [comment]
@ericmatthys This is not a great workaround, in my opinion. Trying to get all the other plugins/loaders to add the additional directory path everywhere is not trivial (I tried, and ran into issues with `postcss-loader` and `extract-text-webpacl-plugin`).

It would be so nice if we could just use a `../index.html` for the `filename` :disappointed:

**Comment by ericmatthys** [comment]
@idolize Are you setting `publicPath` appropriately?
