### ISSUE TITLE
Meta images

### ISSUE THREAD

**Issue by mxstbr** [ampedandwired/html-webpack-plugin#82]
In my .html file, I have a meta tag like this:

```HTML
<meta property="og:image" content="/img/screenshot.png">
```

When I build the file, that image does not get moved over to the build folder. I've also tried this, and it didn't work:

```HTML
<meta property="og:image" content="<%= require('./assets/img/touch-icon-iphone.png') %>">
```

Any ideas how to achieve that the image gets moved to the build folder?

**Comment by jantimon** [comment]
You could use the loader branch (2.0) of the plugin
