### ISSUE TITLE
How to use plugin with webpack-dev-server?

### ISSUE THREAD

**Issue by amorphius** [ampedandwired/html-webpack-plugin#94]
Hi! I have problem when using plugin with webpack-dev-server. 

I've rendered my index.html but it stays in memory, not in the `content-base` folder where static should be located. So browser cannot find any index.html and gives 404 error.

**Comment by jantimon** [comment]
Hi - could you send me a minimal project setup so I can try to reproduce the error?

**Comment by amorphius** [comment]
I fixed it after setting `publicPath` to "/". Didn't work with any other path.
