### ISSUE TITLE
require.ensure modules are inserted into html.

### ISSUE THREAD

**Issue by shlomiassaf** [ampedandwired/html-webpack-plugin#95]
Since require.ensure modules are implicitly declared async modules they should not appear in the final html.

**Comment by jantimon** [comment]
Absolutely - could you please open a pull request?

**Comment by shlomiassaf** [comment]
I will, but before that...

Does webpack give any insight on the assets type, meaning sync or async?

I didnt find any reference to it, so it might not be possible...
A workaround is already supported via ignores..

**Comment by vyorkin** [comment]
its `chunk.initial`, I'll submit a PR

**Comment by jantimon** [comment]
Okay cool will merge it soon for both branches
