### ISSUE TITLE
Regression when using minify in v1.6.2

### ISSUE THREAD

**Issue by cesarandreu** [ampedandwired/html-webpack-plugin#97]
#81 is a breaking change, it shouldn't be released in v1.6.2. I was passing in true or false depending on my environment, (admittedly I hadn't looked at my output, I just assumed it was being minified) and the v1.6.2 release broke my builds.

Adding a check such as: `minify = minify === true ? {} : minify` could be released as v1.6.3 and it would preserve backwards compatibility.

**Comment by davezuko** [comment]
Got bit by this as well, would be great to get this fixed. Thank you!

**Comment by frederickfogerty** [comment]
Commenting here with a fix, you need to replace `minify: true` with an [html-minify options config](https://github.com/kangax/html-minifier#options-quick-reference)

**Comment by SimenB** [comment]
Ah, sorry :sob: I did comment on it though https://github.com/ampedandwired/html-webpack-plugin/pull/81/files#r37053625
