### ISSUE TITLE
historyApiFallback + generated script/link tags

### ISSUE THREAD

**Issue by luisrudge** [ampedandwired/html-webpack-plugin#98]
Currently, the plugin generates this:

`<script src="app.js?6be84a4f96612dd43e8d"></script>`

But, when using webpack-dev-server + historyApiFallback and html5 routing (react-router, for example), it fails to fetch the correct file.

Example:
* navigate to localhost/users/123
* save a file
* webpack reloads the page
* **ERROR: 404 not found**: http://localhost/users/app.js?[hash]

Maybe we should add an option to add the root slash or something

**Comment by jantimon** [comment]
wouldn't solve setting a publicPath your issue?

**Comment by luisrudge** [comment]
set publicPath to what?

**Comment by luisrudge** [comment]
oh, ok. setting publicPath worked indeed. Thanks!

```js
  output: {
    publicPath: '/',
  }
```

**Comment by caesarsol** [comment]
Would it make sense to include this hint somewhere in the docs? :)
